### ISSUE TITLE
Issues with user-defined types

### ISSUE THREAD

**Issue by chepner** [dhall-lang/dhall-lang#10]
It's (sort of) possible to create a new type:

```
% dhall <<< 'let Day : Type = Natural in Day'
Type

Natural
```

It doesn't appear possible to do anything with said type, though:

```
% dhall <<< 'let Day : Type = Natural in \(d : Day) -> d'

Use "dhall --explain" for detailed errors

Error: Unbound variable

Day

(stdin):1:35
```

It seems like `Day` should be defined, leaving aside the issue of how one would create a value of type `Day` in the first place. (It doesn't appear to simply be a synonym for `Natural`, as evidenced by

```
% dhall <<< 'let Day : Type = Natural in \(d : Day) -> d + +1'

Use "dhall --explain" for detailed errors

Day : Type
d : Day

Error: ❰+❱ only works on ❰Natural❱s

d + +1

(stdin):1:43
```
)

**Comment by Gabriel439** [comment]
The second example failing:

```bash
$ dhall <<< 'let Day : Type = Natural in \(d : Day) -> d'
```

... is definitely a bug in Dhall.  That example should succeed because Dhall requires that any `let` expression of the form:

```haskell
let x : t = e1 in e2
```

... must behave the same as:

```haskell
(λ(x : t) → e2) e1
```

... for both type-checking and normalization.  The only difference between the two (in theory) is that Dhall changes the type-checking error messages for `let` to be more `let`-specific, but in practice there may be small errors in the implementation that cause `let` to deviate from the required behavior (such as this bug)

Indeed, if you rewrite the `let` as the equivalent lambda expression then the example does type-check:

```haskell
$ dhall <<< '(λ(Day : Type) → λ(x : Day) → x) Natural'
∀(x : Natural) → Natural

λ(x : Natural) → x
```

I have a pull request up with the fix here: https://github.com/dhall-lang/dhall-haskell/pull/134

The third example should definitely fail, though:

```haskell
$ dhall <<< 'let Day : Type = Natural in \(d : Day) -> d + +1'
```

... for the same reason, which is that Dhall requires that the behavior is equivalent to:

```haskell
$ dhall <<< '(λ(Day : Type) → λ(d : Day) → d + +1) Natural'

Use "dhall --explain" for detailed errors

Day : Type
d : Day

Error: ❰+❱ only works on ❰Natural❱s

d + +1

(stdin):1:31
```

That fails to type-check for the same reason that the anonymous function in isolation fails to type-check:

```haskell
$ dhall <<< 'λ(Day : Type) → λ(d : Day) → d + +1'

Use "dhall --explain" for detailed errors

Day : Type
d : Day

Error: ❰+❱ only works on ❰Natural❱s

d + +1

(stdin):1:30
```

Dhall's core semantics (ignoring imports) are specified in terms of System Fω, which does not have a mechanism for encoding type synonyms.  However, you can use the import system to work around this limitation, by doing this:

```haskell
$ echo 'Natural' > ./Day
$ dhall <<< 'λ(d : ./Day) → d + +1'
∀(d : Natural) → Natural

λ(d : Natural) → d + +1
```

If you want `newtype`-like behavior, then the easiest way to get that is to wrap the type in a record with one field (just like Haskell):

```haskell
$ echo '{ getDay : Natural }' > ./Day
$ dhall <<< 'λ(d : ./Day) → d.getDay + +1'
∀(d : { getDay : Natural }) → Natural

λ(d : { getDay : Natural }) → d.getDay + +1
```

... or (more verbose) a union with one alternative:

```haskell
$ echo '< Day : Natural >' > ./Day
$ dhall <<< 'λ(d : ./Day) → merge { Day = λ(y : Natural) → y + +1 } d'
∀(d : < Day : Natural >) → Natural

λ(d : < Day : Natural >) → merge { Day = λ(y : Natural) → y + +1 } d
```

**Comment by chepner** [comment]
Right, I expected `let Day : Type = Natural in \(d : Day) -> d + +1` to fail. The question I was leading up to was, indeed, if there was a way to create a value of a new type.

**Comment by Gabriel439** [comment]
Do you consider the question answered, then, or are you still looking for another solution?

**Comment by chepner** [comment]
I think the record- and union-based approaches are sufficient, or at least I don't have any real argument for adding dedicated data constructors.
