### ISSUE TITLE
Lack of unification prevents true separation of data and type "schema"

### ISSUE THREAD

**Issue by deepfire** [dhall-lang/dhall-lang#103]
The type inference algorithm goes in a single direction / isn't unification, which makes the interesting use case of data/schema separation less ergonomic/useful.

Case in point:

```
[nix-shell:~/daedalus/installers]$ dhall
{ a = ["a"] } : { a : Optional Text }

Use "dhall --explain" for detailed errors

Error: Expression doesn't match annotation

{ a = ["a"] } : { a : Optional Text }

(stdin):1:1
```
..but:
```
[nix-shell:~/daedalus/installers]$ dhall
{ a = ["a"] : Optional Text } : { a : Optional Text }
{ a : Optional Text }

{ a = [ "a" ] : Optional Text }
```

**Comment by deepfire** [comment]
This is somewhat related to #73

**Comment by Gabriel439** [comment]
Yeah, this will likely be the case for the foreseeable future

The main reason why Dhall is designed this way is because Dhall is "completely functional" meaning that there is no logic programming component (whether at the type-level or otherwise) and therefore no unification.  All automation in Dhall is based around functions, including type-level automation.  This is why type abstraction and type application are explicit.  If something is repetitive you use a function to reduce the repetition.

Dhall is also based on a "pure type system" which means that there is no syntactic distinction between  term-level programming and type-level programming.  This is why you use the notation to abstract and apply types and terms.  This is also why you use the same `let` notation to define type synonyms and you can also (more recently on `master`) store types in records/unions.  Because there isn't a strict separation between the term and type level there will never really be a separation of data and schema.

That does mean that it is less ergonomic in the small but it also means that it is far more straightforward to debug and errors are better localized because type inference is only done in the forward direction.  It also makes the type-checking algorithm easier to explain and reason about because there is no subtyping relationship between polymorphic and monomorphic terms and the conversions between them are explicit instead of implicit.

**Comment by Gabriel439** [comment]
I will go ahead and close this, but feel free to reopen if there are additional questions
