### ISSUE TITLE
No way to import an environment variable which may be undefined

### ISSUE THREAD

**Issue by nescohen** [dhall-lang/dhall-lang#1048]
I would like to be able to at least provide a default value for an environment variable I want to import. Otherwise trying to run the configuration file with an undefined environment variable will result in an error.

e.x. I have a flag imported from the environment, but I need to read a different value out of the same config in another context. Still get this error:
```
Error: Missing environment variable

↳ USE_SINK

27│                env:USE_SINK
```

**Comment by sjakobi** [comment]
Are you aware of `?`? E.g.

```
⊢ env:UNDEFINED ? 42

42
```

**Comment by Gabriel439** [comment]
@nescohen: You can use the import fallback operator (`?`) to do this.  Here is an example usage of the operator:

```dhall
env:USE_SINK ? False
```

**Comment by nescohen** [comment]
Ahh.. clearly not. Thanks. Perhaps I will submit a PR to add a hint here: https://hackage.haskell.org/package/dhall-1.33.1/docs/Dhall-Import.html

**Comment by nescohen** [comment]
@Gabriel439, Yes, this will work well. Thanks!

**Comment by Gabriel439** [comment]
@nescohen: Perhaps I can update the Haskell tutorial to link to the [Language Tour](https://docs.dhall-lang.org/tutorials/Language-Tour.html) since that includes a section explaining the fallback operator:

* [Language Tour - Alternative imports](https://docs.dhall-lang.org/tutorials/Language-Tour.html#alternative-imports)
