### ISSUE TITLE
reference current record?

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-lang#107]
I was trying to build a record of functions and couldn’t figure out how to reference other fields in the same record, so I started chaining them as below:
```
      let foo = { g = λ(a : Natural) → λ(b : Natural) → a + b }
  in  let fooo = foo ⫽ { h = λ(a : Natural) → foo.g a +2 }
  in  fooo ⫽ { i = fooo.g (fooo.h +4) }
```
so that the final record has `g`, `h`, and `i` in it.

**Comment by Gabriel439** [comment]
Yeah, this restriction is very intentional in order to prevent infinite loops

The way I would organize this is to define the fields in a certain order and then pack them into a record at the end, like this:

```
    let g = λ(a : Natural) → λ(b : Natural) → a + b

in  let h = λ(a : Natural) → g a +2

in  let i = g (h +4)

in  { g = g, h = h, i = i }
```

**Comment by sellout** [comment]
Ah, I like that better. Thanks.

Would it be acceptable if I implemented something that ensured there were no cycles in the fields? I’ve done something similar in a total language I wrote (pretty simple if you just require that fields can only reference fields defined “above” them, much like nested `let`s). No promises, but if it wouldn’t be rejected outright, I would keep it in the back of my mind as I dive deeper into Dhall.

**Comment by Gabriel439** [comment]
I think the main pros are:

* It allows dependent records (especially now that they can store types for fields)
* It's a common idiom in other configuration languages

I think the main cons are:

* It's not clear if records with different field order are the same type.  If not, that would be a bit weird
* Sorting or reordering fields for clarity of configuration is no longer automatically safe

Overall I'm probably slightly against since it overlaps with nested `let` and I try to avoid having two idioms to do the same thing.  I think the more compelling motivation is dependent records but nobody has requested that yet.

However, if you feel strongly about the idea then I can set up a process for voting on proposed changes to the language where I don't exercise veto power over proposed features.

**Comment by sellout** [comment]
No, that’s fine – I’m definitely still getting my feet wet. I agree with trying to keep things orthogonal.

**Comment by sellout** [comment]
BTW, I would love some way to construct dependent records. I think that’s all that’s needed in order to implement `Nu` for corecursive fixed-points, no?

**Comment by Gabriel439** [comment]
Yeah, I'm not ruling out dependent records (or even ordered records).  I was thinking that if we do introduce that at some point it might be as a new separate construct with its own syntax
