### ISSUE TITLE
Simplify if x then y else y to y?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#108]
Is it worth having the normalization step

```
l ⇥ x   r ⇥ x
─────────────────────── 
if t₀ then l else r ⇥ x
```

?

**Comment by Gabriel439** [comment]
Yeah, that seems reasonable to me.  Would you like to open a pull request to update the semantics?

Note that because this is comparing expressions for equality you have to explicitly specify the equivalence relation like this:

```
l ⇥ x₀   r ⇥ x₁   x₀ ≡ x₁
──────────────────────── 
if t₀ then l else r ⇥ x₀
```

It's probably also worth doing the same for other boolean operators, such as `x && x = x` and `x == x = True`

**Comment by ocharles** [comment]
Sure, I can do that. Can you assign this one to me as well? I'm hoping to find some time to do some hobby hacking tonight.
