### ISSUE TITLE
need for a generic HomogenousRecord type

### ISSUE THREAD

**Issue by uwedeportivo** [dhall-lang/dhall-lang#1081]
right now it's not really possible to write generic functions that would leverage `toMap` and operate on homogenous records of some field value type.

this new HomogenousRecord would be similar to `List`, so` HomogenousRecord Natural` would be a type of records where all the field values are `Natural`s.

this would allow the definition of functions that build on top of `toMap` like so:

```
let Map/values =
      https://prelude.dhall-lang.org/v18.0.0/Map/values

let recordList
    : ∀(xs : HomogenousRecord Natural) → List Natural
    = λ(xs : HomogenousRecord Natural) → Map/values Text Natural (toMap xs)

let example1 =
        assert
      :   recordList {a = 2, b = 3, c = 4}
        ≡ [2, 3, 4]

let example2 =
        assert
      :   recordList {f = 1, g = 2}
        ≡ [1, 2]

in  recordList
```
note that `{a = 2, b = 3, c = 4}` and `{f = 1, g = 2}` are records of different types but both are `HomogenousRecord Natural`.

`toMap` would need to change to accept `HomogenousRecord <Type>`.

**Comment by Gabriel439** [comment]
@uwedeportivo: I believe this would be difficult to standardize and implement because it would entail adding a form of subtyping to the type system and also mean that we would no longer have a principal type for record types.

For the specific example you gave I would have written it this way:

```dhall
let Map = https://prelude.dhall-lang.org/v18.0.0/Map/Type

let HomogeneousRecord = Map Text

let Map/values =
      https://prelude.dhall-lang.org/v18.0.0/Map/values

let recordList
    : ∀(xs : HomogenousRecord Natural) → List Natural
    = λ(xs : HomogenousRecord Natural) → Map/values Text Natural xs

let example1 =
        assert
      :   recordList (toMap {a = 2, b = 3, c = 4})
        ≡ [2, 3, 4]

let example2 =
        assert
      :   recordList (toMap {f = 1, g = 2})
        ≡ [1, 2]

in  recordList
```

I know that you're probably aware of that solution already and you're trying to avoid the need for the `toMap` keyword (or at least make it more ergonomic), so perhaps another solution I could suggest is to provide something like `{{ ... }}` notation for homogeneous maps to distinguish them from record types.  The main thing is that there needs to be some sort of term-level distinction between records and homogeneous maps in order to keep the type system simple.

**Comment by uwedeportivo** [comment]
@Gabriel439 got it, makes sense.

**Comment by f-f** [comment]
@Gabriel439 alternatively it sounds like this could be another place where something like #979 could work?

**Comment by Gabriel439** [comment]
@f-f: Yeah, I was about to suggest that, but then I noticed that the example given was only converting the other way around: from records to `Map`s
