### ISSUE TITLE
Add test for CORS compliance

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-lang#1130]
There was a bug in the Haskell implementation's CORS compliance check (see: https://github.com/dhall-lang/dhall-haskell/pull/2121), which highlighted that the test suite is missing a test to verify this language requirement

**Comment by Nadrieril** [comment]
I would like that too! Let's see what we need:
- [ ] check that imports from local to remote ignore the CORS headers
- [ ] check that same-domain imports ignore the CORS headers
- [ ] check that cross-domain imports fail in the absence of CORS headers
- [ ] check that cross-domain imports succeed with a "*" CORS
- [ ] check that cross-domain imports succeed with CORS that does include the domain
- [ ] check that cross-domain imports fail with CORS that doesn't include the domain
- [ ] check that imports with two hops use the correct domain to check CORS
- [ ] check that a remote import can import the prelude (since that's arguably the most important remote import)

Anything else?

Here's what we can do:
- set up a few files on test.dhall-lang.org with various combinations of CORS headers
- commit some files that have imports pointing to test.dhall-lang.org
- add some tests that import the above via raw.githubusercontent.com

I think with that we can cover everything without changing our infrastructure. For the two-hop one we can do test.dhall-lang.org -> github -> test.dhall-lang.org with the last file blocking raw.githubusercontent.com.

**Comment by Gabriel439** [comment]
@Nadrieril: The only other thing I can think of is we could also verify that a Dhall implementation does not honor `Access-Control-Allow-Methods` or `Access-Control-Allow-Headers` (since the standardized behavior does not exactly match CORS).  I'm not sure if that's worth testing or if we just amend the standard to say that an implementation can optionally implement CORS more rigorously than what is specified.

**Comment by Nadrieril** [comment]
Hm, I'd rather allow implementations to be stricter here, in case there's a standard CORS library they can use to avoid doing the checks by hand.

**Comment by Gabriel439** [comment]
Yeah, I'd be fine allowing implementations to be stricter

**Comment by Nadrieril** [comment]
We have all those tests now!
