### ISSUE TITLE
Small explainer for Let .. in

### ISSUE THREAD

**Issue by thebritican** [dhall-lang/dhall-lang#1144]
Many of my coworkers have run into the same issue learning Dhall syntax. 

"What does the `in` keyword do?"
"Is `in` how you define module exports?"

Here's all the spots in the docs we could find that reference `let`.

1. https://docs.dhall-lang.org/references/Built-in-types.html#keyword-let
1. https://docs.dhall-lang.org/howtos/Cheatsheet.html#programming
1. https://docs.dhall-lang.org/tutorials/Language-Tour.html#let-expressions

The closest doc to explaining `in` is the Language Tour section, but none of them explain their semantic correlation, only that `let` must come before `in`.

This section from [LYAH](http://learnyouahaskell.com/syntax-in-functions#let-it-be) helped it click for a coworker:

> The form is let \<bindings\> in \<expression\>. The names that you define in the let part are accessible to the expression after the in part. 

Should we add something like this? I'm happy to make a PR, but I want to get thoughts first on how else we can explain `let .. in` or where else the explainer should live

**Comment by timbertson** [comment]
I agree, this has been surprisingly one of the biggest stumbling blocks for my team too.

> The names that you define in the let part are accessible to the expression after the in part

That doesn't quite describe dhall, since every `let` binding is immediately visible to following `let`s as well, not just "stuff after the `in`".

I've been musing on this, and if I got to pick an explanation I'd probably go for something like:

> Everything in dhall is an expression. So a file can simply contain an expression like `"Hello World"` (type `Text`) or `\(i: Natural) -> i + 1` (type `Natural -> Natural`).

> Often, you'll want to give expressions a name to clarify intent or to reuse an expression.

> To give a name to an expression, you can use `let <name> = <expression>`. But this `let` binding isn't itself an expression, it has no value. To give the "resulting value" after one (or more!) `let` bindings, you place the expression after the `in` keyword. Like so:

```dhall
let x = 1
let y = 2
in
x + y
```

> Often a large dhall file will be a long series of `let` bindings, ending with an `in` followed by a record with all of the module's functionality as fields. This might look like a "module system" or "exports definition" from other languages, but there is no special-casing of this structure in dhall - the result of a file can be any valid dhall expression.

**Comment by Gabriel439** [comment]
There are potentially two sources of confusion that might explain why they stumble on this:

* They might be used to a statement-oriented programming language (i.e. most mainstream programming languages)

  Dhall is an expression-oriented programming language, so there is no concept of a statement.  So they see the `let` keyword and think "Oh, this must be a variable assignment like `val` in JavaScript" and then they're wondering why there is an "`in` statement".

* They are used to multiple top-level bindings

  Most programming languages let you define multiple values/functions at the top level of the program, whereas in Dhall is there is only a single top-level expression (the entire file), and the only way you can "export" multiple values is to collect them in a record.

What I propose doing is:

* amending the Language Tour to clarify the above two points about Dhall since I believe that is the most appropriate place for the detailed explanation
* amending the cheatsheet and built-in documentation with a small snippet that says something like:

  > To a first approximation, you can think of `let x : A = a let y : B = b in e` as the same thing as `(λ(x : A) → λ(y : B) → e) a b`
  
  … which is true so long as `x` and `y` are not types and you gloss over the fact that `let` bindings can omit the type annotation (unlike the equivalent lambdas).

**Comment by Gabriel439** [comment]
I have a fix for this up here: https://github.com/dhall-lang/dhall-lang/pull/1147
