### ISSUE TITLE
open record type?

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-lang#116]
I‘m wondering if it’d be feasible to add an open record type:
```dhall
λ(t : { foo : Natural … }) -> t.foo
```
so that function can be applied to any record that has a `foo` field of type `Natural`, without caring what else may be in that record.

**Comment by Gabriel439** [comment]
I've always had an unstated "no subtyping" rule when designing Dhall.  Formally, the rule is that types that are not α-equivalent or β-equivalent must be treated as distinct types and conversions between them must be explicit at the term level.  The motivation for this rule is:

* Simpler semantics
* Easier to teach the language since users don't have to reason about unification

This is why Dhall does not treat the type `∀(a : Type) → a → a` as equivalent to the type `Integer → Integer` and you have to use an explicit type application to convert a value of the former type to a value of the latter type.  In general, the no subtyping rule tends to also imply no unification in the type-checking semantics.

Note that this rule technically does not forbid row polymorphism, but it makes it more verbose.  For example, under this restriction the type and term would look something like this:

```haskell
    let example : ∀(b : Row) → ∀(t : { foo : Natural | b }) → Natural
        = λ(b : Row) → λ(t : { foo : Natural | b }) -> t.foo

in  example
```

And in a language like Elm/PureScript the `b` row type parameter would be automatically instantiated for you, but in Dhall you would have to explicitly apply `example` to the type representing the remainder of the record, like this:

```haskell
example { bar : Text } { foo = +1, bar = "ABC" }
```

... which I'm guessing wouldn't be what you want because while you've made the function easier to write you've made it harder to use by deferring the work of specifying the remaining field types to each call site.

The way I would design this is to instead make it easier to project out a subset of fields from a record, using something like this syntax:

```haskell
someRecord.{ foo, bar }
```

Making an analogy to Nix, that would be like:

```nix
{ inherit (someRecord) foo bar; }
```

See https://github.com/dhall-lang/dhall-lang/issues/74#issuecomment-359087171 for more discussion about how this dovetails with other potential extensions to the language.

If you had the ability to project out fields then instead of writing a function like:

```haskell
λ(t : { foo : Natural, bar : Natural, … }) -> t.foo + t.bar
```

... you would just omit the `…` and specify an exact set of required fields:

```haskell
λ(t : { foo : Natural, bar : Natural }) -> t.foo + t.bar
```

... and if some record had a superset of those fields you would project out the subset you needed before passing them into that function, like this:

```haskell
    let example = λ(t : { foo : Natural, bar : Natural }) -> t.foo + t.bar

in. let someRecord = { foo = +2, bar = +3, baz = "ABC" }

in. example someRecord.{ foo, bar }
```

Would that alternative proposal satisfy your use case?

**Comment by sellout** [comment]
> I've always had an unstated "no subtyping" rule when designing Dhall.

Yeah – that almost prevented me from asking the question in the first place 😄

I think the subset projection would work well for what I want.

**Comment by Gabriel439** [comment]
Yeah, don't be afraid to ask :)

The worst that happens is that I'll try to propose another solution to the original requirement

**Comment by FintanH** [comment]
The proposition sounds great, I'd also appreciate this 👍

**Comment by Profpatsch** [comment]
Having open record types almost always makes code more brittle (from my experience with a lot of code in nixpkgs. Inheriting/Projecting fields is the more explicit way and makes definitions a lot more local, e.g. I used that a lot here, to great effect: https://gist.github.com/Profpatsch/7c555b181552ce7fb259faa6cf435351#file-simple-types-nix-L81

**Comment by Gabriel439** [comment]
The proposal for subset projection is up here: https://github.com/dhall-lang/dhall-lang/pull/126
