### ISSUE TITLE
Support for Blob types?

### ISSUE THREAD

**Issue by ProofOfKeags** [dhall-lang/dhall-lang#1179]
Perhaps I'm misunderstanding or misusing this language but I would like to be able to consume a value directly into a Haskell Bytestring. My first idea was to build a decoder that consumed a text value limited to an even number of characters, but I figured since that wasn't already in the library (given it seems like it would be common), I'm guessing that there was a reason to not do this. What is the appropriate way to use non-utf8 values in a dhall config?

**Comment by mmhat** [comment]
AFAIK there is none at the moment.
You might be interested in the discussion of #1092.
#1121 is somehow related as well.

**Comment by Gabriel439** [comment]
Let's all this type of value `Bytes`.  I think the main thing that would help move this forward is deciding on the syntax for `Bytes` literals.

**Comment by ProofOfKeags** [comment]
My first suggestion would be to use hexadecimal encodings since they are byte aligned and are the required utf8 encoding needed to be in dhall configs.

\xDEADBEEF

or something like that. Is it doable in the syntax tree or are there going to be conflicts?

**Comment by ProofOfKeags** [comment]
I think the quoted version seems good. From my non-PL-designer POV, I don't have a strong preference for any particular implementation as long as it isn't overly burdensome. And as we all know, it can be quite easy to bikeshed over trivial stuff. If there's no obvious reason not to go with quotations I think we should just do that and call it a day.

**Comment by IamfromSpace** [comment]
I also have a few interesting use cases to throw out there for a `Bytes` type, where files can be imported as such.

One case is for generating powerpoint files (I'm using Dhall basically anywhere and everywhere I can these days!), which is just a zip of a bunch of XML, for the most part.  Using `dhall to-directory-tree` is awesome here, as it does all the things I would otherwise have to do manually here.  The only thing left at this point is to copy resources like images and fonts into the directory before zipping.  It would be especially cool if I could just import the images in dhall and plop them right into the director tree output so they were scooped up automatically.  That would also mean some references could be made explicit, rather than implicit.

Another case would be for something like CloudFormation for AWS Lambda.  A zip file of the code is essentially the deployable unit.  In some configurations, it's helpful to have a SHA256 of the zip in the CF itself.  If the zip could be imported as bytes and then sha256 was a function from and to `Bytes` that could be rendered out to `Text` that would again eliminate otherwise custom build steps in some cases.

Hope these use-cases are helpful!
