### ISSUE TITLE
Can't use `Type` as the output type for Prelude.List.map

### ISSUE THREAD

**Issue by giuscri** [dhall-lang/dhall-lang#1199]
```
...
let Prelude =
      https://prelude.dhall-lang.org/package.dhall

let namespaces = ["worms", "buyer-area"]
in Prelude.List.map
    Text
    Type
    (λ(n : Text) → { job = n, groups = "hello-world" })
    namespaces
```

```
cat main.dhall| dhall-to-yaml


Error: Wrong type of function argument

- Type
+ Kind

30│    Prelude.List.map
31│     Text
32│     Type

(input):30:4
```

**Comment by MonoidMusician** [comment]
You are returning arguments of type `{ job : Text, groups : Text }` from the function, so you want that type to be the second argument to `map`, you don't want to pass `Type` there.

**Comment by giuscri** [comment]
That was just an example: what if the record is much more complex and I
don’t need to describe the whole schema?

**Comment by f-f** [comment]
> what if the record is much more complex and I don’t need to describe the whole schema?

Dhall doesn't currently do type inference - this is why the output type is an argument to `map`, so that the typechecker can match things up.
Now, passing it `Type` as a return type doesn't work because you'd need to return something from the set of things that typecheck to `Type` (e.g. `Integer`, or `Text`, end so on), but you're instead returning it a record `{ job = .., groups = ..}`, which is part of the set of things that typecheck to the type `{ job : Text, groups : Text}`.
Does this make sense?

So if you'd need to return a complex type there you'll need to write it down, but for clarity you can specify a type synonym, for example:

```dhall
let Prelude =
      https://prelude.dhall-lang.org/package.dhall

let ReturnType = { job : Text, groups : Text }

let namespaces = ["worms", "buyer-area"]
in Prelude.List.map
    Text
    ReturnType
    (λ(n : Text) → { job = n, groups = "hello-world" })
    namespaces
```

**Comment by giuscri** [comment]
Makes sense, Thank you

**Comment by f-f** [comment]
You're welcome 🙂
