### ISSUE TITLE
Show for arbitrary enums

### ISSUE THREAD

**Issue by hllizi** [dhall-lang/dhall-lang#1204]
I am configuring a web project that is supposed to feature multiple installations for different customers, which, at the least, will each require a different apache vhost config, and I am using dhall to abstract away from the differences between the configurations. Originally, I intended to simply identify the installations using their abbreviated names as Texts, which would have been sufficient for my current purposes. But the fact that dhall does not allow comparing Texts for equality thwarted that plan, and I am now using an enum (i.e. a union with all alternatives empty).

Still, the names of the enum members are exactly the strings that I would like to use as Texts in the vhost-configuration, so it would cause a considerable amount of redundancy if I used a merge to assign them names. Hence I have been wondering whether there is any mechanism akin to Haskell's `deriving (Show)` that makes the names of the enum members available as Texts. I could not find anything of that kind and now suspect there isn't, leading to two questions:

- did I miss anything?
- are there good arguments against having this as a feature?

In case of two negative answers, I'd like to suggest this as a new feature.

And, since this is my first issue here: amazing work, thanks for all the effort you're putting into this!

**Comment by TristanCacqueray** [comment]
It does not seems like you miss anything, and I think you need to write `show` by hand. Though you can bundle such function with the union as demonstrated here: https://discourse.dhall-lang.org/t/sum-type-value-equal-predicate/185/9 .

What should this feature do with non enums, for example how to show `< F : Natural -> Natural | D : Double >` ?

**Comment by hllizi** [comment]
Thanks for the link, I'll have a look at that.
Regarding the behaviour for non-enums, I do not have any strong opinions, yet, but I doubt that it would actually be useful and suspect it would not be worth the effort. For enums, it seems to me like an innocent feature that may come in handy in cases where strings would almost be enough, but you still need to be able to distinguish between different objects.

**Comment by SiriusStarr** [comment]
> What should this feature do with non enums, for example how to show `< F : Natural -> Natural | D : Double >` ?

One answer would be to simply make it `showConstructor` rather than `show`, so you simply get `"F"` and `"D"`.

Not going to lie, I have wished for something like this many, many times while writing out all the `merge` cases by hand.  :laughing:

**Comment by Gabriel439** [comment]
I created a funding proposal for this: https://discourse.dhall-lang.org/t/expense-proposal-new-keyword-to-render-constructors/516

**Comment by darichey** [comment]
In implementing this, I had the idea to access a `showConstructor` function on a union instead of it being a bare keyword. For example:

```dhall
let Foo = < A | B | C > in Foo.showConstructor Foo.A
```

This has the benefits of
1. Only forbidding `showConstructor` as an alternative name 
2. Giving `Foo.showConstructor` a type for any union `Foo`

What do you think?

**Comment by Gabriel439** [comment]
Yeah, I like that idea!

**Comment by mmhat** [comment]
Hm, I am not sure if that approach is a good idea as it restricts interoperability with other formats. I.e. when I want to convert some external JSON/TOML/... data to Dhall in order to work with it I don't want to worry about illegal identifiers at all.
Admitted, since it is only one right now this is an edge case but if we were adding a similar constructs like
```dhall
{ foo = "hello", bar = "world"}.showFields == ["foo", "bar"]
```
then I am worried we end up in a difficult situation.
I can however see that the ability to give it a type seems intriguing...

**Comment by darichey** [comment]
> I don't want to worry about illegal identifiers at all.

Sadly, I don't think we can avoid that entirely, but, if I understand you correctly, this approach _helps_ with that desire, rather than hinders it. If `showConstructor` were a keyword, it would be illegal as an identifier in _any_ context. Under this approach, it would only be illegal as an alternative name in a union. 

----
Quick aside: I do agree that this approach is kind of inconsistent with existing built-ins. Ideally, we could instead write something like `showConstructor : ∀(U : Union) -> ∀(u: U) -> Text` (i.e., we could constrain `U` to be a union type), but I have no idea how that kind of change to the type system would look. It also wouldn't be possible for user programs to really take advantage of without being able to introspect on the constructors of `U`, and then we're going down a metaprogramming rabbit hole I don't think we want to right now.

**Comment by mainrs** [comment]
> Quick aside: I do agree that this approach is kind of inconsistent with existing built-ins. Ideally, we could instead write something like showConstructor : ∀(U : Union) -> ∀(u: U) -> Text [...]

I am not really familiar with the internals of how dhall's type system works. But from a newcomer's point of view I like the above approach more. It behaves the same as other builtin functions like `toMap` for example. Rather than being called on some type it's a standalone function.

> It also wouldn't be possible for user programs to really take advantage of [...]

Wouldn't this type of extension to the type system allow users to write functions that only operate on a specific variant of an `enum` instead of the whole thing? Maybe that's already possible and I simply do not know about it.

**Comment by Gabriel439** [comment]
It is definitely possible to make a standalone `showConstructor` function work.  The way you standardize it is similar to how we standardized `toMap`: you have the grammar enforce that the `showConstructor` function is saturated with one argument, and then the type-checker verifies that the argument is a statically-known union literal (i.e. not an abstract type)

**Comment by MonoidMusician** [comment]
Personally I would prefer having it as a function-like keyword for two reasons: (1) I think the dot operator is already overloaded enough, and (2) there’s plenty of precedence for function-like keywords, which means it’s easier for implementations to add them, as opposed to having to create the infrastructure around disallowing keywords specifically for union (and potentially record) labels.

Also note that there are ways to quote both union/record labels (using backticks) and variable names (`reserved@0`) that allow you to still use those names. At least I’m pretty sure, but I don’t have time to double check that right now.

Regarding the types: how Dhall works now is that it requires the argument to be statically known, so it doesn’t have to give a type to the full polymorphic function, only the specific instantiations once it knows what union type it is actually operating on, etc. How this works in practice is that in the syntax, those keywords are required to take enough arguments to make this happen, and then during typechecking, the argument is required to normalize to the right sort of thing.

I am doing some work to add row types to Dhall so (in theory) everything can be given a type, but I don’t have many details to share yet.

**Comment by darichey** [comment]
I've already implemented the function-like keyword approach, so I'll open a PR and let it play out there :)
