### ISSUE TITLE
Add arithmetic operations for Natural and Integer

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-lang#1213]
I think `dhall` could benefit from adding some arithmetic operations on `Natural`:

- division with remainder:  `Natural.div 5 3 === Some 1`, `Natural.rem 5 3 === Some 2`, `Natural.div 1 0 === None Natural` (returns `None` when trying to divide by zero)
- the bit length of a natural number: `Natural.bitLength 8 === 4`, `Natural.bitLength 7 === 3`, `Natural.bitLength 0 === 0`
- greatest common divisor: `Natural.gcd 9 6 === 3`, `Natural.gcd 1 0 === 0`
- integer power: `Natural.pow 2 5 === 32`, `Natural.pow 10 0 === 1`
- integer square root: `Natural.sqrt 9 === 3`, `Natural.sqrt 10 === 3`

These operations can be implemented more easily using `foldWhile`:

```haskell
let foldWhile: ∀(n: Natural) → ∀(res : Type) → ∀(succ : res → Optional res) → ∀(zero : res) → res =
    λ(n: Natural) → λ(R: Type) → λ(succ: R → Optional R) → λ(zero: R) →
    let Acc: Type = { current: R, done: Bool }
    let update: Acc → Acc = λ(acc: Acc) →
       if acc.done then acc
       else merge { Some = λ(r: R) → acc // {current = r}, None = acc // {done = True} } (succ acc.current)
    let init: Acc = { current = zero, done = False }
    let result: Acc = Natural/fold n Acc update init
    in
    result.current
```

I propose to add these operations as built-ins. These operations can be implemented in plain `dhall` via `Natural/fold`, although inefficiently since there is no way to stop iterating when the result is already obtained.

Example code is here: [https://github.com/winitzki/scala-examples/blob/master/chapter11/src/test/scala/example/naturals.dhall](https://github.com/winitzki/scala-examples/blob/master/chapter11/src/test/scala/example/naturals.dhall)

Similar code for `foldWhile` can be added to `List`.

What do you think?

**Comment by denizdogan** [comment]
I think these are good additions to the language.

Personally, I could definitely live without e.g. `Natural.bitLength` in Prelude, as it's not obvious to me under what circumstances that would possibly be useful from a Dhall perspective, but I'm sure someone could explain that to me. :) It should be noted that many general-purpose programming language standard libraries lack this functionality as well, perhaps exactly because it's so rarely useful?

The one thing that stands out to me is that it's important to keep consistency throughout the Prelude functions. For example, I think that `Natural.div` returning `Optional Natural` when dividing by zero is not entirely obvious for Dhall, but it _would_ be obvious for e.g. Elm. It's, in some sense, similar to the idea of having `NonEmpty.fromList`, which should "fail" for empty list inputs. They're both operations that are invalid for the "bottom value" (terminology?) of each type, so I would expect them to fail in the same way.

@Gabriel439 suggested that using an `assert`-based approach to a potential `NonEmpty.fromList` function: https://github.com/dhall-lang/dhall-lang/issues/1205#issuecomment-901380421 -- if that happens, I'd suggest using the same approach to `Natural.div`, and vice versa.

**Comment by winitzki** [comment]
`bitLength` is used to estimate the number of iterations required for a `fold` to achieve convergence for certain algorithms. In a language like `dhall`, all functions are required to terminate and all iterations are required to have an explicit number of iterations known in advance. When we compute GCD(x,y) by Euclid's algorithm, the number of iterations is bounded by the bit length of the largest of x, y. The integer square root is useful for similar reasons. In most programming languages, termination is not assured and so it is not necessary to estimate the required number of iterations in advance.

**Comment by winitzki** [comment]
A validation-based approach will look like this, as far as I understand:

```haskell
let x: Natural = ...
let validate_x = assert : Prelude.Natural.isZero x === False
let y: Natural = div 10 x
```

where `div` is a division function that never fails because it gives a fixed result (e.g., `0`) when trying to divide by zero.

As far as I understood from Gabriel's comment, it is incorrect to put the `assert` inside the `div` function itself. The `assert` must be applied directly to the arguments of `div` before we evaluate `div`.

**Comment by winitzki** [comment]
I think we would like to keep the number of built-in functions to a minimum. However, `foldWhile` and `div` with `rem` seem to be important. Other numerical functions can be implemented efficiently once we have `foldWhile` that actually stops when convergence is reached, and `div` , `rem` that are much faster than linear time.

**Comment by infogulch** [comment]
> It's, in some sense, similar to the idea of having NonEmpty.fromList, which should "fail" for empty list inputs. They're both operations that are invalid for the "bottom value" (terminology?) of each type, so I would expect them to fail in the same way.

Your observation that both natural number zero and empty list are like the 'bottom value' is reasonable, though I would prefer 'zero value'. Also that for both Natural.div and NonEmpty.fromList the zero value is not present in the domain of each function respectively. But I think you're extrapolating too far when you imply that the reason why a value might be missing from a function's domain is because it's *the zero value specifically*. (Though I suspect you did not intend to imply this.) Consider the function `λ(y: Natural) -> λ(x: Natural) -> Natural/div y (Natural/subtract 2 x)`, here the domain for x also omits the elements 1 and 2 because subtract saturates negatives to zero. Or a hypothetical Pairs.fromList that is only valid on a list with an even number of items.

My point is that the generalized way to consider functions that have some kind of 'invalid' input is to state that the invalid inputs are not part of the function's domain, and the fact that both of these functions have an invalid input that happens to be the zero value for that type, while true, is just incidental. **In other words, the need to solve the problem of dealing with functions that have a domain smaller than their naive input type is broader than these cases.**

Perhaps unsurprisingly, I think it's helpful to use the notion of a function's 'domain' (valid inputs) and 'range' (possible outputs) to describe this problem. The domain of div's divisor doesn't include zero, but the domain we would like to use, `Natural`, does include zero. There are two ways to reconcile these seemingly irreconcilable facts within our type system:

1. We can invent a new type, say `PositiveNatural`, that omits zero and is therefore always valid to use as a divisor. Here the type of div would be `Natural → PositiveNatural → Natural`. Great. (Maybe this could also be implemented by div taking a proof that the divisor is nonzero ("validate_x" above) as an argument?) ... But it would be really convenient to not have to invent a new named type (and special constructor for instances) or other complex pre-validations just to represent the divisor which is *this close* to being the correct domain, which leads into option 2:
2. Project any "extra" elements that aren't in the true domain of the function but are in the domain we wish to use out into to the range. Basically we extend the 'true' definition of div to include the zero element by also extending div's range with a special case so that the 'hole' is covered allowing us to use the more convenient domain (`Natural`) in exchange for having to deal with an extra element in the range. Here the type would be `Natural → Natural → Option Natural` as described by winitzki in the OP.

These two strategies have different consequences on the surrounding code. 1 means that the caller has to prove that the divisor is nonzero to construct a `PositiveNatural` but knows for sure that it will work if they get their hands on one. 2 means that the caller is less burdened up front because they only need to provide a regular `Natural`, but then they have to deal with the aftermath of the None case of the option if the divisor turned out to be zero. There are other pros and cons as well, but it's definitely more 'tradeoff' than 'right/wrong'. I don't know what the best answer for dhall is.

I hope this is more helpful than confusing. :)

**Comment by winitzki** [comment]
Here is an implementation of “safe division” `divide x y _` where the  third argument must be of type `Unit` and represents a proof that the second argument is nonzero. (This works only when `y` is a `Natural` constant.)
[dependent_types.dhall](https://github.com/winitzki/scala-examples/blob/master/chapter11/src/test/scala/example/dependent_types.dhall#L26-L27)
Question: is this too complicated? Is there a different, easier way to assert that an argument is nonzero? I was not able to simplify the function so that we can just say `divide x y` and have this fail to typecheck when `y` is zero.

**Comment by Gabriel439** [comment]
@winitzki: If possible, I'd like to see if we can directly add the downstream utilities that `foldWhile` is used to implement

**Comment by winitzki** [comment]
I think it would be useful to implement at least `divmod` and `gcd` in some way. I won't have time to contribute the code myself though, I'm not very familiar with Haskell and don't know much about the dhall codebase.

**Comment by Gabriel439** [comment]
I think my recommendation would be to standardize `Natural/lcm` (since it forms a `Monoid`), and `Natural/divideBy` since `gcd` can be implemented in terms of `lcm` and `divideBy` and `mod` can be implemented in terms of `divideBy` and `subtract`

**Comment by IamfromSpace** [comment]
I have a use case I'd like to bring up for something like `divideIntoDouble` (or some better name than that, haha), which would divide naturals and give back a double.  For audio/video, frames, timing, and sampling simply come in pretty awkward harmonics.  However, being able to describe cuts/text/subtitles/effects via configuration is often very helpful.  The gifcurry library is a good example like this, which uses seconds to specify timings.

When specifying time, arguably frames or audio samples are better than a double of seconds, but there's really no perfect option.  Video comes in a pretty odd variety of frame rates, most notably strange are 29.97hz and 23.96hz.  Audio sampling is commonly 48khz or 96khz.  Using a Natural to encompass the combo, let alone a natural that is the harmonic of all possible combos is pretty impractical.  Not to mention, often thinking in frames or samples isn't exactly natural (if you'll excuse the pun!).  There's a decent argument that Double is the right choice for this kind of work--given the lack an ideal answer.

Some sort of math around these is helpful or occasionally necessary (e.g., add gap of two frames for subtitles), but if the target output uses seconds, this is currently impractical.  While I think excluding Double arithmetic does makes some sense, I think it could make sense as a final "dead-end" step, and would work for these use cases.  So, with a 29.97 frame rate, rather than something like `Double/add 0.0667334 t`, a user could do `Natural/divideIntoDouble (Natural/add 200 t) 2997` to get the final time is seconds.  This gives exactly one clear moment of imprecision, but is terminal from there.

Just wanted to get this use case out there and curious to get thoughts on it.

**Comment by Gabriella439** [comment]
If we were to add a division operation for `Double` I'm guessing the most likely type that would work is:

```haskell
Double/divide : Double -> Double -> Optional Double
```

In other words, we don't need to restrict the denominator to `Natural` specifically, since the main pathological case is division by 0, which is an issue both for `Natural` and `Double` division

**Comment by IamfromSpace** [comment]
That would certainly work for this case.  Is `Double/divide` under consideration?  I may have misunderstood, but I thought Double arithmetic had been ruled out—was divide by zero the only factor?

**Comment by Gabriella439** [comment]
I'm probably the main person that has been arguing against `Double` arithmetic, although thinking about it more I think my main objection is providing operator support for it, since I usually reserve operators for operations that are associative.  I think I would object less to `Double` arithmetic operations if they were named builtins

**Comment by winitzki** [comment]
I thought the main issue with `Double` was portability. Different software systems define floating-point arithmetic differently. Floating-point arithmetic violates associativity:

[As Tikhon Jelvis said:](https://www.quora.com/Can-we-prove-that-floating-point-addition-is-not-associative)
> Floating point addition is not associative. This is actually surprisingly easy to demonstrate:
> 
>     Prelude> let r₁ = (0.1 + 0.2) + 0.3; r₂ = 0.1 + (0.2 + 0.3) 
>     Prelude> r₁ 
>     0.6000000000000001 
>     Prelude> r₂ 
>     0.6 
>     Prelude> r₁ - r₂ 
>     1.1102230246251565e-16

The precise violation will depend on the system and the hardware. You cannot define floating-point operations that are associative, and I don't think Dhall needs to adopt a particular associativity-violating definition of floating-point arithmetic.

Working with floating-point numbers such as `0.3` and `0.41` is deceptively convenient. I don't think it's really any better than working with exact fractions such as `3/10` and `41/100`. It is easy to define a `Fraction` type in Dhall if this is needed for an application.

**Comment by IamfromSpace** [comment]
> I don't think it's really any better than working with exact fractions such as 3/10 and 41/100. It is easy to define a Fraction type in Dhall if this is needed for an application.

Ultimately, this is why I first presented the desire for something like `Natural/divideToDouble`, because I don't strictly need `Double` arithmetic for my use case (frames or samples to seconds), but I do need to make an imprecise decimal value in order to output valid JSON or YAML.

> Different software systems define floating-point arithmetic differently.
Well I knew floating point was full of gotchas and not associative, but TIL that [even the IEEE spec isn't portable](https://www.ccs.neu.edu/~jaideep/nsv12-paper.pdf).  From this paper it appears that associativity (seems like your hardware may rearrange ordering even if your compiler doesn't?) and intermediate precision are the primary considerations.  I believe that something like `Natural/divideToDouble` would still be portable.

**Comment by winitzki** [comment]
> but I do need to make an imprecise decimal value in order to output valid JSON or YAML

If you just multiplied all your decimal values by 1,000,000 and converted the results to integers, would that be sufficient for your application?

**Comment by IamfromSpace** [comment]
If it were my application, maybe :)  But I don't get to decide the schema of the config.  If there's another trick to this, then I'd be curious.

The "maybe" comes in that because the lowest common denominator (or harmonic) for audio video is often something quite ugly like 47952000hz or 28752000hz--before you even consider the prospect of mixing frame rates or samples.  This is why one is tempted to use things like seconds with a Double, because with a lot of precision you can support everything all together and probably be just fine.  So in a very strict sense, Naturals are the most correct way to model things.  Pragmatically, it's a _lot_ of work in this use case, where a Double probably does the trick.

**Comment by IamfromSpace** [comment]
Another use-case for `Natural` and `Integer` division is vector graphics, such as SVG.  I mentioned in another issue that I've been using Dhall to generate powerpoint presentations (I've been using it everywhere I can!), and not having the ability to divide `Naturals` and `Integers` means that there are certain layout functions for images and shapes that I just can't implement in Dhall alone.  Currently, I have an external spreadsheet helper that does the calculation and then I plug it back in, which seems rather silly given how much else I can accomplish!

Powerpoint uses english metric units (EMUs) which are 1/914400 of an inch (nicely divisible by 254, 300, and 72 for metric and common DPI interop) so this use case doesn't need to have division into `Double`.

**Comment by kukimik** [comment]
>> @Gabriel439 Do you think `foldWhile` is not worth adding as a built-in (for `Natural` and `List`)?
>
> @winitzki If possible, I'd like to see if we can directly add the downstream utilities that `foldWhile` is used to implement

While I am not against standardizing `Natural/lcm` and `Natural/divideBy`, I think a `Natural/foldWhile` builtin could also be a useful utility:

* as shown by @winitzki, it can be used to implement a variety of arithmetic operations;
* even with `Natural/divideBy` in place, it would still be desirable to have an efficient `foldWhile`  to implement a `showHex` function (see #1351).

I am pretty sure there are many similar usecases.

@Gabriella439 I have the impression that you are not enthusiastic about `Natural/foldWhile` (although this was never directly stated, so I may be wrong). Can you share your thoughts about it?

**Comment by winitzki** [comment]
The only argument for adding `foldWhile` as a builtin is the possibility of early termination. If `foldWhile` is applied to literals then the implementation could detect when the loop is finished early. But maybe one could somehow make the Dhall evaluation strategy more sophisticated and detect the early termination automatically. Then `foldWhile` could be just implemented in user code and evaluation will not be inefficient.

I am not sure if it is feasible, but can it be implemented that Dhall automatically detects when a function no longer depends on one of its arguments? More precisely, suppose `f : A -> B -> C` where `A` is a non-function type. Can we somehow detect (automatically, in the Dhall interpreter) that when `f` is applied to a particular literal value `a : A` then `f a b` can be evaluated without evaluating `b`? An example of such a function is:

```dhall
λ(x : Natural) → λ(y : Natural) → if Natural/isZero x then 0 else y
```

**Comment by Gabriella439** [comment]
So the language standard explicitly permits implementations to use whatever evaluation strategy they want (as long as the final result is the same), so you could have any given interpreter implement that sort of behavior-preserving optimization.

**Comment by winitzki** [comment]
As time permits, I will try to implement that and see if it's even feasible.

**Comment by Gabriella439** [comment]
The language standard doesn't require that you implement judgments exactly as they're written.  You can translate them to different code as long as the final result is the same.

**Comment by winitzki** [comment]
I am implementing an experimental change in the beta-normalization where `Natural/fold` is implemented via a tail-recursive loop of this sort:

```
betaNormalize (Natural/fold n B g b)  =  loop b 0 where
    loop x c = 
       if  (c >= n || x' == x) then x else loop x' (c + 1)
             where    x' = betaNormalize (g x)
```

While evaluating `loop x c` the invariant is: `x == g(g(... g(b)...))` where `g` is applied `c` times. 

This shortcuts the loop when the result no longer changes. This allows us to calculate more efficiently when the loop reaches a fixpoint of `g` and there is no need to keep calculating. 

This change appears to be completely safe and allows to reduce things like

```dhall
λ(y : Natural) → Natural/fold 10000000000000000000000000000 Natural (λ(x : Natural) → x) y
```

This reduces to `λ(y : Natural) → y` in O(1) time.

After this change, it is no longer necessary to implement `Natural/foldWhile` as a built-in. An early termination of the loop is detected automatically while reducing `Natural/fold`.

Another experimental change is to avoid beta-reducing `Natural/fold` under a lambda, in case the expression grows in size after beta-reduction. In other words, we compute `g x` and compare the size of the expression trees for `x` and for `betaNormalize(g x)`. If `betaNormalize(g x)` is larger than `x` (and, say, the size of `x` is at least 5 subexpressions), we stop the beta-reduction and return the intermediate result.

This allows me to avoid expression blow-up under lambdas where it is most likely useless to beta-normalize `Natural/fold`:

```dhall
\(y: Natural) -> Natural/fold 10000000000000000000000000000 Natural (\(x: Natural) -> x + 1) y
```

The usual beta-normalization will generate a huge expression of the form `y + 1 + 1 + 1 + 1 ...` although this is most likely useless.

With the experimental change I'm describing, the result will be the following "normal form":

```dhall
λ(y : Natural) → Natural/fold 9999999999999999999999999996 Natural (λ(x : Natural) → x + 1) (y + 1 + 1 + 1 + 1)
```

This change is perhaps problematic because it changes the meaning of beta-normalization for lambdas. Perhaps it is reasonable to limit this change to just `Natural/fold`, which alone has a capacity for generating huge expressions out of nothing, as already shown in this issue about "List/drop" https://github.com/dhall-lang/dhall-lang/issues/1286 

`List/fold` cannot do as much damage because (I think) one would have to start with a huge list in order to generate a huge normal form. But `Natural/fold` allows us to implement a denial-of-service attack.

After the no-beta-under-lambda change, the example with "List/drop" no longer generates huge expressions.

Another version of this change is to stop looping in `Natural/fold` if some of the arguments have free variables. We can still beta-normalize the arguments, but that's it. Again this would be a breaking change. The result of beta-normalizing 

```dhall
\(y: Natural) -> Natural/fold 10000000000000000000000000000 Natural (\(x: Natural) -> x + 1) y
```

will be again the same expression because of the free variable `y` under `Natural/fold`.

**Comment by Gabriella439** [comment]
I'm definitely in favor of the change to short-circuit if the accumulator doesn't change although technically that doesn't require any change to the standard (since the standard already permits alternative evaluation strategies if they produce the same result as the standardized behavior).

I'm not too worried about blow-up of symbolic expression and in some cases it can be a feature to symbolically evaluate expressions.  For example, one of my "go to" examples to showcase Dhall is that `List/generate` can be used like this:

```
$ dhall repl
⊢ :let generate = https://prelude.dhall-lang.org/List/generate.dhall

generate : ∀(n : Natural) → ∀(a : Type) → ∀(f : Natural → a) → List a

⊢ generate 10

λ(a : Type) →
λ(f : Natural → a) →
  [ f 0, f 1, f 2, f 3, f 4, f 5, f 6, f 7, f 8, f 9 ]
```

… and I believe that would no longer work if we disallow free variables before interpreting `{Natural,List}/fold`.

**Comment by winitzki** [comment]
PRs were merged, implementing a short-circuiting optimization for `Natural/fold`. This removes any need for `foldWhile` and enables much faster implementations of natural division.

I'm no longer inclined to pursue adding division as a built-in.  There are lots of functions that one would be tempted to add to Dhall built-ins just for efficiency. But instead of that, a Dhall implementation could just provide optimized code for certain functions. I was thinking about the following mechanism: Suppose we implement division for natural numbers. The normal form of that function will have a certain hash value. Then we declare (in a Dhall implementation) that during beta-reductions, all terms with that hash value should be replaced by some optimized code in the host language (when all arguments are literals). A Dhall implementation could provide a "standard library" that maps a number of hash values to optimized code routines. This removes pressure from Dhall to implement things like `List/sort` efficiently.

**Comment by Gabriella439** [comment]
I feel like if you want to do something efficiently it's still worth standardizing.  Even if you use the hash trick to map slower functions to more efficient implementations it will decrease portability if only one implementation does that optimization.  So, given that other implementations would need to support the optimization anyway it's usually better to just bite the bullet and standardize it as a builtin.

**Comment by winitzki** [comment]
My motivation was that we could provide an optimized implementation only for functions that are already implemented in pure Dhall; we do not just add arbitrary new primitives that are only available in a specific Dhall implementation.

In this way, we avoid having non-portable Dhall code. For example, `List/sort` is inefficient but it will still work correctly in all implementations. In some implementations, `List/sort` is replaced by a native function and it will work faster, but that's a nice-to-have. Not everyone has the same needs, and probably most Dhall users will not need to sort large lists of natural numbers quickly. Currently, it is not very quick and easy to standardize a new built-in. 

I am also thinking about user-provided routines. For example, on JVM one can dynamically load code at runtime from JAR files. Then a user may provide a JAR file with additional optimized routines. But all those routines must be first implemented in pure Dhall and their hash values must be known.

**Comment by winitzki** [comment]
Using some tricks related to "hylomorphisms", I was able to implement very fast integer division via the "Egyptian division" algorithm. The newly implemented short-circuit functionality of `Natural/fold` is quite sufficient.

**Comment by winitzki** [comment]
I simplified the division code to get rid of hylomorphisms. The code has become significantly faster and divides `100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000` by `3` in no time (that is, in the same time as it takes to parse the input files). The hylomorphism-based code took a few seconds for that.

```dhall

let Natural/lessThan = https://prelude.dhall-lang.org/Natural/lessThan

let powersOf2Until
    : Natural → Natural → List Natural
    = λ(a : Natural) →
      λ(b : Natural) →
        let TableT = { result : List Natural, power2 : Natural }

        let succ =
              λ(prev : TableT) →
                if    Natural/lessThan a (prev.power2 * b * 2)
                then  prev
                else  let newPower2 = prev.power2 * 2

                      in  { result = prev.result # [ newPower2 ]
                          , power2 = newPower2
                          }

        in  (Natural/fold a TableT succ { result = [ 1 ], power2 = 1 }).result

let egyptian_div_mod
    : Natural → Natural → Result
    = λ(a : Natural) →
      λ(b : Natural) →
        let powers2 = powersOf2Until a b

        let update
            : Natural → Result → Result
            = λ(power2 : Natural) →
              λ(prev : Result) →
                if    Natural/lessThan prev.rem (power2 * b)
                then  prev
                else  { div = prev.div + power2
                      , rem = Natural/subtract (power2 * b) prev.rem
                      }

        in  List/fold Natural powers2 Result update { div = 0, rem = a }
```
