### ISSUE TITLE
The prelude.dhall-lang.org certificate has expired

### ISSUE THREAD

**Issue by LightAndLight** [dhall-lang/dhall-lang#1223]
You're probably aware, but I figured I'd make a note just in case.

Is there a way to force Dhall to use http for the time being?

**Comment by Gabriel439** [comment]
It should be fixed now for all of the dhall-lang.org subdomains

I just want to document what I did here, which was:

```bash
$ ssh dhall-lang.org
$ sudo systemctl restart nginx
```

Apparently the certificates were getting automatically renewed, but for some reason `nginx` was not picking up the updated certificates without the restart.  I'm not exactly sure why this only happened recently.  I thought that perhaps this was due to the fact that there were no recent changes to dhall-lang.org that might trigger a redeploy, but there actually were several in the last few weeks.

To answer the question: there isn't currently a way for the Haskell implementation of Dhall to ignore certificates.

**Comment by LightAndLight** [comment]
Thanks, no worries. I managed to work around it.
