### ISSUE TITLE
Normalize with effects

### ISSUE THREAD

**Issue by alexbiehl** [dhall-lang/dhall-lang#133]
I am evaluating Dhall to describe inputs to a solver. These inputs are basically records which fields can be populated by a variety of API calls (= IO). Although Dhall allows custom 'Normalizer's these are meant to be pure. 

Having the flexibility + strong normalization of Dhall is exactly what I need for my users to describe their problems. Do you have any suggestion on how I might approach this?

My naive thinking tells me I want something like the following:

```haskell
type Normalizer m a = forall s. Expr s a -> m (Maybe (Expr s a))

normalizeM :: (Eq a, Monad m) => Expr s a -> m (Expr s a)

normalize expr = 
  runIdentity (normalizeM (\_ -> pure Nothing) expr)
```

Is that something you would consider accepting a PR for? Would be happy to cook one up.

**Comment by ocharles** [comment]
I've wanted a normalizeM type function in the past, too.

**Comment by Gabriel439** [comment]
The "right" way to do this depends on your use case, but my intuition is that interleaving effects with normalization is usually not what you want to do.  The two main reasons are:

* Neither the Dhall standard nor implementation guarantee how many times expressions are evaluated, whether or not they are evaluated at all, or in what order they are evaluated
* Interleaving side effects with pure evaluation is inconsistent with "denotational programming" which is the programming paradigm that Dhall is inspired by

For your specific use case, the approach I would suggest is using the API support for customizing import resolution step (i.e. `loadWith` and friends) so that you can reuse Dhall's import system for importing values from your API.  Dhall already supports importing Dhall expressions from URLs but if you need to support an input format other than Dhall expressions you could extend the Dhall API to support that.  For example, you might want to add a way to implement something like `http://example.com/api/someEndpoint as YourDesiredFormat`

**Comment by alexbiehl** [comment]
I somewhat expected that answer. Problem is that the resolution logic doesn`t look at whole expressions: 

```
{
  input = ./some-api-call param1 param2 ... paramN
}
```

At resolving time I only get to see the './some-api-call' part and not it`s parameters. I thought about this:

```
newtype Lang = Lang (Dhall.Expr Dhall.Src (Api Lang))
```

But then I lose import resolution by path. Any thought on this?

**Comment by Gabriel439** [comment]
So, thinking about this more, I think what you originally proposed is the only way to do this correctly because you would need to interleave importing the value with normalization.  So I changed my mind and I'll accept a pull request to generalize `normalizeWith` to a monadic version

**Comment by Gabriel439** [comment]
Also, this issue probably belongs in https://github.com/dhall-lang/dhall-haskell since it's specific to the Haskell API rather than the language standard

**Comment by f-f** [comment]
@Gabriel439 should we close this as https://github.com/dhall-lang/dhall-haskell/pull/371 has been closed?

**Comment by Gabriel439** [comment]
Yes.  Thanks for reminding me
