### ISSUE TITLE
Variable record keys

### ISSUE THREAD

**Issue by blast-hardcheese** [dhall-lang/dhall-lang#135]
In attempting to produce desired JSON output with maximal code reuse I came across the following problem:

```
let server1 = { id = 1, name = "foo" } in
let server5 = { id = 5, name = "bar" } in
{
  ${server1.name} = server1,
  ${server5.name} = server5
}
```

This is necessary to avoid duplication, as the same `name` will need to be string interpolated into JSON-pointer-style paths (`#/servers/${server1.name}/foo`) in the target runtime (Terraform).

Reading through the parser, it doesn't seem as though this is currently a supported feature. Do you have any suggestions on where to start if I were to add this feature?

**Comment by Gabriel439** [comment]
So I don't think this will happen in the short term, but I think there is a viable plan for this in the long run, which I'll outline.

The first step would be to turn on dependent types in Dhall because records with computed field names are one form of dependent types.  This is technically very straightforward to do and only requires changing the [function check](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#function-check) in the standard semantics to add the following judgment to permit dependent types:

```
───────────
Type ↝ Kind
```

That is safe and preserves soundness and the matching change to the Haskell implementation is a one line change here:

https://github.com/dhall-lang/dhall-haskell/blob/3fb4d0e758c60e667270f67f7b22752cb600b1bf/src/Dhall/TypeCheck.hs#L66

The main reason that I haven't enabled dependent types so far is because this requires other matching changes to the language to provide more comprehensive support for them.  Specifically, I expect that once we introduce dependent types that users will request:

* a much more robust judgmental equality check (i.e. something more sophisticated than the current αβ-equivalence)
* language support for something like `Refl`
    * you can technically encode `Refl` in the language once you enable dependent types but the ergonomics are poor

The third step is then to extend the standard to support computed record fields, which would expect to be pretty straightforward.  However, I would prefer to delay this until after the first complete draft of the standard is complete and there is at least one independent reimplementation of the language before expanding the standard, mainly as a sanity check on the growing complexity of the standard.

This is something that I think is useful to include because Dhall's first target use case is ops, including Terraform, so I would like to support that as comprehensively as possible.  It just might take some time to get to that point because right now the bottleneck is completing the standard and getting one parallel and well-supported implementation going.

**Comment by Gabriel439** [comment]
So, thinking about this more in the context of #136, what I think might work better for this is a Terraform-specific Dhall integration (i.e. `dhall-to-terraform`) where on the Dhall side you use an association list as the encoding but then `dhall-to-terraform` knows to translates that to the equivalent JSON record that Terraform expects

**Comment by Gabriel439** [comment]
I believe this is now fixed at the `dhall-to-json` level through its support for converting association lists to JSON homogeneous maps.  For example, the Dhall code for this would be:

```haskell
let Prelude = https://prelude.dhall-lang.org/package.dhall

let server1 = { id = 1, name = "foo" }

let server5 = { id = 5, name = "bar" }

let kv = Prelude.JSON.keyValue { id : Natural, name : Text }

in  [ kv server1.name server1, kv server5.name server5 ]
```

... which generates this JSON:

```bash
$ dhall-to-json --pretty <<< './test.dhall' 
```
```json
{
  "bar": {
    "id": 5,
    "name": "bar"
  },
  "foo": {
    "id": 1,
    "name": "foo"
  }
}
```

Note that there are still some planned improvements here by possibly adding something like a `toMap` keyword to convert homogeneous records to association lists, but that is already captured in https://github.com/dhall-lang/dhall-lang/issues/234
