### ISSUE TITLE
Creating records via folding on `List T`

### ISSUE THREAD

**Issue by blast-hardcheese** [dhall-lang/dhall-lang#137]
Somewhat related to #135, an alternate approach (permitting more generic constructions) would be something like:

```
  Record/fromList
:   ∀(a : Type)
  → List a
  → (toKey: a -> Text)
  → ∀(value : Type)
  → (toValue: a -> value)
  → ???
```

With knowledge of the runtime, this could return a concrete type. From a consumer's perspective, however, this would be cumbersome to maintain in an abstract way. For that reason, it would be useful to be able to specify the return type via #136, similar to:

```
  myFromList
:    List { id: Integer, name: Text, foo: Bar }
  → { [Text]: { id: Integer, name: Text, foo: Bar } }
```

where the definition could be
```
let t = { id: Integer, name: Text, foo: Bar } in
myFromList:
  List t -> { [Text]: Bar } =
  \(value: List t) ->
    Record/fromList value (\(x: t) -> x.name) (\(x: t) -> x.foo)
```

**Comment by Gabriel439** [comment]
As I mentioned in #136, I think the idiomatic way to support this is to encode the record as a homogeneous association list instead.  Then you could implement this in Dhall without any changes to the language as a function of this type:

```haskell
fromList
    : ∀(a : Type)
    → List a
    → ∀(toKey : a → Text)
    → ∀(value : Type)
    → ∀(toValue : a → value)
    → List { k : Text, v : value }
```

So I think all three of these requests can be satisfied by using association lists to encode this in Dhall and then the Terraform-specific integration can convert the assocation lists to JSON records.

**Comment by Gabriel439** [comment]
@aleator: What I would like to propose is that the idiomatic way to do equality in Dhall is to use a sum type and pattern match on it.  If that is not ergonomic enough for your case then I would like to add features to make them easier to use for that purpose

**Comment by aleator** [comment]
@Gabriel439 The whole thing might boil down to me not understanding how to use Dhall in this specific case. Let's take the bibliography case as an example. What this boils down to is:

`
let bib = {cook97 = {link=... , ...}, schneider10= {link = ... , ...} ..}
in let bibList = [bib.cook97, bib.scheider10, ...]
in let exercise = {readings=format bibList, description=''Considering the details in ${cite bib.cook97} ...''}
`

Now, assuming that `bib` is rather large the probability of me forgetting to add the entry to the list or otherwise mucking it up is quite high. Also, the amount of duplication is such that I've resorted to generating this list using haskell.

How about 'special' associative list type where keys are from a sum? Or perhaps allow comparison of sums with only constructors?  (I'm not having any great ideas about this right now)

**Comment by Gabriel439** [comment]
@aleator: I think this needs to be solved at the API level rather than at the language level (i.e. using the API to detect what bibliographic references were actually referenced and used to automatically include them in the bibliography).

For example, even if Dhall were to support treating records as homogeneous maps, it still wouldn't address the following two related problems for creating an accurate bibliography:

* You can cite things that are not in the `bib` record
    * For example, I could write: `"See ${cite { link = ..., ... } }"`
* You can have things in the `bib` record which are never cited
    * For example, would you want to include `schneider10` in your bibliography if you never used the citation?

Proper reference tracking requires access to the language API (which does store records internally as homogeneous maps like you would want), but I don't think the language should support exposing that sort of introspection capability to the language level.

The way I would approach this if I were you is to write an `exercise-to-bibliography` command line tool that lets you author an exercise like this:

```haskell
  λ(cite : { link : Text } → Text)
→     let bib =
            { cook97 =
                { link = "https://example.com/cook97" }
            , schneider10 =
                { link = "https://example.com/schneider10" }
            }
  
  in  "Considering the details in ${cite bib.cook97} and ${cite
                                                           bib.schneider10}"
```

... then the tool would:

*   resolve/type-check/normalize the file, producing an internal result such as this:

    ```haskell
      λ(cite : { link : Text } → Text)
    → "Considering the details in ${cite
                                    { link =
                                        "https://example.com/cook97"
                                    }} and ${cite
                                             { link =
                                                 "https://example.com/schneider10"
                                             }}"
    ```

* traverse the AST, find all occurrences of `cite` and transform the arguments into a bibliography

That would guarantee a much more accurate bibliography, because:

* It would correctly handle citations no matter where they originate from
    * It would handle citations originating outside of our `bib` record
    * It would correctly handle inline citations
* It would correctly discard items from the bibliography that didn't appear in the final result

**Comment by ocharles** [comment]
We now have the `toMap` keyword - does that help here?

**Comment by aleator** [comment]
The `toMap` works very nicely for my use case above.

**Comment by ocharles** [comment]
Great! In that case I will close this.
