### ISSUE TITLE
Disjoint record types and values

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-lang#174]
Not sure if this had been already discussed (i didnt find an issue about but sorry if it exists). Not sure neither if "disjoint record type" is the precise name for this.

Recently, in attempting [to make a funcion in dhall-to-cabal we missed](https://github.com/dhall-lang/dhall-to-cabal/pull/73#discussion_r192588272) the possibility of define a record type removing some keys from another one with many of them.

Not sure about the better syntax, but i could imagine something like:

`{a: Text, b: Text, c: Text, d: Text, ...} \\// {a,b} ~= { c: Text, d: Text, ..}`
or
`{a: Text, b: Text, c: Text, d: Text, ...} .- {a,b}`
or simply (as in the comment referenced above)
`{a: Text, b: Text, c: Text, d: Text, ...} - {a,b}`

I guess that it could be correlated with a way to do somethink similar for record values (it would be the inverse of `.`?):

`{a=1, b=2, c=3, ..} \\ { a,b} ~= { c = 3, ... }`
or
`{a=1, b=2, c=3, ..} .- { a,b}`
or again
`{a=1, b=2, c=3, ..} - { a,b}`

**Comment by Gabriel439** [comment]
So for types I think the right thing to do is to define the smaller type and extend it to become the larger type.  In other words, begin from `{ c : Text, d : Text, ... }` and then add the `{ a : Text, b : Text}` fields using `⩓`)

However, for record values I think there might be utility in support for deleting fields (See: https://github.com/dhall-lang/dhall-lang/issues/169#issuecomment-395893113 for one reason why).  However, I'd like to see more specific use cases before doing that because I want to make sure that there aren't other solutions to the same problem (like record projection).

My main advice so far is that I would probably avoid using an operator.  I generally try to reserve operators for things that are associative (the main exception to this rule is accessing fields from records using the `.` operator).  So if we do this I would either recommend a named keyword instead or figure out how to implement this in terms of some new underlying associative operator.

**Comment by quasicomputational** [comment]
I've got another use-case for this, also inspired by `dhall-to-cabal`. It would be nice to write a utility function for `cabal-doctest` integration, which requires a `custom-setup` section and a `test-suite`, so it would have to have the type `Package -> Package`. However, `custom-setup` sections don't compose: there can only be one of them in a package. If I mistakenly pass in a `Package` that already has a `custom-setup`, that will just be dropped and whatever I was using that `custom-setup` for will not work. It'd be nice to statically eliminate that possibility and for my function to have the signature `Package \\// { custom-setup } -> Package` (in the syntax of the OP). The core issue here is that this is user code trying to talk about a subrecord of a type from a library, so there is not necessarily the option of writing with `//\\`, since most of the code is out of your hands.

I've got another idea that might help with this: being able to project the fields that this other record (record type?) has; or, put another way, field intersection. For example, `let A = {a = 1, b = 2} in let B = {a = 3} in A.{fields B}` would result in `{a = 1}`. This would also be useful for `dhall-to-cabal`, which has several records that have `BuildInfo` as a subrecord, and it would be useful to write `mapPackageBuildInfo : (BuildInfo -> BuildInfo) -> Package -> Package`, but currently that requires manually projecting [all 30-odd fields of `BuildInfo`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/BuildInfo.dhall) from each of [`Benchmark`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/Benchmark.dhall), [`Executable`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/Executable.dhall), [`ForeignLibrary`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/ForeignLibrary.dhall), [`Library`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/Library.dhall) and [`TestSuite`](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/types/TestSuite.dhall). With that primitive, it's a lot easier to talk about subrecords even if the superrecord isn't defined in such terms.

**Comment by Gabriel439** [comment]
I think it definitely makes sense to allow projecting multiple fields from a record type.  It's consistent with the support for record literals and it has a straightforward encoding in System F.  I might not have time to standardize that right now but if somebody else wants to do it before I can then I'd approve that change.

**Comment by Gabriel439** [comment]
@quasicomputational: Oops, I didn't completely read your comment the first time.  I see that you're proposing something different.  Let me think more about this.

**Comment by Gabriel439** [comment]
@quasicomputational: So I like the idea of a first-class "Set of fields" abstraction, too, so that users can reuse the same field projections.  I'd also approve that

**Comment by jneira** [comment]
As there is another better option suggested by @quasicomputational for the current user cases i think we can close this one if you agree.
