### ISSUE TITLE
dhall modules

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-lang#182]
It looks like—as any other language—some kind of module system is needed for code that is more complex than simple standalone functions.

The current solution in `Prelude` uses a file named `package.dhall` in each folder and re-exports terms in a standard record, like this:

`/package.dhall`
```
{ Integer = ./Integer/package.dhall
, Text = ./Text/package.dhall }
```

`/Text/package.dhall`
```
{ concatSep : <type>
, concatMapSep : <type> }
```

This means, as a user of Prelude, one can simply import the whole thing and get something akin to a module system:

```
let Prelude = ./deps/Prelude/packgage.dhall in
Prelude.`Text`.concatMapSep …
```

Since types can’t be in the same record with terms, one needs two such files per package to export both types and terms.
This completely breaks down for type constructors, since those still need values and dhall doesn’t allow those in records (probably not to introduce dependent types):

```
Error: Invalid field type
{ foo : \(t : Type) -> { bar : ∀(f : t -> t) -> t } }

or

Error: Invalid field
{ foo = \(t : Type) -> { bar : ∀(f : t -> t) -> t } }
```

which makes exporting them in a record impossible, see for example dada’s [functor](https://github.com/sellout/dada/blob/master/functor) type constructor.

So the next idea is to simple reference everything by absolute path. Now we arrive at the problems that golang also has: 1) absolute paths to everything or 2) vendor everything, for example in `/vendor` and reference via relative paths.
The first one is how dhall was conceived, but suffers from verbosity, network overhead, links going out of date. The second one is essentially vendoring, which can be achieved by a package manager of sorts.

My point is: records (aka the `package.dhall` convention) aren’t powerful enough to be used for practical module namespaces. On the other hand, absolute/relative imports suffer from the inconvenience of repetition.

**Comment by Gabriel439** [comment]
I am pretty sure that the only thing that might change in the near future is possibly adding support for records of type constructors.  Anything else goes against the philosophy that everything in Dhall is an expression

**Comment by Profpatsch** [comment]
> I am pretty sure that the only thing that might change in the near future is possibly adding support for records of type constructors.

I’m torn whether that’s a good idea. It sounds rather ad-hoc. My current hunch is that it’s an abuse for records to use them for namespaces. It comes quite naturally for nix expressions, but only because it’s not hindered by strict typing.

It might be better to add some primitives for import abstraction instead; on the other hand maybe I am overthinking and explicitely using opaque import paths is the best way to handle references to other code?

One insight should be taken into account: if the import can be type-checked, there is always a transformation from a dhall [expression?|term?] with imports to a corresponding function that takes an argument of the type of the import (which could lead to an explosion of code, granted), and another file with actually imports and calls the resulting function with the import.

For example:

```
./id.dhall:
λ(t: Type) → λ(a: t) → a

./original.dhall:
./id.dhall 4

./original-alt.dhall:
let id = ./id.dhall
in id 4

./no-import.dhall:
λ(id: ∀(t: Type) → ∀(a: t) → t)
→ id 4

./apply-import.dhall:
./no-import.dhall ./id.dhall
```

Which, intuitively, should mean that you can always “push out” imports to the top level.
I guess this has something to do with free variables?

**Comment by ocharles** [comment]
With the limitation that a record can no longer contain expressions and types, I do feel like there is a need for some kind of module system that lets me bundle those up. When records could contain everything, records were sufficient.

**Comment by Gabriel439** [comment]
The main bottleneck here is finding an elaboration in System F to ensure that this is sound and doesn't introduce weird type system backdoors like the previous unsound attempt did.

To illustrate the issue, you can try to encode a record storing a term and a type in System F, like this

```haskell
{ x = 1, t = Text }
```

... which corresponds to this:

```haskell
  λ(record : Type)
→ λ(makeRecord : ∀(x : Natural) → ∀(t : Type) → record)
→ makeRecord 1 Text
```

... and we can extract the `x` field from a record of that type, like this:

```haskell
  λ ( example
    :   ∀(record : Type)
      → ∀(makeRecord : ∀(x : Natural) → ∀(t : Type) → record)
      → record
    )
→ example Natural (λ(x : Natural) → λ(t : Type) → x)
```

... but if you try to extract the `t` field from that same record:

```haskell
  λ ( example
    :   ∀(record : Type)
      → ∀(makeRecord : ∀(x : Natural) → ∀(t : Type) → record)
      → record
    )
→ example Type (λ(x : Natural) → λ(t : Type) → t)
```

... you get the following type error:

```
$ dhall <<< './example.dhall'

Use "dhall --explain" for detailed errors

↳ ./example.dhall

example : ∀(record : Type) → ∀(makeRecord : ∀(x : Natural) → ∀(t : Type) → record) → record

Error: Wrong type of function argument

- Type
+ Kind

example Type

/Users/gabriel/proj/dhall/example.dhall:1:98
```

This is because the first parameter of our Boehm-Berarducci-encoded record type requires us to specify what type of value we extract:

```
example : ∀(record : Type) → ...
```

... and we cannot specify that we want to extract a `Type` because we can't allow `Type : Type`.

The way we encode a record of types like this:

```haskell
{ x = Text, y = Natural }
```

... is like this:

```haskell
λ(makeRecord : ∀(x : Type) → ∀(y : Type) → Type) → makeRecord Text Natural
```

... and then we can project either field like this:

```haskell
  λ(example : ∀(makeRecord : ∀(x : Type) → ∀(y : Type) → Type) → Type)
→ example (λ(x : Type) → λ(y : Type) → x)
```

This is one reason that records have the restriction that they have to be all terms or all types.

The other reason is that the encoding in System F also affects what the inferred type of a record type is.  For example, the inferred type of our first record type is `Type` and the inferred type of our second record type is `Kind`.  The type system backdoors introduced by the first unsound attempt were due to treating a record storing types as having type `Type` instead of `Kind`.  This System F elaboration is why Dhall infers different types for records storing terms vs records storing types:

```
$ dhall <<< '{ x : Natural }'
Type

{ x : Natural }
$ dhall <<< '{ x : Type }'
Kind

{ x : Type }
```

So the limitations of this encoding are that:

* Records have to specify in advance what kind of value you will project from them (i.e. either a term or type)
* The type of value you plan to project from them changes the type of the record type

The main reason I insist on doing this through records instead of through some out-of-band mechanism is because I want to keep as many things first-class in Dhall as possible.  Whatever Dhall modules end up being I would prefer that they remain first-class expressions that users can import, alias using `let`-bindings, export a sum type of alternative records instead of a record, or accept/return from functions.  Otherwise we end up with a situation like Haskell where you require special language support for features like "re-export qualified" which would be trivial if modules were first-class.

Anyway, that all being said, I think another way that this can be made ergonomic in the future is if there were some safe way to do computed imports in Dhall because then you could create something like `let prelude = https://prelude.dhall-lang.org` to avoid having to provide the same import boiler-plate for each thing you want to import.  The other benefit of that approach is that you don't have to import the entire package and you can instead import a more granular graph by having one `let` expression per imported value.

**Comment by Profpatsch** [comment]
> Anyway, that all being said, I think another way that this can be made ergonomic in the future is if there were some safe way to do computed imports in Dhall because then you could create something like let prelude = https://prelude.dhall-lang.org to avoid having to provide the same import boiler-plate for each thing you want to import. The other benefit of that approach is that you don't have to import the entire package and you can instead import a more granular graph by having one let expression per imported value.

Does this mean making paths/path prefixes appendable? e.g. will `prelude/Text/concatMapSep` resolve to a file in the folder referenced by `prelude`? I think this would complicate the dhall import backend semantics too much, moving from “an import is a pointer to a dhall file” to “an import could be a folder, which is a tree containing dhall files that should be cached as a hole”.

**Comment by Gabriel439** [comment]
@Profpatsch: Yeah, I don't have a specific proposal for "import synonyms" yet because I agree that it would complicate the semantics.  Right now I'm fine with just sticking with the current system

**Comment by ocharles** [comment]
We're going to restore mixed records of types and terms, so is this still so important? We're back to being able to treat a record as a module, which I think may be sufficient for now.

**Comment by Gabriel439** [comment]
Yeah, I think we should just go with records as modules for now, so I'll go ahead and close.
