### ISSUE TITLE
Extend record projection to allow projecting by record type & import

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#183]
The `⩓` operator gives us the ability to combine the types of two records into one record type:

```dhall
⊢ { hello : Text } ⩓ { world : Bool }

{ hello : Text, world : Bool }
```

This operator is compatible with imports, so I can also do:

```dhall
⊢ ./hello.dhall

{ hello : Text }

⊢ ./world.dhall

{ world : Text }

⊢ ./hello.dhall ⩓ ./world.dhall

{ hello : Text, world : Text }
```

However, *projection* is much more limited, it only supports a list of field names.

In this issue, I'd like to propose two changes:

1. Projections can be type annotated. This is not type *directed* projection, merely an extra check. The following are equivlent expressions:

    ```
    λ(x : { hello : Text, world : Text }) → x.{ hello }
    λ(x : { hello : Text, world : Text }) → x.{ hello : Text}
    ```

    This is a type error:

    ```
    λ(x : { hello : Text, world : Text }) → x.{ hello : Int }
    ```

2. Projections can refer to an import, which must be a record type:

    ```
    λ(x : /hello.dhall ⩓ ./world.dhall) → x.{ ./hello.dhall }
    ```

    has type 

    ```
    ./hello.dhall ⩓ /world.dhall → ./hello.dhall
    ```

As always, syntax is up for discussion, but this felt quite natural.

My motivation comes from playing around in http://github.com/nix-dhall and wondering what I want, rather than just copying Nix verbatim. Considering the packaging of `bash-4.4`, I might write:

```
  λ(deps : ./../busybox/busybox.dhall ⩓ ./../GCC/gcc.dhall)
→ ./../builder/autotools.dhall
  deps.{ ./../busybox/busybox.dhall }
  (   ./../builder/autotools-defaults.dhall
    ⫽ { name =
          "bash-4.4"
      , src =
          { url =
              "http://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz"
          , sha256 =
              "1jyz6snd63xjn6skk7za6psgidsd53k05cr3lksqybi0q6936syq"
          }
      , buildTools =
          [ deps.{ ./../GCC/gcc.dhall } ]
      }
  )
```

Note how `deps` is split up twice, but I don't actually know (or care about) what I'm projecting.

**Comment by Gabriel439** [comment]
Yeah, this seems like a good idea.

The only change I would suggest is that we use `x.(./hello.dhall)` instead of `x.{ ./hello.dhall }` (I'm pretty sure we can make the grammar and type-checking judgements work for the former version).  The reason why is that if `./hello.dhall` contained `{ k : T }` then `x.{ ./hello.dhall }` would be sort of like `x.{ { k : T } }` which seems inconsistent.

Other than that the rest of the proposal made perfect sense to me

**Comment by Profpatsch** [comment]
`x.( ./path )` feels more logical, but it’s yet another piece of syntax to remember. `x.{ ./path }` feels more natural, if one sees it as “`.{}` means projecting fields out of a record, so `.{ ./path }` projects all fields of `./path`, which has to be a record”.

If `./path` didn’t have to be a record, then maybe? But it’s only about the fields anyway; so would `./path: { foo : Integer }; { foo = 23, bar = 42 }.{ ./path }` be valid? And if so, would `{ foo = "not an int" }.{ ./foo }` be?

**Comment by quasicomputational** [comment]
I don't like the idea of special-casing imports like this. How about this variant: `\ (x : /hello.dhall //\\ ./world.dhall) → x.{ fields ./hello.dhall }`; the argument of the `fields` keyword should be a record type, which can be any expression (including imports). Then, e.g., in dhall-to-cabal, we'd be able to write something like `mapLibraryBuildInfo = \ (f : types.BuildInfo -> types.BuildInfo) -> \ (lib : types.Library -> types.Library) -> lib // f ( lib.{ fields types.BuildInfo } )`. (I originally floated this in #174, but this is probably a better place for it.)

**Comment by ocharles** [comment]
Thanks for bringing this up @quasicomputational, I was actually going to say just the same after sleeping on it. With my proposal, you still can't write `let fields = { hello : Text, world : Text } in { hello = "A", world = "B" }.{ fields }`, which seems unfortunate. Indeed, why should imports get special treatment? If we're introducing a new keyword, I wonder if it should just be a prefix function: `project fields { hello = "A", world = "B" }`. That, or we could get a bit SQLy and give this a bit syntactic sugar: `project fields from { hello = "A", world = "B" }`.

**Comment by Gabriel439** [comment]
@quasicomputational @ocharles : I'm not proposing special-casing imports.  The idea is that the `Projection` constructor would optionally accept an arbitrary expression for what to project:

```haskell
data Expr s a = ... | Project (Expr s a) (Either (Set Text) (Expr s a))
```

So, for example, this would be valid:

```
x.( { k₀ : T₀ } ⩓ { k₁ : T₁ } )
```

... and this would be valid:

```haskell
x.( ./someRecordType.dhall ⩓ { k₁ : T₁ } )
```

... and this would be valid, too:

```haskell
x.( let types = ./types.dhall in types.myRecordType ⩓ { k₁ : T₁ })
```

... and the example that @ocharles thought wouldn't be valid actually would be valid:

```haskell
let fields = { hello : Text, world : Text } in { hello = "A", world = "B" }.(fields)
```

The only change that you have to make to the syntax is that you have to parenthesize the projection expression to avoid confusing it with a field name (which is why the last example has to be `.(fields)` instead of `.fields`).

The type-checking judgement for the projection expression would just check that it is an immediate record type literal (i.e. not an abstract bound variable), similar to how the type-checking judgement for `⩓` already works.

**Comment by ocharles** [comment]
The suggestion was that *I* was special casing imports (and I was), not you
:)

**Comment by jneira** [comment]
What is the status of this? i am implementing some utility functions (similar to another mentioned here:  mapBuildInfo : Package -> Package) for `dhall-to-cabal` and it would be very, very handy to have `library.(types.BuildInfo)` to abstract over the four types (Library, Executable, TestSuite and Benchmark) that share their fields.
