### ISSUE TITLE
Escaping text

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-lang#186]
Consider generating a `.travis.yml` file, which is YAML with bits of shell inside it. If the generated shell isn't static, then there will be some need for shell-escaping `Text` values.

I don't really know what can be done here: adding escaping functions to Dhall would be a never-ending process because of the enormous variety of formats out there, but it's quite deliberate that there aren't the text-manipulation capabilities to build escaping functions in Dhall. Custom environments, maybe, and then a `dhall-travis` command that fills those in appropriately?

**Comment by ocharles** [comment]
I think this is just another case of something very domain specific, where it's best to introduce some domain specific types and marshalling functions. E.g., a thing to generate `.travis.yml` files has type

```haskell
forall ( ShellScript : Type ) -> forall (escape : Text -> ShellScript ) -> TravisYml ShellScript
```

**Comment by Gabriel439** [comment]
Yeah, in general the Dhall language tries to be as format-agnostic as possible, but the various Dhall integrations try to provide language-specific features (like `dhall-json`'s support for various JSON idioms).

I think @ocharles's suggestion is the way to go since `dhall-to-cabal` does something similar for processing version ranges while still maintaining compatibility with existing `dhall` tooling.

**Comment by Gabriel439** [comment]
I will close this since it sounds like the solution is to extend the language with additional built-ins (either directly or Boehm-Berarducci-encoding them as in `dhall-to-cabal`)

**Comment by singpolyma** [comment]
If the idea is to have a different interpreter (such as `dhall-json`) written for each possible output format, then this is perhaps enough.  However, the addition of `Text/show` and the existence of `dhall-nethack` say to me that there is a chance we want to support generating arbitrary formats from "pure dhall".

I would thus like to propose a new builtin for escaping, of approximately this form:

    Text/escape : [{min : Natural, max : Natural, escape : Natural -> Text }] -> Text -> Text

I believe that this could (with possibly a little help from something like `Natural/encode : Natural -> Natural -> Text` or similar, needs some though) be used to implement the bulk of encoding schemes  one might want.  For example:

```
Text/escape [
   {
      min = 9,
      max = 9,
      escape = \(_: Natural) -> "\\t"
   },
   {
      min = 65536,
      max = 1114111,
      escape = \(_: Natural) -> "\\u{${Natural/encode 16 _}}"
   }
]
```

Even with `Natural/encode` this is not enough to implement `Text/show` because we have no subtraction or division on `Natural` to enable the UTF-16 surrogates hack Dhall and JSON use for higher Unicode.  Full Unicode support in URL encoding would have a similar problem (since the codepoint should be UTF-8 encoded before percent encoding) -- however, this is not actually a big problem in either of these cases because Dhall, JSON, and most URLs allow Unicode to be represented unescaped, so only non-printing codepoints need escaping and one can hope to find this on BMP.  So, I think that just these two `Text/escape` and `Natural/encode` could get us pretty close.  Certainly enough to do shell escaping, XML escaping, etc.

**Comment by Gabriel439** [comment]
@singpolyma: I think we should first finish taking advantage of `Text/show` to implement support for JSON in pure Dhall before we add support for more output formats.

I also think it's probably better to directly from built-in support for the formats we have in mind (i.e. URL escaping, for example) than to try to encode them in a general-purpose function.  My rationale is that if we try to author a sufficiently general function to target N output formats we will likely end up with N degrees of freedom for this function when N built-ins would have been simpler

**Comment by singpolyma** [comment]
> My rationale is that if we try to author a sufficiently general function to target N output formats we will likely end up with N degrees of freedom for this function when N built-ins would have been simpler

Possible. I'm a bit on the fence when it comes to deciding if we should support output formats/general template engine in "pure dhall" at all, but the issue I see with special-purpose escaping builtins (which Text/show is almost, but not quite) is that the language expands as output formats are added, and implementations need stuff to support the whole language which seems "special purpose" to them and maybe not exercised by many users.

My thought with something like Text/escape is to support as many escapings as possible‎ while keeping and "special purpose" constructs out and hopefully not add too much support for text manipulation outside of escaping (which is something we don't want for design reasons).

**Comment by Gabriel439** [comment]
So the rationale behind `Text/show` is that it's taking advantage of a sweet spot where:

* It is consistent with the other `*/show` built-ins that the language already provides
* We can cleverly define it to also support rendering JSON and YAML, the two most common integrations

Once we try adding more built-in renderers or a general-purpose rendering function then the scope of the language broadens a lot and we commit to supporting encodings for all sorts of formats in pure Dhall.  `Text/show`, on the other hand, signals less of a commitment to supporting pure Dhall renderers since we can justify its existence even in the absence of JSON rendering support.

**Comment by singpolyma** [comment]
> `Text/show`, on the other hand, signals less of a commitment to supporting pure Dhall renderers since we can justify its existence even in the absence of JSON rendering support.

Totally fair, the only thing about Text/show that is JSON-specific at all is the lack of \$‎

**Comment by ocharles** [comment]
It's unclear what the status of this issue is to me now - as it got reopened by a somewhat-related suggestion. Should this be closed? A new issue opened?

**Comment by Gabriel439** [comment]
I'll close it since no clear proposal emerged here.  I think we should only reopen if somebody wants to propose a specific solution.
