### ISSUE TITLE
Add Github highlighting for .dhall files

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#198]
It should be just a matter of [adding a new language to their `linguist` library](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)

**Comment by f-f** [comment]
Yes, I opened this issue mostly for keeping track of this while we get there :)

According to a [search based on their example](https://github.com/search?q=extension%3Adhall+NOT+nothack&type=Code) there should be tens of repositories already.

**Comment by vmchale** [comment]
As of Oct. 24, there are 2,727 results, so I think this is an entirely justified change.

**Comment by Gabriel439** [comment]
Having gone through the list I still think there are not hundreds of repositories, yet (although there were more than I expected 🙂 ).  By my rough count there appear to be 60-70 repositories that comprise those 2,700+ results (with `dhall-haskell`'s test suite and `dhall-kubernetes` being a substantial fraction of the results).

However, I think that we will hit our mark when Dhall gets used more widely for building Haskell packages via `etlas`.  It will also make the case stronger if Dhall is a first-class integration into a more widely used tool/language because it's easy to prove that the usage will grow.

**Comment by Gabriel439** [comment]
As mentioned in https://github.com/dhall-lang/dhall-lang/pull/533 maybe now is a good time to try adding `linguist` support for Dhall as it is has grown quite a bit since the last time we checked

**Comment by f-f** [comment]
PR for fixing this up in linguist: https://github.com/github/linguist/pull/4539

**Comment by f-f** [comment]
The PR linked above has been merged, with color `#dfafff`, so we should get highlighting and proper classification on their next release 🎉

**Comment by Gabriel439** [comment]
@sellout: Awesome job! 🙂
