### ISSUE TITLE
Grammar cannot parse some http imports

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#205]
Some http import URLs are correctly parsed by the grammar, e.g.
```
https://github.com/dhall-lang/prelude/package.dhall
http://localhost/package.dhall
```

But some valid URLs are not parsed; examples include:
```
http://prelude.dhall-lang.org/
http://prelude.dhall-lang.org
https://example.com
http://localhost:8080/
http://a
```

**Comment by Gabriel439** [comment]
This was an intentional change introduced in: https://github.com/dhall-lang/dhall-lang/pull/127

This was done to unify the grammar of imports and files, for two reasons:

* This simplifies the logic for import chaining
    * Otherwise the logic has special cases for imports with no path components
* Conceptual consistency
    * If you think of the URL's path as a file path, then you shouldn't be able to import a directory, including the root directory

**Comment by ocharles** [comment]
But URLs are not file paths... This is not a good idea imo. Any valid URL
should be usable, anything else is confusing.

**Comment by Gabriel439** [comment]
@ocharles: I covered why URLs should have the same number of path components as file paths (i.e .a non-empty list of path components where the last path component is the file), but I want to add that should must also have the grammar for the individual path components.

For example, suppose that we have an import named `foo.dhall` which we want to import from `bar.dhall`, like this:

```haskell
-- bar.dhall

./foo.dhall
```

Now suppose that we rehost both expressions from a file server serving the directory tree, such that we can now import `bar.dhall` from `https://example.com/bar.dhall`, which would then transitively resolve `https://example.com/foo.dhall` due to import chaining.  If there was a mismatch in the grammar between file path components and URL path components then you could get an import error if `foo.dhall` was a valid file path but not a valid URL path.  Rehosting a directory of Dhall expressions should always "just work" if it worked when importing expressions from the directory locally.

Vice versa, locally downoading a remote directory tree (via `git clone`, `ipfs mount`, recursive `wget`, or something similar) should also "just work".

Along the same lines, if you were not able to import the top-level directory when importing locally you should not be able to import the top-level directory when importing remotely.

**Comment by f-f** [comment]
@Gabriel439 that's cool, thanks 👍 

Now I see why having the same treatment for urls and local files makes a lot of sense.

However I think that UX-wise it might make sense to allow importing naked domains - so e.g. `https://example.com` would be allowed, but not `https://example.com/`, as the first one refers to a resource that is not possible to express with local imports (while the second is the `/` directory) but a quite common url idiom.  
(Not sure though if this would mess up with the. behaviour of e.g. `wget`)

**Comment by Gabriel439** [comment]
@f-f: Naked domains would still need to be treated as a path for the purpose of import chaining

**Comment by f-f** [comment]
I think this is the best approach, so to close this issue I'll just explicitly add a note about http imports in the "Import chaining" section.

**Comment by philandstuff** [comment]
Apologies for reviving an old discussion, but this caught my eye:

> Vice versa, locally downloading a remote directory tree (via git clone, ipfs mount, recursive wget, or something similar) should also "just work".
> 
> Along the same lines, if you were not able to import the top-level directory when importing locally you should not be able to import the top-level directory when importing remotely.

I understand and accept this argument, but one thing nags at me: if we accept this line of reasoning, does it not also follow that we shouldn't accept anything within a URL that doesn't look like a `path`?  We already exclude some things: bare domains, paths ending in `/`, etc.  But we allow query strings.  Why? Should we not also exclude query strings, for the same reason?  If not, what makes query strings and empty paths qualitatively different? :confused:

**Comment by Gabriel439** [comment]
@philandstuff: Yeah, thinking about this more, perhaps we should permit the final path component of a URL to be the empty string (which would permit bare domains and paths ending in `/`)
