### ISSUE TITLE
alias: protocol for shortening import paths

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-lang#219]
Dhall’s imports are very powerful, but not first class citizens of the language. Once we assign an import to a value

```
   let List/map = https://dhall-lang.org/long/path/to/prelude/List/map
in let List/otherfunc = https://dhall-lang.org/long/path/to/prelude/List/otherfunc
in {=}
```

it is transparently replaced by Dhall expression represented by the import path.
This also means that we can’t shorten them like in other languages where imports have more of a notion of being “first class”, e.g. by being stringly typed, like in nix:

```nix
let preludePrefix = https://dhall-lang.org/long/path/to/prelude;
    map = import "${preludePrefix}/List/map";
    otherfunc = import "${preludePrefix}/List/otherfunc";
in {}
```

In Dhall this can be alleviated somewhat by setting up the local folders in a way that makes all dependencies reachable via relative paths (which is to say: vendoring):

```
$ git clone https://github.com/FormationAI/dhall-bhat ./bhat
$ nix-build -A dhall-prelude --out-link ./prelude '<nixpkgs>'
```

```
   let List/map = ./prelude/List/map
in let Functor/void = ./bhat/Functor/void
in {=}
```

In practice this is brittle, because it depends on a precise setup. Also, one needs third party tools to get one’s dhall code working. This is what the Dhall import system was designed to avoid; Dhall code should be stand-alone.

I propose a new `alias:` protocol to resolve that dichotomy.

An import like `alias:prelude/List/map` will make Dhall start looking at the first element of the path. If it’s a folder, it will look at the next element, until one element is a file. In our example the first element—`prelude`—is a file. It shall have the content:

```
https://raw.githubusercontent.com/dhall-lang/Prelude/v1.0.0
```

This causes Dhall’s importer to replace the path, including the current element (`prelude`), with the aliased path. The remaining path elements (`List` and `map`) are then resolved relatively to the aliased path. The final import will be:

```
https://raw.githubusercontent.com/dhall-lang/Prelude/v1.0.0/List/map
```

This also works if the local prefix is longer than one element. Let’s assume `prelude` has the same contents as before, but this time it is placed inside the `modules` folder, and we reference it from deeper within our project:

```
alias:../../modules/prelude/List/map
```

It will still point to the same remote file as before.

There are some special cases we need to think about:

1) What happens if there is no alias file at all? I think it should just act like a local import in that case. No point in throwing an error.
2) What happens if the last element is an alias file? It should still resolve and import the expression pointed to by the aliased URI. Take `alias:prelude` from the first example; the link might be a perfectly valid dhall file, even if there is more dhall resources under it. (Consider an http server that returns a dhall file instead of some directory at the `/prelude` endpoint.)
3) What happens if the suffix of the remote contains another alias? Again from our `prelude` example, what if `List` was another alias file, pointing to `https://someotherserver.com/List`. Intuitively I would disallow that, because the user explicitely requested `raw.githubusercontent.com`, not `someotherserver.com`.

**Comment by Gabriel439** [comment]
@Profpatsch: Could you give an example of how this would be used?

**Comment by Profpatsch** [comment]
What kind of example do you want to see? I tried to give an example in the description above (having a local alias to prelude that can be accessed without having to paste the `https` link into each separate dhall file (and multiple times!).
The alias files should also contain the integrity hashes and access information, so that doesn’t have to be duplicated over one repository.

I will try to create an example repository.

**Comment by Gabriel439** [comment]
@Profpatsch: I mean, a self-contained example of defining an alias and using the alias within the same expression.  You gave an example of how you would implement aliases in Nix (i.e. string interpolation of the imported paths), so maybe translate that example to Dhall using your proposed alias feature

**Comment by Gabriel439** [comment]
Ah, I get it now!  I like this idea 🙂 

I noticed that you first proposed using an `alias:` prefix for these imports but your latest example just uses the normal import syntax.  Did you change your mind about the prefix?

I'd suggest dropping the `alias:` prefix and using the same syntax for both normal imports and aliased imports.  In other words, if you try to import:

```
./Prelude/List/map
```

... then the interpreter will:

* first try to resolve the local file `./Prelude/List/map`
* if that fails then try to resolve `./Prelude/List` as an alias file
* if that fails then try to resolve `./Prelude` as an alias file
* if all of them fail, then report the original error from trying to resolve `./Prelude/List/map`

> What happens if there is no alias file at all? I think it should just act like a local import in that case. No point in throwing an error.

Yeah, if we use the same syntax both for normal imports and aliases then it just behaves like a normal import if the file and all prefixes are missing.

> What happens if the last element is an alias file? It should still resolve and import the expression pointed to by the aliased URI. Take alias:prelude from the first example; the link might be a perfectly valid dhall file, even if there is more dhall resources under it. (Consider an http server that returns a dhall file instead of some directory at the /prelude endpoint.)

I think if the full path is an alias file then it should behave the same as a normal import, so it will succeed if and only if the path the alias file contains points to a valid Dhall expression.

> What happens if the suffix of the remote contains another alias? Again from our prelude example, what if List was another alias file, pointing to https://someotherserver.com/List. Intuitively I would disallow that, because the user explicitely requested raw.githubusercontent.com, not someotherserver.com.

We can actually safely allow this.  Dhall already has standard semantics for [chaining directories](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#chaining-directories) which we can reuse to specify how chaining aliases works.  If an alias file located at `dir₀` refers to another alias file `dir₁`, then the latter alias behaves as if it were located at `dir₀ </> dir₁`.

So, for example, if `https://raw.githubusercontent.com/dhall-lang/Prelude/v1.0.0/List/map` did not exist and `https://raw.githubusercontent.com/dhall-lang/Prelude/v1.0.0/List` existed and contained `https://example.com/List` then the final path would be `https://example.com/List/map` because:

```
https://raw.githubusercontent.com/dhall-lang/Prelude/v1.0.0/List </> https://example.com/List = https://example.com/List
```    

Note that this is safe because Dhall does not forward custom headers across different domains so this won't cause `raw.githubuser.content.com` to accidentally forward any sensitive GitHub personal API tokens to `example.com`

**Comment by Profpatsch** [comment]
> I noticed that you first proposed using an alias: prefix for these imports but your latest example just uses the normal import syntax. Did you change your mind about the prefix?

I didn’t, but now I recognize that it’s way more natural to just use relative imports for this. :smile: 



> We can actually safely allow this. Dhall already has standard semantics for chaining imports which we can reuse to specify how chaining aliases works.

Whoa, that’s awesome.

I wonder if we can reuse the normal form for imports for the import files. That is, it is put through the parser and valid if that returns a valid `ImportAlt` or an `Embed Import`.
For example, it might make sense to allow putting an integrity hash into an import file and specify alternatives.

**Comment by f-f** [comment]
> Yeah, if we use the same syntax both for normal imports and aliases then it just behaves like a normal import if the full path is a valid file.

While this sounds great on paper, I'm slightly worried it would be rather implicit and kind of "overloading" the import resolution? (OTOH this is nice because there is much reuse of the existing logic).  
What I'm trying to say is that maybe drawing the line with the `alias:` syntax is a good idea. (downside in this case: more "language surface" to learn)

**Comment by Gabriel439** [comment]
So I've been thinking about this some more and I think the right solution here is actually https://github.com/dhall-lang/dhall-lang/issues/139

In particular, see: https://github.com/dhall-lang/dhall-lang/issues/139#issuecomment-415290127

Under that proposal, the code would look like this:

```haskell
    import Prelude = http://prelude.dhall-lang.org

in  import Bhat = https://raw.githubusercontent.com/FormationAI/dhall-bhat/5010ebfb1190af9f22eb42bb5fc7aa31840b710e

in  { example1 = Prelude.`List`.map  -- Same as: http://prelude.dhall-lang.org/List/map
    , example2 = Bhat.StateT.Applicative -- Same as: https://raw.githubusercontent.com/FormationAI/dhall-bhat/5010ebfb1190af9f22eb42bb5fc7aa31840b710e/StateT/Applicative
    }
```

This has a couple of advantages:

* You don't need a separate `let` expression for each new value that you import
* The code is self-contained (i.e. doesn't depend on a separate alias file to work)
* Importing a packages resembles Haskell syntax (if you ignore the `in`) and accessing values from that imported package resembles Haskell's fully qualified import syntax

**Comment by f-f** [comment]
@Gabriel439 This is cool. Another advantage of the directory-based approach is that http urls' syntax will be covering all urls again, which is relevant for #205.

Would this import have the same semantics of Records? That is, will it be possible to mix types and values? (intuitively yes, because all of this would happen at import time, not at typecheck time)

**Comment by Gabriel439** [comment]
I'm going to close this in favor of #139 which has the most up-to-date discussion on this issue.

I'll summarize it briefly here, which is to say that the solution I'm going with is each package exports a record of terms and a record of types.  See my comments beginning here: https://github.com/dhall-lang/dhall-lang/issues/139#issuecomment-417953563
