### ISSUE TITLE
Syntactic sugar for multiple lets and lambdas.

### ISSUE THREAD

**Issue by stevana** [dhall-lang/dhall-lang#226]
Perhaps this has been suggested before, but I couldn't find any open or closed issue for it, so here it goes. Can we let the following: 

```
let
  x0 = a0
  x1 = a1
  ...
  xn = an
in
```

desugar into:

```
let 
  x0 = a0
in
let
  x1 = a1
in
...
let
  xn = an
in
```

And while at it, also let:

```
\(x0 : A0, x1 : A1, ..., xn : An) ->
```

desugar into:

```
\(x0 : A0) -> \(x1 : A1) -> ... \(xn : An) ->
```

?

**Comment by ocharles** [comment]
I would probably have `\(x0 : A0) (x1 : A1) -> ...` be the syntax, rather than use commas.

**Comment by stevana** [comment]
Yeah, that would probably be even better.

**Comment by Gabriel439** [comment]
I'd prefer to require that the user explicitly curry functions with nested lambdas rather than provide syntactic sugar because the sugar does not save that many characters (especially when automatically formatted) and it introduces multiple ways of expressing the same ideas.

Generally I try to restrict the language to as few orthogonal features as possible so that each new feature provides enough value to the user to justify the cost of everybody having to learn to read it.

However, I do want to point out that you can get something pretty close to what you originally requested by taking a record as an argument:

```haskell
λ(r : { x0 : A0, x1 : A1, …, xn : An }) → …
```

**Comment by stevana** [comment]
Ah, I like the record as argument syntax idea.

**Comment by ocharles** [comment]
It works for lambdas but doesn't answer the suggestion about `let`.

**Comment by jneira** [comment]
Mmmm, could be it
```
let r={
  x0 = a0,
  x1 = a1,
  ...
  xn = an
}
in r.x0
```
too?

**Comment by Gabriel439** [comment]
I will go ahead and close this since I think the conclusion we came to was that we could use records as a substitute both for "multi-`let`" and "multi-lambda"

**Comment by ocharles** [comment]
I don't agree that records are a suitable alternative as it means that every binding now has to be prefixed so it is *not* an equivalent transformation. However, if we got record matching, then you could at least write

```
let { x0, x1, x2 } = { x0 = ..., x1 = ..., x3 = ... } i
```

I had a look at what other languages do, and the options seem to be split between languages that allow multiple bindings per `let`:

* Haskell has this
* Nix has this
* Elm has this

Languages that don't:

* OCaml doesn't seem to do this. It sort of does with `letrec` and `and`, but that's actually to express recursion between bindings.
* ... and nor does ReasonML

**Comment by stevana** [comment]
> The main reason is that records don't allow later definitions to refer to prior definitions.

Perhaps introducing proper dependent records would be an alternative then?
