### ISSUE TITLE
Let bindings should splat records

### ISSUE THREAD

**Issue by reactormonk** [dhall-lang/dhall-lang#231]
E.g.
```
let record = { Foo = "foo", Bar = "bar" }
in let record in
Foo
```
should return `"foo"`.

**Comment by Gabriel439** [comment]
This is similar to https://github.com/dhall-lang/dhall-lang/issues/74

The main difference is that this is proposing to bring all fields into scope (similar to an "open" import, Nix's `with` keyword or Haskell's `RecordWildCards`) whereas #74 is proposing to bring explicitly chosen fields into scope (similar to Nix's `inherit` keyword or Haskell's `NamedFieldPuns`)

My preference is to go with the proposal in #74 (although I hadn't gotten to standardizing and implementing it yet) and be explicit about what values are brought into scope.  My rationale is that this makes it easier for people reading the code to reliably discern where an identifier originated from.  You could imagine that if there were multiple records unpacked like this:

```haskell
    let record = ./someImport.dall
in  let record2 = ./anotherImport.dhall
in  foo
```

... there wouldn't be an easy way to tell whether `foo` came from `someImport.dhall` or `anotherImport.dhall` without reading through both imports.

However, this is not a strong preference and I could be convinced otherwise because I can see how convenient it would be to bring all of them into scope.

**Comment by f-f** [comment]
I'd like to add my preference for #74 as well

The reasoning is: it's super nice to have a way to bring fields into scope (as demonstrated in #74, for both `let`s and anonymous functions), but *implicitly* getting all of them might end up in awkward situations like the one mentioned above, while not adding much convenience over explicitly mentioning them.

**Comment by Profpatsch** [comment]
If I can’t grep for it, it’s worthless.

**Comment by Gabriel439** [comment]
I'll go ahead and close this in favor of #74 then
