### ISSUE TITLE
deprecate `constructors`

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-lang#244]
As proposed by @Gabriel439.

Rather than having a `constructors` keyword that converts a union to a record of value constructors, provide an operator on unions to select an alternative to construct.

This can be a compatible change, as `constructors` can be simply the identity function, and the `.` operator will select the alternative from the union.

**Comment by sellout** [comment]
This proposal means that `.` is the only overloaded operator in Dhall (I think). I wonder if we should introduce an additional operator for union selection, distinct from record projection. The change in the description is still a good idea to maintain compatibility until the next breaking change.

**Comment by Gabriel439** [comment]
@sellout: Note that this could potentially be done in three stages:

* Stage 1: Overload the `.` but do not change the `constructors` operator.  This is backwards compatible, but users don't automatically benefit from the speed improvement until they update their code to remove the `constructors` keyword
* Stage 2: Change `constructors` to be the identify function.  This is *technically* not backwards compatible if you annotate the result of `constructors` (which basically nobody ever does because the type is so large).  Still technically requires a major version bump
* Stage 3: Remove `constructors`.  Obviously this is not backwards compatible

**Comment by f-f** [comment]
I really like the idea. Some comments:
- I'm not sure going the route of overloading operators is a good idea, so if we can find a distinct operator for this it would be probably nicer to go that route
- since both 2. and 3. in @Gabriel439's plan are breaking and not backwards compatible, let's bundle them in a single release as @sellout noted

**Comment by Profpatsch** [comment]
I don’t understand the description, could you provide some comparisons?

**Comment by Gabriel439** [comment]
@Profpatsch: Currently, we have to write this:

```haskell
    let SomeType = < Left : Natural | Right : Bool >

in  let someType = constructors SomeType

in  [ someType.Left 1, someType.Right True ]
```

After this change, we can now write:

```haskell
    let SomeType = < Left : Natural | Right : Bool >

in  [ SomeType.Left 1, SomeType.Right True ]
```

There are two primary motivations for this:

* Less boilerplate (having to wrap every union type in `constructors` at the beginning of each module)
* Faster to type-check and normalize (since you don't need to materialize a giant `constructors` record)

**Comment by Gabriel439** [comment]
@f-f: The reasons I suggested overloading the `.` operator are:

* It provides a smooth migration path.  You can just specify `constructors x = x` and users get the performance benefits for free and in 99.9% of code it's not a breaking change
* The `.` operator is already overloaded (you can already use it for record projection, too, such as `someRecord.{ x, y }`)
* The `.` operator is the only operator in the language that is not associative.  I figured that, for consistency, it might make sense to reserve `.` for non-associative functionality where the behavior can be inferred from the left operand to reserve and other operators for associative operations
* It feels to me like the most appropriate choice of operator for this purpose since I feel like we should use the same operator for namespacing alternatives of a union type as we do for namespacing values exported by a package record

**Comment by FintanH** [comment]
So as mentioned in https://github.com/dhall-lang/dhall-haskell/issues/635, I wanted to battle test this to see if it gave us any improvements in our pathological use case.

We went from ~56s to ~65s so about 15-20% decrease :/

The syntax looks great thought :smile:

**Comment by Gabriel439** [comment]
Hmmm, that seems odd.  It's not clear how this would make things slower.  It seems like in all situations it should be at least as fast since it's doing less work.

**Comment by FintanH** [comment]
Ya I think you're right. Let me go back and double check the numbers. It could be that my last benchmark was against an intermediate state while getting the last improvements.

**Comment by FintanH** [comment]
Ok, so I ran against https://github.com/FintanH/dhall-haskell/commit/e37e129f382c0e5e050190ee9ee49897ccbef5e6 and got ~61s, so definitely a closer gap.

**Comment by Gabriel439** [comment]
If you can put up your branch I can do the remaining steps to standardize this.  However, that means we still need to profile your code to see what is the bottleneck

**Comment by FintanH** [comment]
My WIP is here https://github.com/FintanH/dhall-haskell/tree/fintan/union-access :)

**Comment by Gabriel439** [comment]
@FintanH: Looking at your branch, I think that the reason for the slowdown is that you are normalizing the `r` when type-checking `Field`, even if the type inferred for `r` is a `Record`.  In other words, it would be faster to only normalize `r` if it is not a `Record`, like this:

```haskell
loop ctx e@(Field r x       ) = do
    t <- fmap Dhall.Core.normalize (loop ctx r)

    case t of
        Record kts -> ... -- Still the same
        Type -> do
            case Dhall.Core.normalize r of
                Union kts -> ... -- Logic for selecting an alternative of a union
                _ -> ... -- Type error
        _ -> ... -- Type error
```

**Comment by FintanH** [comment]
Thanks @Gabriel439 I added that change and was more disciplined about how I was measuring things. I made a reproducible case, compared the baseline to the new changes over an average of 5 runs and the timings are comparable: 77.646s for master, 76.052s with the new changes. So no slow down at least!

I'll try complicate the configuration and re-run the test again to see how they compare as unions get added.

**Comment by FintanH** [comment]
> Stage 2: Change constructors to be the identify function. This is technically not backwards compatible if you annotate the type of the result of constructors (which basically nobody ever does because the type is so large). Still technically requires a major version bump

@Gabriel439: this is actually not backwards compatible if anyone has done:
```
let F = constructors (./Foo)
in { Foo = F, term1 = term1, term2 = term2 }
```

i.e. They were exporting the record created by `constructors` in another record of terms. We actually do this in some of our internal code at Formation, but it's only one instance. So maybe "basically nobody ever does" that either :grin:

**Comment by Gabriel439** [comment]
@FintanH: Just to clarify: You mean that it's also not backwards compatible because it changes the hash, correct?

**Comment by FintanH** [comment]
Oh that as well. But I meant, the user will get an error for mixing types and terms in the above example.

**Comment by ocharles** [comment]
Would this break [`dhall-to-cabal`'s usage](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/prelude.dhall)?

**Comment by Gabriel439** [comment]
@ocharles: Yes

**Comment by ocharles** [comment]
Alright. I don't particularly mind, I'm in support of this change. Just wanted to check.

**Comment by Gabriel439** [comment]
I just wanted to mention that there's now a Dhall wiki page documenting the three phases of the `constructors` deprecation and how users can migrate:

https://github.com/dhall-lang/dhall-lang/wiki/Migration%3A-Deprecation-of-constructors-keyword

**Comment by f-f** [comment]
This has been now fully standardized, as the third part of the plan went in with https://github.com/dhall-lang/dhall-lang/pull/385  🎉
