### ISSUE TITLE
Whitespace in file names?

### ISSUE THREAD

**Issue by andrewchambers** [dhall-lang/dhall-lang#254]
I couldn't see how to import a file with whitespace in it's file name anywhere. Is there some sort of escape syntax?

**Comment by Gabriel439** [comment]
No, there currently is no way to include spaces in import paths.  This is due to the need to unify the grammar for both file path components and URL path components.

For example, suppose that you could quote a path to introduce spaces, such as:

```haskell
'./some/path with/spaces'
```

... but then you hosted the above Dhall expression at `https://example.com/foo.dhall`.  Then due to Dhall's support for import chaining the final path would resolve to:

```haskell
'https://example.com/some/path with/spaces'
```

... which would be an invalid URL.

**Comment by jneira** [comment]
Maybe we should be use the scape character for urls? `./some/path%20with/space`.
Or at least the alternate form using the file scheme: `file://./some/path%20with/spaces`

I' ve done some tests and i got some strange outputs:
```console
C:\Users\Javier\dev\lang\eta\dhall\dhall-eta>type "my example.dhall"
1

C:\Users\Javier\dev\lang\eta\dhall\dhall-eta>type import.dhall
file://./my%20example.dhall
C:\Users\Javier\dev\lang\eta\dhall\dhall-eta>dhall < import.dhall

Error: Invalid input

(stdin):1:7:
  |
1 | file://./my%20example.dhall
  |       ^
unexpected '/'
expecting expression or whitespace
```
http urls works with `%20`

**Comment by andrewchambers** [comment]
I was thinking something like a builtin function to import a path from a string would work.

**Comment by ocharles** [comment]
@andrewchambers that's going to be much more suspect. For example, I could give you a Dhall expression (hosted remotely) that just returns `/etc/shadow`. If you put that into your builtin, then I can escape the security guarantees of Dhall (a remote import should not be able to choose which local files to import).

**Comment by Gabriel439** [comment]
@jneira: So I think requiring the user to percent-encode the local file path wouldn't solve the original problem.  My understanding is that they would like to import a path that had a non-percent-encoded space.

@ocharles: Alright, so we can add support for percent-encoding path characters when doing import chaining, but then we also need a syntax for quoting the path so that the space is not interpreted as the end of the import literal.

**Comment by andrewchambers** [comment]
My original use case was that I wrote a mini package for Go to use dhall for my server config. 

https://github.com/andrewchambers/go-dhallconfig/blob/master/dhallconfig.go

Where I use it I do something like:

server -config ./my_config_expression.dhall

Clearly this would have surprising results if a user  does something like:

server -config ./my\ config.dhall

**Comment by ocharles** [comment]
I think it should be possible to quote a file path, and if that's used with HTTP then it becomes percent encoded. A suggestion is to change the grammar to allow path components to be surrounded by `"`, and during evaluation of this if it's used with HTTP then percent encode, and if it's a local file path simply pass it unchanged.

So:

```dhall
./"hello world".dhall
```

or

```dhall
http://my.dhall/"hello world.dhall"
```

It would still need to support escaping `"` itself - a backlash sequence seems fine here.

**Comment by Gabriel439** [comment]
@ocharles: Yeah, I really like the idea of quoting path components.

It's non-disruptive since the path components are already the one portion of the grammar where we deviate from the official grammars for both files and URLs.  Contrast with quoting, say, the entire URL, which would require significant departures from the official URI grammar.

I vote for going forward with that as the solution for supporting an extended character set in paths (including whitespace), along with support for percent-encoding extended characters when chaining imports.

**Comment by Gabriel439** [comment]
I have a pull request ready now for the change to the standard: https://github.com/dhall-lang/dhall-lang/pull/293
