### ISSUE TITLE
Grammar ambiguity in http-related rules

### ISSUE THREAD

**Issue by SupraSummus** [dhall-lang/dhall-lang#259]
I've noticed ambiguity in rule `host`. For input `1.1.1.1` it can parse it as `IPv4address` or as `reg-name`. I see two options how to disambiguate this:
 * [more structural] make `reg-name` more strict
 * [easier] get rid of `IPv4address`

**Comment by SupraSummus** [comment]
I meant to get rid only of `IPv4address` grammar rule. In this case IP addresses can still be referenced, but grammar will parse them as `reg-name` and IP addresses has to be recognized on later stage (during AST postprocessing or evaluation - but this is an implementation detail).

**Comment by Gabriel439** [comment]
@SupraSummus: My preference is to keep the rule since those rules are lifted almost verbatim from [the corresponding RFC](https://tools.ietf.org/html/rfc3986) .  Instead, I think we should document in the grammar that the original RFC is ambiguous and specify that implementations should prefer parsing as `IPv4Address` over `reg-name`
