### ISSUE TITLE
Grammar cannot terminate paths correctly

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-lang#291]
It looks like the grammar is not able to parse [one of the successful parser tests from the Haskell implementation](https://github.com/dhall-lang/dhall-lang/blob/master/tests/parser/success/pathTerminationA.dhall). While trying to parse this:

```haskell
-- Verify that certain punctuation marks terminate paths correctly
  λ(x : ./example)
→ ./example[./example, ./example{bar = ./example<baz = ./example>, qux = ./example}, ./example]
```

the grammar doesn't seem to expect that `[`:
```
Parse error at line 3, column 12:
→ ./example[./example, ./example{bar = ./example<baz = ./example>, qux = ./example}, ./example]
           ^
Expected one of:
"/"
%x2192
"?"
"||"
"+"
"++"
"#"
"&&"
%x2227
%x2afd
%x2a53
"*"
"=="
"!="
%x0061
%x0073
" "
%x0021-0022
%x0024-0027
%x002a-002b
%x002d-002e
%x0030-003b
%x003d
%x0040-005a
%x005e-007a
%x007c
%x007e
%x0009
%x000a
%x000d
"--"
"{-"
"//\\\\"
"//"
"/\\"
"->"
":"
:end-of-string
```

**Comment by Gabriel439** [comment]
@f-f: I found the problem.  It is due to the required whitespace in between a function and its argument which was introduced in https://github.com/dhall-lang/dhall-lang/pull/161

The first `./example` would normally be the function and the list would be its argument, but they are not separated by whitespace, triggering the parse failure.

I think the resolution here is to add a new parse failure test case for `./example[1]` and then remove the first `./example` from this test case

I hadn't updated the Haskell implementation to reflect that change, which is why that hadn't failed the Haskell test suite.  I will open a pull request do that shortly.
