### ISSUE TITLE
Use plain variables for builtin functions

### ISSUE THREAD

**Issue by MonoidMusician** [dhall-lang/dhall-lang#314]
I was wondering if you would be in favor of using plain variables for builtin functions; that is, `Natural/show` (etc.) become plain variables automatically introduced first in scope, instead of special keywords that are oblivious to scope. I don't have strong feelings either way, but I think this makes sense in terms of reducing the amount of "magic" (special rules) in the language – they look like variables, so they should behave like variables. This means that they could be shadowed, but you could still use use the top-level function with the appropriate `@` level.

It would simplify the syntax and AST a little bit, as well as typechecking, but I recognize it would probably complicate most implementations of `normalize` (because you would have to keep track of shadowing of these variables, so `let Natural/show = \(n : Natural) -> Natural/show (n + 1) in Natural/show 0 ++ " = " ++ Natural/show@1 0 ++ " + 1"` reduces to `"1 = 0 + 1"` not `"0 = 0 + 1"` ... well, that case specifically wouldn't have issues, but shadowing is important).

The result is that the process documented here could potentially be used to add the standard builtin functions into the language (note: I think it would have to be enhanced to take variable shadowing into account, it doesn't look like it does currently ...):
https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function
Or the cases could be kept in the normalization algorithm still.

One downside is that normalization becomes slightly less predictable in theory, since it would depend more on context. That is to say that you couldn't take expressions from deep inside the AST and partially normalize them and expect to get the same result, if the context of variable shadowing is not kept track of. But, I think in practice, this should not be a big deal, since that kind of operation seems rare and I expect shadowing those variables will also be very rare, and Dhall APIs could communicate that you need to keep track of context when calling `normalize` for correctness.

(P.S. Builtin types like `List` should remain as keywords, otherwise typechecking becomes a lot more complicated.)

**Comment by Gabriel439** [comment]
@MonoidMusician: I think my main question is how to standardize the normalization rules for built-in functions in such a way that it takes shadowing into account

**Comment by MonoidMusician** [comment]
Right ... We could pass down a context that holds no information but just keeps track of what variable names have been introduced since the global scope (`Dhall.Context.Context ()` in Haskell, I don't know the best way to describe that in the syntax of the standard).

I actually pass down information in the context that includes variable values (and their types, when typechecking), so substitution does not result in a whole traversal (instead, the `Var` branch looks it up in the context that is passed down), but that's orthogonal to this proposal.

**Comment by Gabriel439** [comment]
@MonoidMusician: The closest thing I could figure out was to have the standard require that the top-level expression was extended with something like:

```haskell
let Natural/build = $Natural/build$

let Natural/fold = $Natural/fold$

…

in  topLevelExpression
```

... and then matching on `$Natural/build$` in the rule (since that's not a valid label).  If you do that then it would already handle the context correctly.

**Comment by sellout** [comment]
@Gabriel439 Yeah, that matches my intuition of how this would work.

**Comment by MonoidMusician** [comment]
Hm ... Are you saying that `Natural/build` would still be a builtin in terms of the `Expr` AST in Haskell, but we would only allow access it to it via referencing it as a (global) variable? That might work nicely, in fact – then whenever the `NaturalBuild` constructor occurs, we know it references the top-level definition (since `let` substitution respects shadowing). I'm wondering if pretty-printing might be an issue then?

**Comment by f-f** [comment]
This sounds to me like a risky tradeoff: on one hand it is cool, as
- we'd reduce the AST size, and 
- we'd standardize "builtins extensibility" (e.g. the Clojure compiler doesn't have any extensibility point so far to define your own builtins)

But on the other hand it would
- complicate normalization and
- introduce shadowing of builtins

Why is shadowing a problem?
- there's no use-case I can think of (that is, I think the right way to "patch" a builtin is through the interpreter extensibility mechanism)
- I'm not sure how it would work with imports.

Example:
```haskell
-- ./foo.dhall
Natural/show 1
```

```haskell
-- ./bar.dhall
let Natural/show = λ(n : Natural) → Natural/show (n + 1)
in ./foo.dhall
```

Should `bar.dhall` return `"1"` or `"2"`?

So would we "inherit" the context when importing (breaking the self-containment of expressions) or would every import inherit the "standard" context? (thus making shadowing not that useful in the end - this is the "current behaviour")
Assuming we want to go with the second option, you'd be allowed to shadow builtins only inside the same file...which I feel it could be quite confusing to have?

**Comment by Gabriel439** [comment]
@f-f: It wouldn't even reduce the AST size because you still need to reserve AST constructors to recognize as the "real" built-ins (i.e. the `$Natural/build$` in the example).  The main difference is that it lets you shadow built-ins.

Presumably the way this would affect imports is that you would add the built-in context to each imported expression, which is what the Haskell implementation already does for custom built-ins.

However, I'm weakly opposed to this because it seems out of scope for the standard and seems more like an implementation-specific feature to allow users to customize the language.  The main benefit if the user does not want to customize the language is to allow them to shadow built-ins, but I'm not convinced that we want to do that.

**Comment by Nadrieril** [comment]
I'd like to reopen this idea, since there is a benefit that hasn't been mentioned here yet: adding new builtins wouldn't break existing code anymore (see #394). Currently, "builtins extensibility" technically breaks the standard. This may or may not be a legitimate problem.
I personally think it would be worth it, since it makes the language more uniform and it doesn't look like implementations would need to change much.
