### ISSUE TITLE
Could the documentation be more specific about what a "malicious user" is?

### ISSUE THREAD

**Issue by Qix-** [dhall-lang/dhall-lang#333]
![image](https://user-images.githubusercontent.com/885648/50536136-93b6d480-0b51-11e9-8c23-fb00223e01ca.png)

> You can safely import and evaluate untrusted Dhall code, even code authored by malicious users.

Right now, Dhall allows imports to pull from HTTP endpoints. I tested this myself by starting a local web server and pointing an import to `localhost`. Worked just fine.

The website states that you can "safely" run Dhall configuration that's been accepted from a malicious user, but this is not _actually_ safe.

Dhall allowing HTTP imports and then subsequently running the code has two very unsafe effects:

1. A malicious user can track victims (even without a weakness in the code)
2. A malicious user can deliver payloads that exploit zero-days or other weaknesses in various implementations of Dhall

Personally, I don't see why HTTP imports were considered such a critical feature to have, but that's not the point of this ticket.

It's very clear it's not _completely_ safe and you cannot guarantee safety in the context of malicious users and untrusted Dhall code. Malicious users are still able to leak information about a victim.

You should update this phrasing on the site, as it's misleading and somewhat irresponsible.

**Comment by Profpatsch** [comment]
> 2\. A malicious user can deliver payloads that exploit zero-days or other weaknesses in various implementations of Dhall

I don’t think this piece of text describes implementations, rather the language standard.

Your definition of “safety” seems different from the one assumed in the text.

**Comment by ocharles** [comment]
> I don’t think this piece of text describes implementations, rather the language standard.

The standard is not free of bugs, and there's no reason to assume it's not free of security problems. The comment seems reasonable.

**Comment by Qix-** [comment]
[HTTP imports are part of the standard](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#imports-1). Point #1 still stands.

My definition of safety includes bringing up potentially unsafe verbiage on landing pages :) Saying I can, as a consumer of Dhall, not have to worry about malicious Dhall code is a very large claim without context.

Upon digging further, it appears it's referring to the semantics of the library calls - guaranteed not to throw or abort or whatever. That's much less interesting than what's being claimed on the front page.

**Comment by Profpatsch** [comment]
> That's much less interesting than what's being claimed on the front page.

What is your reading of the safety claims then? Apart from HTTP?

**Comment by Qix-** [comment]
I think you're missing my point, @Profpatsch, due to your last paragraph:

> On the other hand, to prevent injection of malicious code, Dhall offers to protect your imports with hash-sums.

You're only thinking about MITM. You're not thinking about if developers accept Dhall code from untrusted users, which is the unsafe part. The documentation on the front page implies it is safe to do so, in which my point is that it's not.

**Comment by Gabriel439** [comment]
> A malicious user can track victims (even without a weakness in the code)

Yes, unless they protect the import with a semantic integrity check.  If they do so then the import is only downloaded once and then cached locally forever (or until they delete their own local cache for whatever reason).

I can update the phrasing of the statement to reflect this, such as: "Dhall provides support for semantic integrity checks which guarantee that …" to imply that the user may need to use`dhall freeze` to protect their code in this way.  Would that resolve your concern for this point?

> A malicious user can deliver payloads that exploit zero-days or other weaknesses in various implementations of Dhall

I think the most compelling argument that has been made so far is that there can be a specification bug.  For example, I'm aware of one such specification bug at this very moment, which is that the referential transparency check has not yet been standardized (which I will address very soon).  This referential transparency check is a safety guarantee that exists in the Haskell implementation but I forgot to upstream it into the standard until reviewing this thread.

Even accounting for that, I view the risk of compromise to be so negligible that I feel confident declaring Dhall safe.  The word "safe" always requires a certain threat model and Dhall is safe within the threat model that most users assume when they read the safety claim on the website.  A 100% precise statement of the safety guarantees and threat model would require inlining the entire text of the "Safety Guarantees" document linked immediately below that sentence.

At most, I may qualify the statement to mention the use of semantic integrity checks in the safety claim since I believe they resolve the concerns you expressed so far.  A semantic integrity check (A) is permanently cached locally, foiling tracking and timing attacks and (B) pins the semantic content of the import, making it impossible to modify even by a MITM attack over an unprotected channel.  This is covered in the "Safety Guarantees" link.

> You're not thinking about if developers accept Dhall code from untrusted users, which is the unsafe part

I was absolutely thinking about the use case of importing code from entirely untrusted and even hostile users when I designed Dhall's import system so let me know if you have a specific attack vector in mind that you think I missed.  For example, I would feel safe hosting a server that interpreted arbitrary user-supplied Dhall code from any user, even malicious users trying to compromise the host machine.

The exact claim is that it is safe to "import and evaluate" code from untrusted users.  The most they can possibly do is waste CPU/RAM and add to the local append-only import cache if any of the imports are protected by a semantic integrity check.  In other words, the worst damage is a potential denial-of-service attack by exhausting CPU/RAM/Disk, and even that can be mitigated using control groups.

**Comment by Qix-** [comment]
> If they do so then the import is only downloaded once and then cached locally forever

My point is still being missed, it seems. If developers are told they can safely run Dhall code even from potentially malicious users, they're going to assume that they are not sacrificing privacy or internal information.

Dhall cannot guarantee that at all.

If the developer allows untrusted users to upload and run Dhall code, a malicious user can execute HTTP requests on a victim's machine's behalf.

It doesn't matter if you download the remote once, or a hundred times. The library is still making an outgoing socket connection (and more so, an HTTP request) to an untrusted, third party server.

This has the potential to leak sensitive information, and therefore is not completely "safe". The verbiage on the front page is misleading in that regard.

> I can update the phrasing of the statement to reflect this, such as: "Dhall provides support for semantic integrity checks which guarantee that …" to imply that the user may need to usedhall freeze to protect their code in this way. Would that resolve your concern for this point?

I don't see how that clarifies anything.

Also, what's a "semantic integrity check"? That's not a security term, it sounds made up. Can you explain what that entails?

> I think the most compelling argument that has been made so far is that there can be a specification bug.

Are bugs in implementations the a _very new_ standard not a compelling reason? Are you implying there is negligible surface area for zero-days or other vulnerabilities that could potentially expose an attack vector via the network import method?

Personally, I wouldn't believe _anyone_ that told me it was 100% safe. That is what the front page is implying.

> Even accounting for that, I view the risk of compromise to be so negligible that I feel confident declaring Dhall safe.

How can you even _begin_ to prove that?

> The word "safe" always requires a certain threat model and Dhall is safe within the threat model that most users assume when they read the safety claim on the website.

Obviously not, otherwise I wouldn't be here 😄 

```
You can safely import and evaluate untrusted Dhall code, even code authored by malicious users.
```

This statement is objectively untrue at face value. I don't see why this is such a point of debate. That's all I'm asking to be clarified.

> A semantic integrity check (A) permanently caches the protected impo,rt locally, foiling tracking and timing attacks

How can a "semantic integrity check" prevent a remote server from logging access information and potentially leaked request metadata from a Dhall client? Like I mentioned before, at some point you're still downloading the remote code, which involves an HTTP request to an untrusted server in the case where developers have mistakenly been told that Dhall is 100% safe, as the above statement suggests.

> making it impossible to modify even by a MITM attack over an unprotected channel or if the origin server is malicious or compromised.

I've never mentioned MITM attacks as that is obviously not a concern. That's not the point of this thread.

> let me know if you have a specific attack vector in mind that you think I missed

I did, in the two bullet points in the first post. I'll rephrase them here to be absolutely clear:

1. A malicious user can gain knowledge of my machine, my location or my application's infrastructure by crafting Dhall code that hits a remote server the malicious user controls..
2. In the event there is a vulnerability in an implementation of Dhall, an HTTP request might be used as a vector for pulling an RCE payload.

Given both of these, however likely or unlikely they may be, do not make Dhall 100% safe **as the front page seems to claim**, without any further context.

**Comment by Gabriel439** [comment]
I'll answer things out of order, since I think this first point is the most important one to address:

> Are bugs within implementations of a very new standard not a compelling reason? Are you implying there is negligible surface area for zero-days or other vulnerabilities that could potentially expose an attack vector via the network import method?

Would your concerns be resolved if I changed the statement on the page to "We commit to making the language safe to import and evaluate maliciously crafted code"?  That way instead of providing a guarantee that the language is safe we instead commit to treating the inability to safely interpret malicious code as a specification bug.

******

> This has the potential to leak sensitive information, and therefore is not completely "safe". The verbiage on the front page is misleading in that regard.

My understanding is that the only information that the attacker can exfiltrate for imports protected by semantic integrity checks is that the subject of the attack uses Dhall.  However, the attacker would already know this given that they are trying to compromise the subject using Dhall code.

Beyond that, what information do you believe that you can leak or exfiltrate through Dhall's import system?

> Also, what's a "semantic integrity check"? That's not a security term, it sounds made up. The only evidence I can find for anything remotely similar is for niche database use cases. Can you explain what that entails? Because it's going to confuse readers, which doesn't solve the problem.

This post explains Dhall's semantic integrity checks:

http://www.haskellforall.com/2017/11/semantic-integrity-checks-are-next.html

Discussing this, I realized that the "Safety guarantees" page doesn't actually define what semantic integrity checks are so I can expand the page to include a condensed summary of that post.

One thing that is missing from that post is that imports protected by semantic integrity checks are locally cached using the hash as the lookup key.  That feature was added after the post was written.

> Given both of these, however likely or unlikely they may be, do not make Dhall 100% safe as the front page seems to claim, without any further context

There is further context, though, which is the "Safety Guarantees" link immediately below the claim, which should clarify these points (and if it doesn't I can fix that).

**Comment by Gabriel439** [comment]
Here is the change to the standard to add the referential transparency check, as I mentioned above: https://github.com/dhall-lang/dhall-lang/pull/334

**Comment by sarneaud** [comment]
There's a name for this class of security vulnerability:
https://www.owasp.org/index.php/Server_Side_Request_Forgery
https://www.acunetix.com/blog/articles/server-side-request-forgery-vulnerability/

This special case is one of the OWASP Top Ten 2017 vulnerabilities: https://www.owasp.org/index.php/Top_10-2017_A4-XML_External_Entities_(XXE)

As an example, suppose someone builds a web app running on a server on AWS.  It needs to process data files uploaded by untrusted users, so it uses Dhall because

> You can safely import and evaluate untrusted Dhall code, even code authored by malicious users.

Someone uploads a file that imports from http://169.254.169.254/latest/meta-data/iam/security-credentials/role .  [That URL returns a blob of JSON](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials), so if https://github.com/dhall-lang/dhall-lang/issues/121 got implemented, Dhall could be used to steal secret credentials.

**Comment by Gabriel439** [comment]
@sarneaud: I opened an issue to discuss the security vulnerability you identified:

* [Discuss: Solutions to protect against server-side request forgery](https://github.com/dhall-lang/dhall-lang/issues/404)

**Comment by Gabriel439** [comment]
Also, related to the original discussion, I opened a pull request to change the wording around the security guarantees:

https://github.com/dhall-lang/dhall-haskell/pull/841

The current draft of the wording is:

> The language aims to support safely importing and evaluating untrusted
      Dhall code, even code authored by malicious users.  We treat the inability
      to do so as a specification bug

**Comment by Gabriel439** [comment]
I'll close this now that I've updated the claims on the website
