### ISSUE TITLE
RFC: SSH URIs

### ISSUE THREAD

**Issue by cbarrett** [dhall-lang/dhall-lang#338]
Much like you can fetch HTTP content `as Text`, it would be neat if you could fetch content via SSH. Could open up system administration automation workflows.

A rough grammar I stole from the first page search results:
 
    ssh://[username@]hostname[:port][[/]initial/remote/path]

A simple implementation could launch the ssh(1) tool, if present. (Making sure special characters are handled correctly would be important here.)

Thanks for reading 😊

**Comment by Gabriel439** [comment]
The main issue I can see is that `ssh` imports expose a broad attack surface via the large number of SSH options (i.e. everything in `man ssh_config`) and we can't lock down those options because users can add them to their `~/.ssh/config` file.

`ssh` is easier to misuse than `https` (the anti-patterns of `StrictHostKeyChecking=no` and shared private keys come to mind) and Dhall's users should trust the language designers to think carefully about security so that they don't have to.

**Comment by cbarrett** [comment]
Thanks Gabriel. What you said makes sense.
