### ISSUE TITLE
[docs] Missing reference to Union types in "Built in types, functions, and operators" wiki page

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-lang#345]
Hi, sorry if the are already documented but i cant find them in https://github.com/dhall-lang/dhall-lang/wiki/Built-in-types%2C-functions%2C-and-operators

**Comment by Gabriel439** [comment]
@jneira: "Built-in" in this case means reserved identifiers (i.e. `Natural/show`) rather than keywords (like `if`/`then`/`else` or `merge`).  That page is not an exhaustive accounting of all language features, but rather just primitive functions and operators.

You might be thinking more of the [Cheatsheet](https://github.com/dhall-lang/dhall-lang/wiki/Cheatsheet) which does strive to briefly account for all language features (although it might be out of date)

**Comment by jneira** [comment]
Oh, thanks, that is what i was looking for.
