### ISSUE TITLE
Discussion: transpile dhall to other languages in both directions?

### ISSUE THREAD

**Issue by Kinrany** [dhall-lang/dhall-lang#346]
Context: spent half a day dealing with several pages of config files in different languages.

It would be nice to be able to write all config files for a large project in Dhall, then transpile them ***at design time*** in both directions, so that they're stored as `Dockerfile`, `.travis.yml`, etc.

This way we'd be able to use the same syntax and enforce correctness without having to depend on the transpiler, other than mentioning it once in CONTRIBUTING.md

Seems related to https://github.com/dhall-lang/dhall-lang/issues/295 and https://github.com/dhall-lang/dhall-lang/issues/312

**Comment by Kinrany** [comment]
Regarding Dhall -> JSON, the IDE will have to be aware of the target language anyway, so it would only allow an appropriate subset of Dhall.

Regarding JSON -> Dhall, personally in the absence of a schema I'd expect it to always use the same general type, instead of trying to infer it from data.

**Comment by Gabriel439** [comment]
I'll narrow this down to a simpler minimal version of this problem with just two JSON files and give a dump of my thoughts on this.

So, suppose that we have two local files named `./a.json` and `./b.json`.  My understanding is that you want to edit both of them as if they were a single Dhall configuration file.  However, let's unpack what that means.

First off, we need to specify how they would be combined within this larger configuration file.  I assume that if we implemented https://github.com/dhall-lang/dhall-lang/issues/121 then you would have some top-level configuration file named `input.dhall` that might look like this:

```haskell
{ a = import ./a.json as JSON
, b = import ./b.json as JSON
}
```

Now you want some way to edit that file such that if you edit the `a` field of that top-level configuration then any edits you apply are then transformed back into edits of the original `a.json` file.

I'll assume that we want to do this in some way that doesn't require deep integration with your editor or for us to author a new custom editor just for Dhall expressions.  So here's a low-tech way to do that doesn't require anything editor-specific:

* Interpret the `input.dhall` expression and open up the final result in your editor
* Edit that to the new desired final configuration
* Save that to a file named `output.dhall`
* Run the following commands:

  ```bash
  $ dhall-to-json <<< '(./output.dhall).a > ./a.json
  $ dhall-to-json <<< '(./output.dhall).b > ./b.json
  ```

The main issue with that approach is that you have to manually maintain that post-processing logic to write back out the JSON as you add new sub-configuration files that you import into the top-level configuration.  However, if you use a consistent file and field naming convention then you could automatically convert all top-level fields within the expression you edit to JSON files of the same name.

This would start to get unwieldy as you added new configuration file formats that you need to write out.  How would you specify what output format each field is supposed to be written out as (i.e. JSON vs. YAML vs. Dockerfile vs. Text)

One solution might be to implement the output logic in Dhall (as I suggested in this comment: https://github.com/dhall-lang/dhall-lang/issues/336#issuecomment-451503204).  In other words, you implement the conversion from a Dhall expression to JSON/YAML/Dockerfile/etc. *in Dhall* so that your final result is an association list (or homogeneous map once we support that) with one key-value pair per file to write out:

```haskell
[ { path = "./a.json", text = "{ \"foo\": 1, \"bar\": true }" }
, { path = "./b.json", text = "[1, 2, 3]" }
…
]
```

Then you can select which output format you want just by choosing the appropriate rendering function in your Dhall code.

So let's assume that we then author a file named `./fileSystem.dhall` containing the desired filesystem contents.  It might look like this:

```haskell
let renderA = …

let renderB = …

in  [ { path = "./a.json", text = renderA (./output.dhall).a
    , { path = "./b.json", text = renderB (./output.dhall).b
    ]
```

Then all you need is a utility which I'll call `dhall-to-filesystem` that would read in that `./fileSystem.dhall` file and then generate all of the files listed there.

So then your updated workflow would look something like this:

* Interpret the `input.dhall` expression and open up the final result in your editor
* Edit that to the new desired final configuration
* Save that to a file named `output.dhall`
* Run the following command:

  ```bash
  $ dhall-to-filesystem <<< './fileSystem.dhall'
  ```

**Comment by Kinrany** [comment]
> My understanding is that you want to edit both of them as if they were a single Dhall configuration file.

Oh, sorry, I didn't mean that! It would be good enough to edit only one of them at a time as if they were written in Dhall.

An important detail I failed to mention explicitly is that no Dhall should be stored alongside the resulting JSON or YAML. This would allow using Dhall in scenarios where other developers do not want to use Dhall or store extra files in the repo.

In a perfect world the workflow would look like this:
* Run `$ edit-as-dhall input.json JSON`
* Edit `input.dhall` in the opened text editor
* Save and exit the editor
* Observe that the contents of `input.json` have changed

Underneath `edit-as-dhall` would have to generate a full copy of data in `input.json` for `input.dhall` instead of importing, since the main benefit is using the same syntax, not automated editing.

It seems this issue could not possibly move forward until there's a JSON -> Dhall parser. (JSON is not important by itself, just a sign that implementing parsers for other languages would be hard too.) And I'd hate to waste too much of your time on something that is more of a curiosity than an actual need 🙂

**Comment by Gabriel439** [comment]
Oh yeah, in that case it would be pretty straightforward.  You just need a `json-to-dhall` tool and then you can define a tool that calls `$EDITOR` on a transient intermediate Dhall representation.  The only issue I can foresee is that it might not work as well with IDEs that manage entire projects

**Comment by Nadrieril** [comment]
Triage: We now have `json-to-dhall`, so this workflow is now possible ! Are there any other issues left ?

**Comment by Profpatsch** [comment]
There’s also a [related Discourse thread](https://discourse.dhall-lang.org/t/have-we-solved-the-problem-of-generated-config-yet-best-practices/131)

**Comment by Gabriel439** [comment]
Yeah, I'm fairly certain that with `json-to-dhall` you could build a small script that lets you edit JSON as if it were Dhall.  I'll close this out unless somebody is interested in creating a polished version of such a script.
