### ISSUE TITLE
A C Lanugage binding via FFI (WIP)

### ISSUE THREAD

**Issue by as-capabl** [dhall-lang/dhall-lang#356]
I'm developing a C binding of Dhall via Haskell FFI.
https://github.com/as-capabl/clay-dhall

I read #2, #11, #295, and I understand that the recomended way is to implement native C interpreter.
But I use the Haskell implementation via FFI because at this moment it is the most developed one.
Conceptually it is possible to replace it with native one with same API.

In this API, host type information is passed to clay-dhall.dll through on-memory binary representation (pointer to C structure).

An example code is [here](https://github.com/as-capabl/clay-dhall/blob/master/ctest/type_simple.c)

**Comment by as-capabl** [comment]
I think I should be careful because a C binding may be used by another language. Actually I'd like to make a C++ binding based on this C binding.

If there's no problem, I'll make a PR to add this C binding to the language bindings list of this repo.

**Comment by Gabriel439** [comment]
@as-capabl: This looks great!  Thank you for working on this!

I mainly have two comments:

* The parts of the Haskell API related to customizing the interpreter (i.e. `EvaluationSettings`, etc.) might still be in flux

  If you want to reduce your maintenance burden you can stick to re-exporting only the standardized functionality since the language standard is slower moving than the full Haskell API.

* How will this be packaged?

  Probably the most common request you will get is people asking to package this for various package managers, so be careful about what you are signing yourself up for, especially since it's a C package that depends on a Haskell package.  Things will get even more complicated once you have other languages depending on this via their C FFI (i.e. a PHP depending on C depending on Haskell).

  I'm only asking just to make sure you don't overextend yourself on build/packaging issues because they can be time-consuming to address.

Either way, you can definitely add this as a listed language binding in the `README` for this repository.

**Comment by Gabriel439** [comment]
I have a pull request up to mention `clay-dhall` here: https://github.com/dhall-lang/dhall-lang/pull/361
