### ISSUE TITLE
Scope of built in functions?

### ISSUE THREAD

**Issue by JamesGuthrie** [dhall-lang/dhall-lang#364]
There are a few Hashing/Encryption/Text processing built in functions that I would really appreciate having in Dhall.

I've read the wiki article on [How to add a new built in function](https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function), and while I appreciate that it's possible to add built ins to my own fork, that doesn't seem like a good long-term solution.

This leaves me wondering what  Dhall's "vision" on built ins is. Is the intention that there will be many more built ins, covering a large surface area, and that contribution to built ins is welcomed? Or should we be conservative with built ins and err on the side of trying to do certain processing outside of Dhall?

To provide you with some context, I would like to be able to do things like:
- calculate the sha(x)sum of an input value
- en/decrypt an input value with a symmetric cipher
- truncate a text field to a set length

I could imagine that text truncation would be a "sensible" built-in, but that something like supporting symmetric en/decryption could be way out of scope.

Could you maybe share your thoughts on this topic? It might be helpful if they could be added to the wiki document as well, to answer the question for future visitors.

**Comment by Gabriel439** [comment]
@JamesGuthrie: The set of built-ins is intended to be minimal.  The reason why is that Dhall needs to be ported to many programming languages and new built-ins increase the difficulty of porting the language and (depending on the built-in) might increase the required dependencies of packages that provide Dhall bindings.  For example, standardizing built-in support for symmetric ciphers would entail that all bindings would need to depend on a cryptography library.

The initial scope for Dhall is as a configuration language that will hopefully slowly displace YAML, so most new built-ins that will be whitelisted for inclusion will be intended for that purpose or they will be general-purpose data-transformation functions.  That doesn't imply that Dhall will never be used for another purpose, but focusing on that initial use case will help us conserve our resources so that the language can gain traction.

So that would probably rule out hashes and symmetric ciphers but not necessarily text truncation.  As far as I can tell, none of our prior guidelines really says anything about whether a built-in for text truncation should be allowed.  The closest guideline I have is an informal policy of discouraging built-ins that permit parsing or introspection of text values, but truncation doesn't fall into that category.  We would mainly need to discuss if the text truncation built-in might enhance the initial use case of being a configuration language.

Either way, my understanding is that the main gist of your request is document the policy for which built-ins get whitelisted, so I can add something similar to what I've just written to the Wiki (either as part of the current page on custom built-ins or as part of a separate page).

**Comment by FintanH** [comment]
@Gabriel439 Wouldn't any dhall implementation need to have some sort of crypto dependency to get hashing for the cache part of the implementation? Or am I wrong in thinking this?

**Comment by Gabriel439** [comment]
@FintanH: Yes, that's correct! 🙂

**Comment by JamesGuthrie** [comment]
@Gabriel439 Thanks for the detailed answer. I guess that while my initial request was for documentation of the policy on built ins, perhaps a follow-on question is what is the vision for dhall <-> host language interop? I've only really had exposure to dhall-to-yaml until now, so I really don't know what the interop looks like. Is the idea that more complex transformations would take place in the host language? Or in other tooling which does a postprocessing pass over the dhall output?

I understand the need to focus on a small niche in order to gain traction, and YAML is definitely a good place to be, but what I'm kind of missing is an overview of the types of tools that people are using on the full pipeline of "this is in my repo"  -> "my configuration/application is deployed" and how they all would/could fit together. As I see it Dhall only really plays a small role in this pipeline, so what are people using to do the rest? Mostly the host language (Haskell and Clojure?), or other tooling which mangles/wrangles the yaml which Dhall produces?

**Comment by Gabriel439** [comment]
@JamesGuthrie: `dhall-to-yaml` is basically a temporary solution until more language bindings are available.  The ideal solution is that your language has a package that implements the Dhall interpreter.  You can get a feel for how this would be used like by reading the tutorial for the Haskell bindings to Dhall:

https://hackage.haskell.org/package/dhall/docs/Dhall-Tutorial.html

Basically, once you have a native language binding then the program you deploy can read in and interpret Dhall expressions directly instead of having to delegate that task to a separate `dhall-to-yaml` process.

However, customizing the language with built-ins is not covered by the language standard.  The Haskell API provides support for this sort of customization, but other language bindings might not.

**Comment by Gabriel439** [comment]
I also added a small section on the guidelines for new built-ins at the bottom of this page: https://github.com/dhall-lang/dhall-lang/wiki/How-to-add-a-new-built-in-function

**Comment by sjakobi** [comment]
The idea of built-in support for hashing is being tracked at https://github.com/dhall-lang/dhall-lang/issues/739.

Is there more that should be discussed here or can this issue be closed?

**Comment by sjakobi** [comment]
Closing. Please reopen if I've missed something!
