### ISSUE TITLE
Should we handle reserved names in the grammar ?

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#394]
The parsing of reserved identifiers (like `Bool` and `Natural/even`) adds quite a bit of complexity to the grammar (see https://github.com/dhall-lang/dhall-lang/blob/9203c77/standard/dhall.abnf#L722-L729), and generally feels awkward to me.
I propose to remove this special-casing and instead recognize builtins after parsing. This would simplify the grammar noticeably, and make adding builtins more flexible.

This also opens a new option: allowing builtin names as bound variables. Currently, adding a new builtin can break existing code. For example, if we introduce a new `Map` builtin type, any code that uses `Map` as an identifier, like `let Map = ... in ...`, breaks. This would be the first step towards avoiding that.

Does that sound legit ? I'm currently working on a new implementation of dhall and this is a small pain point I've come across.

**Comment by Gabriel439** [comment]
@Nadrieril: This is possible, but it would require a change to the normalization judgment to thread through a context, similar to type-checking.  The reason why is that you have to correctly handle bound variables shadowing built-ins.

For example, suppose that you normalize:

```haskell
λ(Natural/even : Natural → Bool) → Natural/even True
```

The β-normalization judgment would need to keep track of the fact that `Natural/even` has been shadowed by the bound variable so that normalization doesn't use the built-in `Natural/even`.

So a judgment like:

```
f ⇥ Natural/odd   a ⇥ 0
───────────────────────
f a ⇥ False
```

... would have to change to something like:

```
Γ ⊢ f ⇥ Natural/odd   Γ ⊢ a ⇥ 0
──────────────────────────────── ; Natural/odd ∉ Γ
Γ ⊢ f a ⇥ False
```

In fact, the Haskell implementation's support for custom built-ins is actually vulnerable to this same issue, but few people notice because they avoid naming identifiers after their own built-ins.

**Comment by Nadrieril** [comment]
That sounds like a lot of work. Could we not instead start normalization by doing a few substitutions like `x[Natural/even := built-in:Natural/even]`, which already knows how to avoid bound variables ? I don't know where that would fit in the spec though.

**Comment by f-f** [comment]
There was a discussion about this in #314 and, as I mentioned there, the reason why I'd not like to have shadowing for builtins are that:
- it would complect normalization as Gabriel mentioned above
- it's unintuitive how it would work with imports and self-contained expressions, i.e. shadowing builtins in one expression doesn't propagate to imports - I describe an example of this in https://github.com/dhall-lang/dhall-lang/issues/314#issuecomment-445468966

The usecase "adding a builtin would not break code" is a good one, but I'm not sure it would be so common in the future - as I don't expect we'd add many more builtins at this point

However, I'd agree with removing the special rules for builtins in the grammar and parsing everything as a `simple-label`, and then distinguishing the builtins in a successive step.
That would quite simplify the grammar (but we'd have to keep a list of builtins somewhere in the standard)
I did introduce these rules myself in my very first PR here (https://github.com/dhall-lang/dhall-lang/pull/122), because:
1. there was already a rule for reserved words, so I assumed we wanted such a thing, and I just expanded it
2. I had the vision of handling the parsing holistically in the grammar. It turns out this is quite not possible, and sometimes it goes against the goal of removing ambiguity in the grammar, which is the thing we should strive for.
  And the reason why I wished the parsing to be handled fully by the grammar was that dealing with the grammar and the standard felt a bit overwhelming when I was starting out, so having some "self-containment" was helpful 🙂

**Comment by Nadrieril** [comment]
I'd be happy to try a PR, but is there a test suite for the grammar spec somewhere, so I don't break things ?

**Comment by f-f** [comment]
@Nadrieril there is a sanity check (think ABNF compliance) running in CI, but nothing more than that.
Since my Clojure implementation is based on the grammar I can try out the new grammar from your PR and check that everything is fine!

**Comment by Nadrieril** [comment]
Ok thanks !

**Comment by Nadrieril** [comment]
I'm not sure where in the spec I should specify that builtins are disallowed as bound variables, and that they should be recognized in identifiers ? I was thinking a comment in the grammar file, but there could be a better place somewhere around semantics.md
