### ISSUE TITLE
Wiki page on intentional non-features?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#401]
As one dives into Dhall there is some lore about in issues, etc, around features that have been intentionally left out of the language for various reason (`==` on `Text`, or any string manipulation at all, arithmetic on anything but `Natural`, etc).  It would be nice to document these in a single place that is easy for new people to find so we don't immediately start suggesting things that are not desired, and so we can understand the reasons these features have been left out so far.

**Comment by singpolyma** [comment]
First stab here: https://github.com/dhall-lang/dhall-lang/wiki/Design-Choices

**Comment by Gabriel439** [comment]
@singpolyma: I'll expand the introduction a bit if it's alright, mainly to clarify that nothing is set in stone and that we're open to changing our minds

**Comment by Gabriel439** [comment]
Also, one thing to note is that the true reason for many absent operators was because when I first designed the language I tried to only include associative operators purely due to a mathematical aesthetic (which partly originated from [this post](http://www.haskellforall.com/2015/09/how-to-make-your-haskell-code-more.html)).  However, in my experience (using Haskell) mathematical aesthetics sometimes end up converging with practical concerns.

For example, this is why `==` only works on `Bool` because associativity requires that the result type of the operator is the same as the two argument types.  Same thing for `/=`.  The fact that restricting these two operators also tends to promote strong typing is a bonus (again, aesthetics converging with practical concerns), but I would be misleading people if I claimed that strong typing was the true original motivation.

**Comment by Gabriel439** [comment]
Alright, I expanded the page a bit more with the design choices that I could remember.  I can continue to expand it later as I remember more of them, but I think it's pretty good for now

**Comment by philandstuff** [comment]
Looks really good so far! I made a couple of copy edits. 

On the subject of maps/dictionaries: I think the wiki page is correct as it stands, but if the reader comes from a dynamic language and/or YAML configuration background, I think they might not realise the subtle difference between homogeneous and heterogeneous maps. The page says “no maps” but I think more precisely it means “no homogeneous maps”, given its reasoning. 

The reason for not having heterogeneous maps is that they are not type safe and you should use records instead. I think this point might be worth including (even if it’s obvious to Haskellers).

**Comment by singpolyma** [comment]
I'm not sure most dynamic language devs will even understand why it says "no maps" since records looks a lot like maps.

**Comment by Gabriel439** [comment]
As I was expanding on the maps/dictionaries section I realized that Dhall actually *could* support homogeneous maps and opened https://github.com/dhall-lang/dhall-lang/issues/557 with my thoughts on this.
