### ISSUE TITLE
discourse.dhall-lang.org?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#410]
Is it time we set up Discourse or something for broader discussions? I know we've been using the issue system for this, but I wonder if a discussion platform might be better suited. For example, I'm loosely exploring Terraform+Dhall, and it'd be nice to speak about that more in the open (rather than either here, or https://github.com/etaty).

What do people think?

**Comment by ocharles** [comment]
https://groups.google.com/forum/#!msg/nix-devel/rosQdK40mas/7D7rHIFdCgAJ points to https://gist.github.com/teozkr/ae017b89d4a0179ec211757aa92ff3a1 which is a NixOS module for Discourse.

**Comment by Gabriel439** [comment]
@ocharles: Yeah, I can try to set up a `discourse.dhall-lang.org` this weekend

**Comment by Gabriel439** [comment]
The Dhall Discourse is up now: https://discourse.dhall-lang.org/

I initially also added @f-f and @ocharles as moderators.  I'll apply the same guidelines for moderation that I do for granting the commit bit: you're welcome to ask and I may make people moderator anyway without them asking

The only thing I haven't figured out yet is how to fix this issue:

<img width="359" alt="Screen Shot 2019-03-10 at 5 55 58 PM" src="https://user-images.githubusercontent.com/1313787/54094397-cce3a000-435d-11e9-8c11-adbfda5f495d.png">

... because I'm not sure where the insecure content is originating from.  If anybody knows how to debug this then let me know

Other than that, I'm marking this issue resolved.

**Comment by Gabriel439** [comment]
Also, here is the matching pull request containing the relevant NixOps changes: https://github.com/dhall-lang/dhall-lang/pull/417

**Comment by Gabriel439** [comment]
Also, sorry for any "Bad Gateway" issues you might run into when trying out `discourse.dhall-lang.org`.  Restarting the Discourse server takes quite a while whenever I do a redeploy and I'm still not sure how to minimize unnecessary restarts when redeploying the server

**Comment by ocharles** [comment]
Thanks, works great!

**Comment by f-f** [comment]
Thanks @Gabriel439!

**Comment by Gabriel439** [comment]
Sorry, everybody, but I accidentally wiped the Discourse history when doing maintenance on it, so all prior discussion is gone and people will have to create new accounts.

The root of the problem was that I cloned the discourse repository into `/var/discourse`, which is the same directory it was using for data storage (including backups).  When I removed the repository to clone again it removed the history and backups.
