### ISSUE TITLE
Optional as Union?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#421]
This is continuing the discussion that started as https://github.com/dhall-lang/dhall-lang/pull/416#discussion_r264879605

My proposal would be to drop `Optional` from the language entirely, and use the form `< Some: T | None: {} >`  For example, `List/head` would now have a type like: `x:Type -> List x -> < Some x | None: {} >`

https://github.com/dhall-lang/dhall-lang/issues/224#issuecomment-416287647 says the motivation for special casing `Optional` is to make the JSON/YAML translators easier to write.  I am sympathetic to this, but I feel there are two possible solutions that do not require a special case:

* Encode any value like: `< Tag = {=} | ... >` as `null`
* Special case the label "None" in the JSON/YAML translator to encode any value like: `< None = {=} | ... >` as `null`

In either of these cases other union tags simply being stripped (as is done for json/yaml now) is sufficient, so only none needs to be handled in some way.

Migration path could be to first make `None` and `Some` built-ins that produce values of these types, then drop them and provide a type synonym in Prelude.

**Comment by Gabriel439** [comment]
@singpolyma: To clarify https://github.com/dhall-lang/dhall-lang/issues/224#issuecomment-416287647, what I meant was: many languages and configuration formats have built-in support for null, so Dhall should provide a built-in way of modeling null that is more ergonomic than a generic sum type (same thing for boolean values).  The intention was not to make integrations easier to implement, but rather for Dhall to built-in niceties for supporting commonly used configuration idioms (like null/bool)

That's one of the reasons that I'd prefer not to use a generic sum type to encode `Optional`, because it would make specifying `Optional` values much more verbose.  For example, one of the reasons that users requested to switch from the old list-like syntax to the `Some`/`None` syntax was because `Optional` is so heavily used in configuration formats that it needs to be very ergonomic.  Switching to the use of generic sum types to model `Optional` would be a step backwards and most likely lead to a large number of users to abandon the language, or at least stop upgrading.

**Comment by singpolyma** [comment]
Right, to get `Optional.Some 1` style syntax would require an import or `let`, which is probably too much if prelude wasn't going to be imported in a certain Dhall program for other reasons.

What if `Some`/`None`/`Optional` were all built-ins (so, no import required) basically like now but instead of representing themselves, had a normal form of a union type?  That would still reduce special handling (adding builtins is pretty light on its own) and also allow optionals to be used with union operators, etc.

**Comment by Gabriel439** [comment]
@singpolyma: Yeah, I like that!

As far as I can tell, the main downside is more verbose normal forms.  The main upside is that `merge` would work on `Optional` values and it simplifies the standard.

Note that if we were to do this then we would need to standardize https://github.com/dhall-lang/dhall-lang/issues/224 first so that `None` can be represented as an empty alternative (i.e. `< Some : T | None >`

Another thing to keep in mind is that if we go down that route then for consistency we would probably want to do the same thing for `Bool` (i.e. `Bool = < False | True >`), which would also mean more verbose normal forms (i.e. the normal form of `True` would be `< False | True >.True`).

One way to address the verbose normal forms would be to add `dhall lint` support for rewriting the fully-expanded `Optional`/`Bool` union literals/types to use the built-in shorthands.  Then if you wanted to make the normal form more readable you can filter it through `dhall lint`

**Comment by singpolyma** [comment]
I'm not sure we *need* #224 since alternatives with no fields are possible now (just a bit more verbose) -- but if that is going to go in anyway I agree it makes sense to wait for it :)

**Comment by Gabriel439** [comment]
@singpolyma: Yes #224 will go in once I get to it (any day now 🙂 )

**Comment by Profpatsch** [comment]
> which would also mean more verbose normal forms (i.e. the normal form of `True` would be `< False | True >.True`).

While we’re at it we should also represent Naturals as Peano numerals ;)

**Comment by Nadrieril** [comment]
I am not in favor of this. I think that first-class support for Optional and Bool makes the language feel polished and replacing their normal forms with lesser-known forms would look unwieldy for newcomers that expect something familiar-looking at least for the basic constructs. I view sum types as somewhat more advanced than maps/Bool/strings/Optional, and I think the language should reflect that.

**Comment by Gabriel439** [comment]
@Nadrieril: Another possibility would be to leave them as is and overload `merge` to work on `Optional` and `Bool` as if they were sum types

**Comment by Nadrieril** [comment]
I just noticed an interesting detail: `Some` is weirdly special. If it were just a function, we would need to write `Some Natural 1`, or if it was any other union, `(Optional Natural).Some 1`. Instead, `Some 1` is allowed for convenience. It's closer to the list literal syntax than a builtin function in that way.

**Comment by Gabriel439** [comment]
@Nadrieril: Yes, that ability of `Some` to take advantage of type inference is one of the big reasons we switched from the old list-like syntax to `Some`/`None`

**Comment by Nadrieril** [comment]
It makes sense but is quite surprising. In particular, this means that we can't allow `Some` by itself without inviting weird behaviors like `(Some) Natural 1` and `(Some Natural) 1` being different expressions.

**Comment by Gabriel439** [comment]
@Nadrieril: I view `Some` as similar to `merge`.  They are both keywords, but `Some` just happens to be capitalized to resemble the naming convention of a function (so that it doesn't look weird side-by-side with `None`, which is a genuine function).  So you can't write `(Some) 1` for the same reason you can't write `(merge) x y`

**Comment by Nadrieril** [comment]
@Gabriel439 Now that I'm familiar with the standard I understand why this is the case, but when I started using the language I had no idea these were special. I just don't find that the language clearly conveys their specialness, but I'm not sure if we can do anything about that.

**Comment by philandstuff** [comment]
The language has changed a lot since this issue was raised. In particular, you can now `merge` `Optional`s as if they were unions. 

Does anyone want this issue to stay open? If so, it’s worth precisely expressing what “done” would mean for this issue.

**Comment by Gabriel439** [comment]
I think this is essentially done after #463 was merged
