### ISSUE TITLE
Expression for the Type/Kind of Record Type/Kind

### ISSUE THREAD

**Issue by dingxiangfei2009** [dhall-lang/dhall-lang#434]
This is a question issue on whether we can express the set of Types/Kinds, consisting of records containing a given set of fields of a fixed type.

It is tempting for one to try defining such a set of records, for example, having a field `key : Text`.
For instance, one might try the following:
```
\(T : { ... <but what do we put here?> })
-> \(record : { key : Text } //\\ T)
-> ...
```
Is there a way to express this constraint in the current language?

**Comment by Gabriel439** [comment]
@dingxiangfei2009: Currently, no.  Dhall does not yet have support for row types like PureScript does, which would allow abstracting over record-like types.  If you had that then the type of `T` would be `Row` and the code would probably look something like this:

```
    \(T : Row)
->  \(record : { key : Text, T }
-> ...
```

I think it is possible to add support for something like this, it just takes time to standardize and implement.

**Comment by sellout** [comment]
This looks like you want an open record type, but there’s no support for something like that in Dhall. I don’t know if there’s any plan for it, but I would also find it helpful. Currently I use a bunch of extractors, which often need richer expressions, but could be handled in your example with `record.{ key }`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gabriel439** [comment]
@sellout: Note that abstracting over a type `T` of type `Row` is equivalent to an open record type.  In other words, think of this:

```haskell
    \(r : Row)
->  \(record : { key : Text, r }
-> ...
```

... as being equivalent to this PureScript type:

```
forall r . { key :: Text | r }
```

... where `r` is playing the role of the polymorphic placeholder for "the rest of the fields".  The main difference is that in Dhall the row abstraction/application is explicit

**Comment by sellout** [comment]
Yeah, I want this to happen, but I have a couple questions/concerns

1. is `{ key : Text, r }` meant to be like `r /// { key : Text }`? (assuming `///` is a type-level version of the `//` combine operator) If so, I think that the combine operator would be the right syntax for this, for consistency.
2. `Row` is now a sub-Kind of `Type`, correct? Does that introduce the same issues that having sub-Types would, or is it restricted enough that it’s not a problem.

Open records would be amazing for me, and I don’t see a different way to handle them, but I want to be careful about shifting complexity from my Dhall code into the language bindings.

**Comment by jvanbruegge** [comment]
@sellout 
1. It depends on the implementation semantics of the rows. The version I am implementing in haskell would be more similar to `:` (list cons) as it allows duplicated labels to make Lack constraints on the original row optional. But given dhalls narrower scope other semantics could be possible.
2. No, Row is a new kind. The way to use it on value level is to have type constructors of kind `Row Type -> Type`, ie Records and Variants

**Comment by sellout** [comment]
@jvanbruegge 

1. That sounds like more of an implementation detail – like, couldn’t a `///` operator also be implemented with cons?

2. So `{ x : Bool, y : Natural } : Row`, but _not_ `{ x : Bool, y : Natural } : Type`? I feel like that would break a lot of Dhall I write, but I’m probably just missing something. And I assume you mean “type constructors of kind `Row -> Type`”, but how would I define one of those?

**Comment by Gabriel439** [comment]
@sellout: As far as I know, nobody has proposed a syntax for a `Row` type, yet, but I'm pretty sure that it will not be `{ x : Bool, y : Natural }` (which will be a `Type` and not a `Row`).  The syntax for a `Row` might end up being something like `( x : Bool, y : Natural )`

**Comment by jvanbruegge** [comment]
Yeah, like @Gabriel439 said
In Purescript, `{ x :: Bool }` is just syntax sugar for `Record ( x :: Bool )` with the row being a phantom type on the type constructor `Record`. In Dhall, `Record` and `Variant` would be builtin.

You can't use cons directly because `(a :: A, b :: B) ~ (b :: B, a :: A)`, the point why I mentioned cons is the case when the row already contains a label multiple times. `(a :: A, a :: B) /~ (a :: B, a :: A)`. I have no idea if this has any use in Dhall, but requiring uniqueness of keys would need some sort of lack constraint and at least AFAIK dhall does not have any constraints at all

**Comment by jvanbruegge** [comment]
@sellout to take your example directly:
`{ x : Bool, y : Natural } : Record ( x : Bool, y : Natural )`

**Comment by Gabriel439** [comment]
@sellout: There is some ambiguity about what you meant by using the same operator as the syntax for specifying an open record.  There are a few ways to interpret what you meant by that and I'll try to address those interpretations.

For simplicity, let's assume that we don't support field override and we consider the `⩓` operator since it already exists for type-level merging of records.

The first way to interpret what you meant is to use that operator to separate the row type from the explicit field/type pairs:

```haskell
  λ(T : Row)
→ λ(record : { key : Text ⩓ T }
→ …
```

... but that leads to an ambiguous parse since it could be interpreted as:

```haskell
  λ(T : Row)
→ λ(record : { key : (Text ⩓ T) }
→ …
```

.... i.e. misinterpreted as `key` as having the type `Text ⩓ T`.  I don't think that's what you meant but I'm just listing that interpretation for completeness.

Another way to interpret what you said is that you want this:

```haskell
  λ(T : Row)
→ λ(record : { key : Text } ⩓ T)
→ …
```

... but that is not well-typed since `⩓` expects a `Type` as its right argument, not a `Row`.  However, something close to that would work, which is:

```haskell
  λ(T : Row)
→ λ(record : { key : Text } ⩓ { T })
→ …
```

... or (using the `Record : Row → Type` constructor like @jvanbruegge suggested):

```haskell
  λ(T : Row)
→ λ(record : { key : Text } ⩓ Record T)
→ …
```

... although it would be more verbose than just `{ key : Text, T }`

**Comment by dingxiangfei2009** [comment]
@Gabriel439 this might sound dumb: what is the contribution guideline for dhall-lang?

**Comment by f-f** [comment]
@dingxiangfei2009 [this document](https://github.com/dhall-lang/dhall-lang/blob/master/.github/CONTRIBUTING.md) specifies some contribution guidelines like how to make changes, how they get approved, etc.

**Comment by sellout** [comment]
@jvanbruegge / @Gabriel439 – Thanks. All that explanation helped a lot.

I feel like row types would simplify a ton of my code.

**Comment by dingxiangfei2009** [comment]
@Gabriel439 @jvanbruegge I have a question about this object `Row`. Which level of universe does it belong to? I feel like it can be a member of `Type` or `Kind`, depending on if it is "extending" a record type or a record kind. Because of this difference, it is necessary to mark the universe level on `Row`.

**Comment by sellout** [comment]
I have a branch (two actually) with universe polymorphism, but I haven’t been happy with it yet. I feel like it introduces too much noise, new keywords, and complexity to the implementation. But it seems like `Row` could require exposing levels to the user, although perhaps less pervasively than full universe polymorphism. Definitely a problem I’d like to see solved.

**Comment by dingxiangfei2009** [comment]
I would like to see that in Dhall, too. I was thinking about specializing `Row` into `RowType` and `RowKind`, since we can only express terms in these two universes in current Dhall anyway, but specializing `Row` in this way might not scale.

**Comment by dingxiangfei2009** [comment]
@sellout Do you think it is better to wait for universal polymorphism, or using `RowType`/`RowKind` first?

**Comment by Gabriel439** [comment]
@dingxiangfei2009: What about `Row Type` and `Row Kind` (i.e. parametrize `Row` on the corresponding universe)?  Then it generalizes to additional universe levels (i.e. `Row Sort` or `Row (Type n)`, etc.)

**Comment by sellout** [comment]
@Gabriel439 Yeah, I think that sounds like the right way to go.

**Comment by dingxiangfei2009** [comment]
@Gabriel439 That looks good! I am giving this syntax a try.

**Comment by philandstuff** [comment]
I believe that we decided to go down a different route (in #499), so I'm closing this issue.  Feel free to reopen if I got this wrong.
