### ISSUE TITLE
Embedding arbitrary structures into Dhall values

### ISSUE THREAD

**Issue by dingxiangfei2009** [dhall-lang/dhall-lang#435]
This is a feature request. It might be helpful to have a way to expression imports of external structures, such as JSON or YAML files, and embed it in the Dhall values. This type does not support extraction of values out of it, nor encoding any schema. Its interpretation is defined by the downstream serializers.

**Comment by Gabriel439** [comment]
I've thought about adding support for pluggable imports where the parser for the import type was written in Dhall.  The two main issues with this that I've run into are:

* Dhall currently does not support `Text` introspection/manipulation

  This is potentially fixable by either (A) adding support for `Text` manipulation or (B) only adding support for `Text` parsing in the context of importing a custom format

* Dhall does not support `do` notation like Haskell

  ... which means that even if Dhall did support `Text` manipulation it would be a bit clumsy to author custom Dhall parsers compared to, say, Haskell's monadic parser combinators

Another possible approach would be for `dhall` to allow delegating that functionality to external processes instead of implementing them within the language.  However, that's less optimal because you then depend on another language's packaging tools when it would be nicer to depend solely on Dhall's import system to fetch necessary dependencies.

A third approach is to built-in language support for certain format types.  For example, there is a discussion about adding support for importing `JSON` specifically here: https://github.com/dhall-lang/dhall-lang/issues/121.  I think that is the most likely way the language will evolve

**Comment by Gabriel439** [comment]
I will close this out in favor of #121 since I'm pretty certain we'll have to solve the same problem for that issue
