### ISSUE TITLE
Quoted path segments lost in binary encoding

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#456]
```
$ echo 'https://hai.com/"a b"/c' | dhall encode | rq -c

[
  24,
  null,
  0,
  1,
  null,
  "hai.com",
  "a b",
  "c",
  null
]
```

The semantics of a URL import say that quoted segments should be URI-escapes before resolving.  However, the binary encoding does not differentiate between quoted and unquoted path segments but *also* no part of the standard specifies that this encoding should happen at any point before import resolution and so the binary encoding contains unescaped segments.

If you wonder why one cannot simply run escaping over all segments the reason is this:

```
$ echo 'https://hai.com/a%20b/c' | dhall encode | rq -c
[
  24,
  null,
  0,
  1,
  null,
  "hai.com",
  "a%20b",
  "c",
  null
]
```

Blindly escaping all segments can result in double-escaping since unquoted segments are also not specified to be decoded.  Finally, this case:

$ echo 'https://hai.com/"a%20b"/c' | dhall encode | rq -c
[
  24,
  null,
  0,
  1,
  null,
  "hai.com",
  "a%20b",
  "c",
  null
]

Which has an identical binary encoding to the previous case, even though I believe that the final import should be for `https://hai.com/a%2F20b/c`

## Proposal

I propose that quoted path components be considered a part of the syntax and resolved in the parse phase just as multiline string indent-stripping is.  This would mean that

    https://hai.com/"a b"/c

would ultimately parse as

    https://hai.com/a%20b/c

and binary encode as:

```
[
  24,
  null,
  0,
  1,
  null,
  "hai.com",
  "a%20b",
  "c",
  null
]
```

And then the import semantics can remove the bit about encoding, since everything will be properly encoded by that point.

**Comment by Gabriel439** [comment]
I don't believe the binary encoding needs to distinguish between quoted and unquoted path components, for the same reason that we do not distinguish between quoted and unquoted labels and also the same reason that we do not distinguish between single-line and multi-line strings.

Expanding upon the analogy to simple labels: in the Haskell implementation even the syntax tree doesn't distinguish between quoted and unquoted labels and the only time they are treated differently is when pretty-printing.  The implementation checks renders the label unquoted if it would be valid to do so and otherwise renders the label quoted.

This means that if you pretty-print a quoted label the pretty printer will drop the quotes if they are not necessary, like this:

```bash
$ dhall format <<< 'let `x` = 1 in `x`'
let x = 1 in x
```

... and I think that is a good thing.  It simplifies the internal implementation and leads to nice emergent properties like the formatter being opinionated about how labels are quoted.

The Haskell implementation also treats double-quoted vs. multi-line strings the exact same way.  Under the hood they are represented by the exact same representation (text chunks separated by interpolated expressions) and the only time they are treated differently is when pretty printing.  If the string contains newlines then the pretty-printer uses the multi-line representation, otherwise the double-quoted representation.

Continuing both analogy: quoted labels are binary-encoded the same as unquoted labels and multi-line strings are binary-encoded the same as double-quoted strings.

I believe we should treat quoted path components the same way, meaning that they are represented the same as unquoted path components under the hood and are also binary-encoded the same way.  They are only treated differently for the purpose of pretty-printing the expression.

**Comment by singpolyma** [comment]
> I believe we should treat quoted path components the same way, meaning that they are represented the same as unquoted path components under the hood and are also binary-encoded the same way. They are only treated differently for the purpose of pretty-printing the expression.

I agree, hence my proposal to treat them like multiline strings‎ and encode them in the binary as though they were originally unquoted (and thus escaped).

**Comment by Nadrieril** [comment]
I believe we agree that `'https://hai.com/"a b"/c'` and `'https://hai.com/a%20b/c'` should have the same internal representation (and thus same binary encoding). This is not currently the case as per the standard.

The options seem to be:
- parsing the escape sequence and representing it as a space in the binary encoding, or
- doing the opposite and storing the escape sequence in the binary encoding.

Either option implies that the dhall standard should know how to handle the full range of URL (un)escapes.
For uniformity with quoted labels and such, I'd side with @Gabriel439 and prefer the first option.

**Comment by Gabriel439** [comment]
Yeah, I would support un-escaping unquoted path components of URLs so that the quoted path component without URL escapes was the canonical representation for all path components

**Comment by singpolyma** [comment]
> Yeah, I would support un-escaping unquoted path components of URLs so that the quoted path component without URL escapes was the canonical representation for all path components

This alternative is fine with me and solves the problem just as well :)‎
