### ISSUE TITLE
Dhall expression with multiple valid values

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-lang#496]
This is a weird edge case, but I think I have constructed a dhall expression which the standard allows to resolve/normalize to two different values.

Imagine the following three dhall files:

```
-- top.dhall
{ a = ./a.dhall, b = ./b.dhall }
-- a.dhall
./b.dhall ? "foo"
-- b.dhall
./a.dhall ? "bar"
```

If I run top.dhall through dhall-haskell 1.19.1, I get the output
```
{ a = "bar", b = "bar" }
```
I *think* this is correct according to the standard, but I think that this would be equally correct:
```
{ a = "foo", b = "foo" }
```

(In fact, if you change top.dhall to:
```
{ a = ./b.dhall, b = ./a.dhall }
```
you get this result.)

The important factors here are:

 - the same canonical path, when imported multiple times from different paths, *must* resolve to the same thing (so it makes sense that they are both "foo" or both "bar")
 - we have carefully crafted `a.dhall` so that its value depends on the path via which it was imported:
   - if its import parents are [`top.dhall`], it has value `"bar"`
   - if its parents are [`top.dhall`,`b.dhall`], it has value `"foo"`
   - this works because we use the import alternative operator `?` to catch the import cycle error, but where in the cycle we catch it depends on the path we took to get there.

So: the implementation needs to pick which path it first takes to get to `a.dhall`. Having done so, this fixes the value of `a.dhall`, which must then be used when it's resolved via a different path.

Is this a bug in the standard? If so, what's the right fix? My first instinct is to make import cycle errors uncatchable by the `?` operator? (My zeroth instinct is "meh, this probably won't come up in real life and is just a curiosity.")

**Comment by singpolyma** [comment]
Hmm. I suppose that technically the standard does not specify an order.  However, if you were to assume that the normalization rules form the model against which resolution should happen, then the order would be left-to-right, which seems like the correct behaviour to specify.

**Comment by Gabriel439** [comment]
Yeah, the standard omits the order for several rules (mainly due to laziness on my part), but if there were such a rule for records, it would be something like:

```
(Δ, here) × Γ₀ ⊢ x₀ ⇒ x₁ ⊢ Γ₁   (Δ, here) × Γ₁ ⊢ { xs₀… } ⇒ { xs₁… } ⊢ Γ₂
──────────────────────────────────────────────────────────────────────────
(Δ, here) × Γ₀ ⊢ { x = t₀, xs₀… } ⇒ { x = t₁, xs₁… } ⊢ Γ₂
```

In other words, in the syntactic order in which the fields were specified.  So if we were to explicitly specify that in the standard then the correct output would be:

```haskell
{ a = "bar", b = "bar" }
```

Also note that import resolution precedes β-normalization, which is responsible for sorting fields, so if you were to swap the order of the two fields then you would get the opposite result.

This would make an excellent test case to add to the import resolution test suite.

**Comment by philandstuff** [comment]
Thanks. I can add a test case.
 
I have concerns about specifying an order, mainly in that if there is an order specified it gets harder to parallelise import resolution (for performance) and still maintain correctness. In this example, imagine that these are all remote imports, and that `a.dhall` goes through a chain of 3 or 4 imports before getting to `b.dhall`. This means that, in order to be correct, we can fetch `b.dhall` but we can’t resolve its content until we’ve gone through the whole `a.dhall` import chain. I suppose as long as we’re just fetching and parsing the expression, that’s safe to do in parallel?

(Aside: import resolution is a place where I’ve got stuck implementing dhall-golang. It seems like one of the more complicated and incomprehensible parts of the standard, and even when I crib ideas from dhall-haskell or dhall-ruby, I find the code difficult to follow. I implemented environment variables and `missing` quickly but then hit a brick wall. Does anybody have any implementation advice?)

(Aside2: what is `missing` even for? I don’t get it, and it’s not mentioned in Dhall.Tutorial so I don’t know where I’d go to find it’s motivation other than spelunking the issues)

**Comment by f-f** [comment]
> Aside2: what is missing even for? I don’t get it, and it’s not mentioned in Dhall.Tutorial so I don’t know where I’d go to find it’s motivation other than spelunking the issues

@philandstuff The `missing` comes from the original proposal for the `?` operator in https://github.com/dhall-lang/dhall-lang/issues/163, and it's meant to serve as the identity for that operator:

```hs
missing ? e = e

e ? missing = e
```

**Comment by Nadrieril** [comment]
I don't like to depend on the order of fields: I'd like for implementations to be able to use any map representation that makes sense; forcing to preserve order forces implementors to use unconventional map structures. For example, in Javascript maps are very first-class, but imposing to keep declaration order would mean that the only way would be to encode the map as a list of pairs or something similar.

**Comment by ocharles** [comment]
Another option is to simply identify the potential cycle earlier and fail. Given that there is no canonical value, I feel that this is ambiguous and should just be out right rejected.

**Comment by f-f** [comment]
Could a solution be to just exclude the "cyclic import" error from the ones "catched" by the `?` operator?

(I would also prefer avoiding more ordering or things)

**Comment by singpolyma** [comment]
‎> (Aside: import resolution is a place where I’ve got stuck implementing dhall-golang. It seems like one of the more complicated and incomprehensible parts of the standard, and even when I crib ideas from dhall-haskell or dhall-ruby, I find the code difficult to follow. I implemented environment variables and `missing` quickly but then hit a brick wall. Does anybody have any implementation advice?)

The dhall-ruby import resolution is a bit over-engineered because it's an area where I want to provide a lot of extensability (swapping out HTTP clients, fetching paths or env from a shared store, etc).

If you just want it to work, then it mostly comes down to: do a pass over your tree, and return a new tree replacing every import node with the parse of what that node imports. Then add transparency check once it works. Then add cors check once that works.

**Comment by Gabriel439** [comment]
@philandstuff: My advice is to follow the judgments from the standard rather than consult the `dhall-haskell` code.  They are written to translate pretty closely to valid code; you just need to learn how to read the natural deduction style of judgment.

For example, the import resolution judgment is essentially pseudo-code for implementing a function of the following Haskell type:

```haskell
resolve
    :: NonEmpty Path                                                  -- "(Δ, here)"
    -> Map Path Expression                                            -- "Γ₀"
    -> Expression                                                     -- "e₀"
    -> Either ImportResolutionError (Expression, Map Path Expression) -- "e₁, Γ₁"
```

Like @singpolyma mentioned, the reason it is so complicated is because users request the ability to customize it to a fault (and I often consider removing that customization support because it's a pain for me to maintain).  If it were not customizable it would be much simpler.

**Comment by Gabriel439** [comment]
I would like to distinguish between two different discussions on ordering that I think people are conflating:

* Should we specify an order of import resolution for record fields?  (and unions, etc.)
* If we do specify an import resolution order, should it be syntactic order or alphabetical order?

I can see how people might not want to specify a syntactic ordering (so that implementations can use unordered maps if they prefer), but I do think we should still specify a reference ordering for import resolution, even if that ordering is alphabetical order.

@philandstuff: That doesn't mean that an implementation has to serialize import resolution.  An implementation can still fetch things in parallel as long as the final result is the same.  As far as I know, the main thing that ordering affects (other than this issue) is when files are written-to/read-from the cache and since the cache is content-addressable, reordering cache writes and reads shouldn't change the result.

**Comment by Gabriel439** [comment]
Regarding what `?` should recover from: I think it's important to revisit the original requirements for the operator.  The original purpose of the operator was to recover from imports that were not available (i.e. a host is down or the network is unavailable).  This is why the identity of the operator is called `missing` to reflect the kind of failure it was designed to handle.

Now this operator is being generalized to recover from a broader class of errors than it was designed for (i.e. type errors).  Perhaps we should restore it back to its original goal of just recovering from failures to fetch content and not other classes of failures.

**Comment by philandstuff** [comment]
This isn't important to me, closing
