### ISSUE TITLE
Why does Integer/show include the leading +?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#508]
I'm trying to generate a script for `execline`, and one of the things I need to do is turn `Exit { exit-code = +0 }` into `"exit 0"`. However, just using `Integer/show exit-code` generates "exit +0", but `execline` can't understand that. It seems somewhat exotic to use `+` notation - most things that use integers *don't* include that.

**Comment by Gabriel439** [comment]
The reason that `Integer/show` generates the leading `+` is because it's supposed to generate valid Dhall code to generate the exact same value being shown.  Since the Dhall syntax for that integer is `+0` then that is what `Integer/show` displays.

Once way you can deal with this is to store it as a `Natural` and a separate field for the sign

**Comment by ocharles** [comment]
I guess that's not the end of the world as I'm dealing with exit codes, but ultimately I'm not convinced Integer/show is all that useful as is
