### ISSUE TITLE
Import integrity checks for `as Text` imports are not specified

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-lang#567]
This is valid dhall syntax:

```
https://www.ietf.org/rfc/rfc3339.txt sha256:997f37c99ba05a1a89b035041bdd499b4542068e3311e8a1e89c842d87ddbfed as Text
```

But if you look in `imports.md` for what this means, you won't get far.  The text basically assumes that integrity checks are always on the CBOR representation of a dhall expression in normal form; but this is not correct for `as Text` imports.  There is no mention of integrity checks for `as Text` imports.

dhall-haskell implements this in the obvious way - just hash the file contents to get the hash value.

This just needs somebody to get around to writing it down in the standard.  (It could be me, when i have enough tuits.)

**Comment by Gabriel439** [comment]
I want to note that the way `dhall-haskell` implements it is not necessarily correct.  An alternative interpretation might be to hash a Dhall text literal (i.e. `[18, ... ]` in CBOR) containing the text contents.

**Comment by singpolyma** [comment]
‎> I want to note that the way `dhall-haskell` implements it is not necessarily correct. An alternative interpretation might be to hash a Dhall text literal (i.e. `[18, ... ]` in CBOR) containing the text contents.

I think this is what dhall-ruby does, and would be my preference since that is indeed the expression that ends up inserted -- would means that the hash of a file that only contains an import as Text would match the has of that import, etc.‎

**Comment by philandstuff** [comment]
I hadn't considered the `[18, ...]` option but that a) makes a lot of sense, and b) would be easier to standardise, as we can express `as Text` integrity checks in terms of code integrity checks.

**Comment by philandstuff** [comment]
Also, now I look closer, `dhall-haskell` does the `[18, ...]` thing too. So it looks like there is consensus on the correct approach.

**Comment by f-f** [comment]
I confirm the `[18, ...]` encoding is also what dhall-clj does

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-lang/pull/574
