### ISSUE TITLE
Issues using List/map + dhall-format

### ISSUE THREAD

**Issue by purcell-nec** [dhall-lang/dhall-lang#59]
Probably doing something stupid here, but given the following:

```
in  let envToStr = λ(e : { name : Text, val : Text }) → e.name ++ "=" ++ e.val

in  let List/map =
          https://ipfs.io/ipfs/QmQ8w5PLcsNz56dMvRtq54vbuPe9cNnCCUXAQp6xLc6Ccx/Prelude/List/map 

in  let toEnv =
            λ(es : List { name : Text, val : Text })
          → List/map { name : Text, val : Text } Text envToStr es
```
then `dhall-format` converts `List/map` on the last line to `List /map`, and I get `Error: Missing file`. `dhall-format` doesn't munge `List/head` in the same way, which is odd.

If I disable `dhall-format` then I get the same error, though.

Using dhall 1.8 from stackage nightly 2017-11-25, on MacOS.

**Comment by Gabriel439** [comment]
I believe Dhall's parser used to support this in older versions but doesn't any longer once I [standardized the grammar](https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf).  Like you noticed, `List/map` is a valid parse for `List` applied to the file `/map` and that parse takes priority over parsing it as a single variable name.  In fact, I think some examples in the tutorial use this idiom and they need to be fixed

Normally you would fix this using a lexer with a longest-match rule, but the Dhall language cannot support a separate lexing step because some language features fundamentally conflict with lexing (specifically: nested block comments and string interpolation).

You can work around this by just prefixing the variable name with anything like `Prelude/List/map`, or just calling it `map`

**Comment by purcell-nec** [comment]
Ah, thanks - that works. I was going off the examples at https://hackage.haskell.org/package/dhall-1.8.0/docs/Dhall-Tutorial.html#g:20, fyi.

**Comment by Gabriel439** [comment]
I'll reopen this just to remind myself to fix the tutorial examples

**Comment by Gabriel439** [comment]
Fixed by https://github.com/dhall-lang/dhall-haskell/commit/834c1b6d05f6e342ac8d7c402ebae7f12732f42c

**Comment by Gabriel439** [comment]
It turns out that there might be a way to fix the original issue after all to support identifier names like `List/map`.  See: https://github.com/dhall-lang/dhall-lang/pull/83

**Comment by purcell-nec** [comment]
Nice!
