### ISSUE TITLE
When is `import as Location` expected to chain?

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#614]
The tests seem to indicate that `./some/import.dhall as Location` should be `"./some/import.dhall"`, but my reading of the standard is that paths should be resolved relative to their parent before being turned into a `Location` value... this should imply that the result is actually `"/path/to/dhall-lang/tests/the/test/some/import.dhall"`

**Comment by Gabriel439** [comment]
@singpolyma: It depends on what the root path is.  The standard is ambiguous here because it doesn't specify what the starting path is.  If the starting path were an absolute path (i.e. `$PWD`) then it would behave like you expect.  If the starting path were a relative path (i.e. `./.`) then it would behave like the test

**Comment by singpolyma** [comment]
Oh, I see that now, ok.

So this is at least a deficiency in the test README instructions for import tests.  How should the root path be specified when running the tests?  This test currently seems to assume that it is set relative to the directory containing the test, but that is *very* unlikely because none of the tests importing from Prelude would work that way (unless the working directory were also set to the directory the test is in).

I would vote these paths in the test be changed to style `./dhall-lang/tests/import/success/some/import.dhall` since that matches a path one is likely to use when running the tests as a submodule (it is not the root path I was previously using, but it's an easy change for me and absolute paths in the test obviously won't work).

**Comment by Gabriel439** [comment]
@singpolyma: Maybe `./tests/import/success/some/import.dhall` (i.e. `dhall-lang` as the root directory), but I otherwise agree

**Comment by philandstuff** [comment]
I prefer @singpolyma’s suggestion - it’s exactly what dhall-golang uses.

Changing working directory would be possible but nontrivial - you need to do it exactly once, before any test starts, and I run them in parallel for performance, which makes “before” a trickier concept. 

It’s much more convenient for the working directory to be already correct by design - ie for the tests to expect the directory to be the path from the test driver file (which is outside the dhall-lang tree) to the test.

**Comment by Gabriel439** [comment]
Alright, then let's stick with `./dhall-lang/...`
