### ISSUE TITLE
Allowing invalid URIs

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-lang#617]
We now have a test `potPourri` which expects this import to parse:

    https://-._~%2C!$&'()*+,;=:@-._~%2C!$&'()*+,;=:/foo?/-._~%2C!$&'()*+,;=:@/?

The problem is, this is not a valid HTTPS URI.

Oh, it's a valid URI of course.  A generic parser will happily parse it and say the scheme is HTTPS, but once you *know* it is HTTPS, it is no longer valid (specifically at least the hostname is not a valid hostname) and it will be rejected by your URI library or at very least by your HTTPS library.

**Comment by Gabriel439** [comment]
I still think the test is correct, in the sense that the only contract for the parsing tests is that they matches the grammar.  If an implementation has to deal with limitations of their URL package they can skip the test.

The main resolution I can think of is to split out this URL into a separate standalone test so that an implementation can skip it without skipping other tests.

**Comment by singpolyma** [comment]
> I still think the test is correct, in the sense that the only contract for the parsing tests is that they matches the grammar

Oh, I agree. I think we should tighten up the grammar to only accept valid HTTP(S) URLs since those are the only URIs schemes we allow.

**Comment by Gabriel439** [comment]
Oh, I understand what you mean now.  Yeah, I'm definitely okay with fixing the grammar to only permit HTTP(S) URIs

**Comment by philandstuff** [comment]
Fixed by #627
