### ISSUE TITLE
Hash function as a monoid homomorphism

### ISSUE THREAD

**Issue by puffnfresh** [dhall-lang/dhall-lang#646]
I've been playing around with hashing Dhall code. I see that `hashExpression` is defined as:

```haskell
hashExpression
    :: StandardVersion -> Expr s X -> (Crypto.Hash.Digest SHA256)
```

The `X` is marking that we don't have any imports in the `Expr` value. This means to hash a Dhall expression, we have to resolve all imports. It also means I can't cache a file which looks like:

```dhall
{ compose =
      ./compose sha256:65ad8bbea530b3d8968785a7cf4a9a7976b67059aa15e3b61fcba600a40ae013
}
```

If Dhall caches it, Dhall resolves the import and we actually get this:

```dhall
{ compose =
      λ(_ : Type)
    → λ(_ : Type)
    → λ(_ : Type)
    → λ(_ : _@2 → _@2)
    → λ(_ : _@2 → _@2)
    → λ(_ : _@4)
    → _@1 (_@2 _)
}
```

I've been thinking about how we can allow using the hashes in the original expressions to hash the expanded expression. I think the awesome work of my coworker @srijs on hash functions as monoid homomorphisms is relevant:

https://github.com/srijs/talks/blob/master/hash-functions-as-monoid-homomorphisms/2016-feb-scalasyd.pdf

This raises a few questions, the most interesting one is that we allowed this, we'd have the two expressions above hash to the same thing. They're equivalent but *different*. Is this a consequence we don't want to allow?

**Comment by Gabriel439** [comment]
@puffnfresh: You might be interested in this discussion, which is about a separate cache for non-normalized expressions:

https://github.com/dhall-lang/dhall-haskell/issues/1098

Also, I want to note that there is no particular reason why `hashExpression` requires normalization-free imports.  Both the standard and the Haskell `Dhall.Binary` module support encoding (and therefore hashing) expressions that have imports or that are not normalized.  It's just that we never used it up until we started work on the "semi-semantic cache" linked in the above issue.

**Comment by philandstuff** [comment]
I think @puffnfresh's question is somewhat orthogonal to @Gabriel439's answer.  My reading of it is: should the hash of `<import> sha256:<hash>` be `<hash>`, so that the hash is the same before and after resolving the import?  Currently, we have a defined hash method which works this way:

 - encode the expression as CBOR
 - compute the sha256 of the CBOR representation

We have defined CBOR representations for all expressions, not merely resolved/normalized/alpha-normalized expressions, so even though we only actually use hashes on a subset of all expressions (as the quoted type signature in the OP reflects), we have a perfectly-well defined hash function on any arbitrary expression.

But @puffnfresh is proposing an alternative: that hashed imports use their supplied hash, rather than hashing the CBOR-encoded import.  I think it's an interesting proposal for certain use cases; it allows us to compute the hash of a fully-resolved expression without having to go to the effort of actually fully-resolving it (assuming we are able to normalize and alpha-normalize expressions with unresolved imports, which may not always be possible).  I can see a world where we can pull in `package.dhall`-type hashed imports without having to download the whole package recursively, because for a typical `package.dhall` file we don't need to resolve all imports to be able verify the hash of the whole record. (This has a flavour of nix's efforts to reduce closure size.)

**Comment by AndrasKovacs** [comment]
> it allows us to compute the hash of a fully-resolved expression without having to go to the effort of actually fully-resolving it (**assuming we are able to normalize and alpha-normalize expressions with unresolved imports, which may not always be possible**)

Unfortunately the bold part is very common. For example, an imported expression can contain a function which can be called with any number of different arguments. We can't compute past an unresolved import, and certainly cannot recover the computational behavior of an import from its hash. Homomorphic hashing AFAIK only works in domains which are vastly simpler than Dhall.

(Theoretical note: Dhall has extremely high [proof-theoretical strength](https://en.wikipedia.org/wiki/Ordinal_analysis), at least as much as second-order arithmetic, and there is no known combinatorial bound or characterization of Dhall normalization).

**Comment by Gabriel439** [comment]
Yeah, as far as I'm aware the only computation that is currently valid for expressions with imports is shifting and substitution.  The reason why is that imported expressions are guaranteed to be closed and shifting/substitution have no effect on closed sub-expressions.

**Comment by puffnfresh** [comment]
@philandstuff yeah `package.dhall` was the motivation.

@AndrasKovacs function application is a super good point. This is pretty useless because of that. Thank you!

**Comment by puffnfresh** [comment]
I'll move to https://github.com/dhall-lang/dhall-haskell/issues/1098 which would be good enough for what I want.
