### ISSUE TITLE
How do I map a function across a list?

### ISSUE THREAD

**Issue by joshburkart** [dhall-lang/dhall-lang#648]
Sorry for the likely *really* dumb question, but if I have a function and want to apply it to every entry in a list to produce a new list...how do I do that? I see `List/fold`, which I guess could work by using an originally empty list as an accumulator, but seems like something like this would be convenient:

```
let blah = \(x: Text) -> {name: x}
in List/map blah ["Alice", "Bob", "Miguel"]
```

**Comment by singpolyma** [comment]
Use List.map from the Prelude

**Comment by joshburkart** [comment]
Ah. Thanks. While I'm asking dumb questions, why sometimes `<type>/<function>` and other times `<type>.<function>`?

**Comment by singpolyma** [comment]
If you use the prelude it's always with a dot. The slashes are for builtins usually and I wouldn't suggest using those normally.

**Comment by joshburkart** [comment]
Ah, ok. Documentation of these kinds of things would really help! Thanks though!

**Comment by philandstuff** [comment]
Expanding a bit: the slash is part of the identifier; the dot is a record selection operator. So in `List/fold`, this is an identifier with a name which happens to include a `/` character.

In `List.map`, however, we’re saying “take the record named `List` and select the field named `map` from it. For this to work, there would have to be a `let List = https://...` import above to define `List`. 

Of course, you could always import `List.map` directly, rather than importing the whole Prelude. Then you might choose to bind it to the name `List/map`, rather than trying to create a `List` record with a single field. (In contrast to @singpolyma, this would be my preferred style - maybe we should have a style guide discussion on discourse?)

**Comment by joshburkart** [comment]
Hmm ok, thanks.

FYI my reaction coming from C-like languages is that this all seems quite peculiar, and decreases my interest in the language... Obviously 0 offense intended... Dhall seems like the perfect fit for lots of config file management, so I'm a bit disappointed at what I perceive to be odd design decisions, together with the unfamiliar-to-me functional syntax. E.g. I doubt I'd be able to convince my team at work (C++ codebase with substantial config file problems) to use Dhall... :(

Specifically:

* Having `List/fold` be just another identifier, rather than `/` implying method access and being explicitly tied to `List`, is :( for me...
* Redefining `List` using the prelude :(
* Not having access to `map` without downloading the prelude
* Needing to specify the input and output data types of `map` rather than this being inferred (I just want `map func [1, 2, 3]`...or better yet  `map(func, [1, 2, 3])`...
* Not being able to find documentation for much of this...

Sorry, hope I'm not being rude, just sharing my personal impressions.

**Comment by singpolyma** [comment]
> * Redefining `List` using the prelude :(

You don't redefine List, though you can sort-of create a variable with that name. You can import the whole Prelude as any name (probably Prelude) or just the List module, or just the map function. This should definitely be documented somewhere because any nontrivial Dhall program will want something from Prelude.

> * Not having access to `map` without downloading the prelude

I think it would be interesting if implementations could ship with the Prelude baked in. Would be easier if the "official" link were something stable like IPFS. Worth thinking more about. Then you would still need to import it, but not "download" it.

> * Needing to specify the input and output data types of `map` rather than this being inferred (I just want `map func [1, 2, 3]`...or better yet `map(func, [1, 2, 3])`...

Yeah, this is my least favourite part of Dhall myself. I understand that it makes very powerful features possible with less overhead, but I would like full type inference. Something I've played with and may look at trying again in the future, even as a dhall+inference-to-dhall translator or something.

**Comment by Gabriel439** [comment]
@joshburkart: Just out of curiosity, how were you consdering using Dhall within a C++ codebase?  Are you going to be converting to JSON/YAML?

I also understand that the documentation is falling behind right now.  I plan on improving and centralizing documentation soon (i.e. a book).  Along those lines: what documentation resources have you seen so far?

**Comment by joshburkart** [comment]
@Gabriel439 Well I was more in exploration phase, but yeah perhaps serialize to JSON first. Hmm, I've gone through the website, the tutorial... Maybe some other places?

Thanks for all the responses!

**Comment by Gabriel439** [comment]
@joshburkart: The other big tutorial which you might not have seen is: https://hackage.haskell.org/package/dhall/docs/Dhall-Tutorial.html

**Comment by joshburkart** [comment]
@Gabriel439 I had seen it, but apparently hadn't read it very carefully! Thanks to the responses on this thread, I'm understanding things better now, so hopefully I'll be more self sufficient in future Dhall exploration. :)
