### ISSUE TITLE
Better Syntax for Lists, Records (and Unions)

### ISSUE THREAD

**Issue by adius** [dhall-lang/dhall-lang#66]
There are 3 different syntax styles for list like constructs:
1. Separator
2. Terminator
3. Enumerator

Here a quick overview

## Separator (e.g. JavaScript)

Single line:
```js
const colors = ["Red", "Green", "Blue"]
```

Multi line:
```js
const colors = [
  "Red", 
  "Green", 
  "Blue"
]
```
This feels very natural for single line expressions, but has drawbacks for multi line expressions:

1. Items can't be easily rearranged when the last element is involved
2. Adding an element changes 2 lines (diffs get harder to read & understand)

Other acceptable characters for this style (in single line form) are `|` or `/` and if necessary also `;`.
In multi line form this really sucks.

## Terminator (e.g. OCaml)

Single line:
```ocaml
let colors = ["Red"; "Green"; "Blue";]
```

Multi line:
```ocaml
let colors = [
  "Red";
  "Green";
  "Blue";
]
```

This looks a little weird for single line expressions, but excels for multi line expressions.
Making it also mandatory for the single line version has the advantage that
it's not possible to forget to add the last `;` when converting a single line to a multi line expression.

A special case of this syntax is when the newline character is used as terminator.
(e.g. in CoffeeScript)

```coffeescript
colors = [
  "Red"
  "Green"
  "Blue"
]
```

Other acceptable characters for this style are `.` and `,` (but less so).

## Enumerator (e.g. YAML)

Single line (is not valid in YAML, but could be in another language):

```txt
colors: - Red - Green - Blue
```

```yaml
colors:
  - Red
  - Green
  - Blue
```

Needs a little getting used to in single line form, but is actually not too bad.
Multi line is great, as it feels very natural to use and is quite readable.
Other good characters for this are `*` or `+` (`*` not so much, as it is vertically aligned to the top in many font faces)

Now, what does Haskell / Dhall do?

**It uses a broken version of the Enumerator style (broken, because first element can't be easily changed / rearranged) with the worst possible character (worst, because `,` is totally skewed to the bottom).**

I really hope you can reconsider this design choice!
At the moment it is just awful.

My favorite version would be `;` or `,` in the terminator style.
(I think `.` is too dangerous, as it could be misunderstood as a decimal point or vice versa,
but I haven't thought this through yet.)

```haskell
colors = ["Red"; "Green"; "Blue";]

color = {
  "Red": 50;
  "Green": 60;
  "Blue": 70;
}

-- And Unions could look like this:
size = | Small | Medium | Large
```

What do you think?

**Comment by chepner** [comment]
It's not clear why you think Haskell and Dhall use the Enumerator style. They both use the Separator style, but convention is to put the separator at the beginning of the following line rather than the end of the previous line. That is,

```colors = [
  "Red"
, "Blue"
, "Green"
]```

and

```colors = [
"Red",
"Blue",
"Green"
]```

and

```colors = ["Red", "Blue", "Green"]```

all parse to the same three-item list.

**Comment by adius** [comment]
99% of multi line Haskell code is formatted with comma first => They use the enumerator style.
That it (probably) was originally designed with the separator style in mind and that it uses a character which is normally used for separation doesn't change that.

But you're right for single line. There it's actually written in the separator style.

**Comment by Gabriel439** [comment]
I will give a more detailed response later, but I just want to quickly point out that `dhall-format` formats multi-line lists like this:

```haskell
colors =
    [ "Red"
    , "Blue"
    , "Green"
    ]
```

In other words, comma first, but with the opening and closing bracket also aligned with the commas

**Comment by adius** [comment]
Yes, I know, and I mean it looks like you actually want

```
colors =
  - "Red"
  - "Blue"
  - "Green"
```
but Haskell was designed with this in mind

```haskell
colors = ["Red", "Blue", "Green"]
```

and now you're misusing this syntax in an awful way to generate following frankenstein syntax:

```haskell
colors =
    [ "Red"
    , "Blue"
    , "Green"
    ]
```

**Comment by chepner** [comment]
adius, you are confusing a formatting convention with the syntax used. Dhall *does not* use the Enumerator style; it would be incorrect to write `color = [,"Red" ,"Blue" ,"Green"]` or ```

colors = [, "Red"
                , "Blue"
                , "Green"
               ]
```

This convention addresses the issue of modifying two lines when adding to the end of a list at the expense of making it slightly more work to add an item to the beginning of a list. You might observe that appending is a more common task than prepending.

**Comment by adius** [comment]
Ah OK, now I know what you mean. I should have said:
"Although the syntax is separator style Haskell / Dhall misuses the syntax by formatting it like it would be Enumerator style." Thanks for pointing out this inexactness.

Yes, the convention tries to work around an awful syntax choice (and only makes it worse in my opinion)

**Comment by Gabriel439** [comment]
Alright, now I can give a more detailed response.

I do not plan to change the list separator in Dhall from `,` to `;` (or any other character).  That would be a breaking change with no technical benefit that I'm aware of.  Changing the separator would also produce large diffs in existing Dhall code to conform to the new separator, which is against one of the stated goals of this issue (improving the relevance of `git blame`s).

Assuming that Dhall does not change any separators, the next issue is whether or not Dhall should support trailing separators for smaller diffs and more accurate `git blame`s.  My understanding is that trailing separators is the main request of your proposal.

This was requested before in https://github.com/dhall-lang/dhall-haskell/issues/27 and for a while Dhall did support trailing separators.  As you can see later in that issue I removed support for them when standardizing the grammar because they greatly increased the complexity of the grammar for union literals (especially when combined with support for the selected alternative not needing to be at the front of the union literal).  In the interest of simplifying the grammar and also standardizing on a single style for `dhall-format` I removed support for trailing separators.

Also, `dhall-format` simplifies adding or prepending elements: you can insert them inline anywhere within the list and let `dhall-format` reformat the list for you.  For example, suppose that I have the following formatted Dhall multi-line list:

```haskell
[ "Red"
, "Green"
, "Blue"
]
```

... and I want to both prepend and append elements to the list.  I would, in my editor, insert the additional elements inline, such as:

```haskell
[ "Infrared", "Red"
, "Green"
, "Blue", "Violet", "Ultraviolet"
]
```

... then use `dhall-format` to reformat the list:

```haskell
[ "Infrared"
, "Red"
, "Green"
, "Blue"
, "Violet"
, "Ultraviolet"
]
```

... or equivalent editor support powered by `dhall-format` (such as [dhall mode](https://melpa.org/#/dhall-mode) in `emacs`)

There's also another (subjective) issue with trailing separators, which is that the separators cannot be aligned, assuming you minimize `git` diffs.  I subjectively prefer to align separators, which is why I prefer preceding ones.

However, I also would not support the YAML-style separator because there is no easy way to separate two consecutive list literals in the grammar.  For example, suppose that you had a function of type:

```haskell
foo : List Integer → List Integer → List Integer
```

If you translated the following expression:

```haskell
foo [1, 2, 3] [4, 5, 6]
```

... to YAML-style separation then you would get:

```haskell
foo - 1 - 2 - 3 - 4 - 5 - 6
```

... which would be parsed as one long list literal.

**Comment by adius** [comment]
> with no technical benefit

Well, how about we write Assembly instead of C. There is no "technical benefit" ^^

Readability, understandability, writability and ease of editing
are the most important aspects for a syntax.
Especially if it is supposed to be a config / template language.


> Changing the separator would also produce large diffs in existing Dhall code

We should try to optimize over the whole lifetime of the language, not over existing code. 

---

I actually also forgot to mention one more really annoying problem. 
It's not possible to easily comment out the first line for testing:

```dhall
colors = 
  [ "Red"
  , "Blue"
  , "Green"
  ]

colors = 
  [ -- "Red"
  --, 
  "Blue"
  , "Green"
  ]
```

This seems to be the easiest way. 🤮.

> no easy way to separate two consecutive list literals in the grammar

```
foo [- 1 - 2 - 3] [- 4 - 5 - 6]
```

But I guess the minus is to dangerous anyways: `[- 1 - 2 - 3]` vs `[- (1 - 2) - 3]`

How about you add support for leading comma then?
This should also just slightly complicate the grammar, right?
("ignore whitespace and `,` after `[`" instead of just "ignore whitespace after `[`")
And it should of course not be optional.

```dhall
colors = [
  , "Red"
  , "Blue"
  , "Green"
]
```

**Comment by adius** [comment]
Actually Haskell did already great job (but they didn't notice 🙈):

```haskell
colorsA =  "Red" : "Green" : "Blue" : []
colorsB = ["Red", "Green", "Blue"]
```

I fail two see why the second syntax is necessary.
I think the first syntax is much better.

Empty list could maybe shortened by one character, but that's it.
```haskell
colorsA =  "Red" : "Green" : "Blue" : #
```

**Comment by adius** [comment]
Oh, look at that, I'm not the only one: https://wiki.haskell.org/Syntactic_sugar

**Comment by adius** [comment]
Even cooler, I just realized you could do this in Haskell:

```haskell
(~~) a b = a ++ [b]

colorsTilde = []
  ~~ "Red"
  ~~ "Green"
  ~~ "Blue"
```

❤️❤️❤️

But I guess this does is not particularly efficient 😅

**Comment by Gabriel439** [comment]
When I say "no technical benefit" I mean that the differences are subjective.  For example, I think that `dhall`'s list syntax and recommended formatting style is pleasant and readable, but I don't use that as an argument in this discussion because it's a subjective judgment.

Contrast that with a argument such as the one you just made: "it's harder to comment out one element", which is an example of a technical concern.  However, I still think this concern is minor because it only happens in the uncommon scenario where (A) the user wants to comment out the first element and (B) the first element fits on one line.

Also, you can to comment out arbitrary subsets of elements using block comments:

```haskell
colors =
  [ {- "Red"
  , "Blue"
  , -} "Green"
  ]
```

The benefit of that solution is that it works even when elements of the list span more than one line (i.e. each element is a large record, for example).

More generally, Dhall is not line-oriented, which is why Dhall provides support for block comments and that is also why Dhall is not whitespace-sensitive or indentation-sensitive.  `dhall-format` tries to be line-oriented but that's about it.

Also, regarding your latter comments, you can achieve a similar effect in Dhall using the `#` operator:

```haskell
colorsTilde = ([] : List String)
    # [ "Red" ]
    # [ "Green" ]
    # [ "Blue" ]
```

If you really want precise `git diff`s and `git blame`s at all costs then that is an option.

However, I also want to address the argument of what Dhall should optimize for.  The stated goals of the Dhall configuration language are listed here:

https://github.com/dhall-lang/dhall-lang#design-philosophy

Note that readability, writability, and ease of editing are not stated goals of the language.  The reasons why are that:

* readability, understandability, writability are subjective standards that people cannot universally agree on
    * My experience is that people interpret all of these to mean "similar to languages that I'm already familiar with".  I'm certainly no exception to that rule, which is why Dhall's syntax resembles Haskell's syntax.
* "ease of editing" *is* a more rigorous standard, but it makes the Dhall language design a slave to idiosyncrasies of version control tools and editors

I'm not saying that a configuration language should not strive to be readable.  I actually agree that readability is valuable for a configuration language!  It's just that "readable" means different things to different people and (as far as I can tell) pleasing everybody is not possible.

Also, the absence of a rigorous technical standard for design goals invites heated discussions and toxic debates.  Imagine hundreds of comments on a GitHub issue where nobody can conclusively prove that their side of the debate is technically superior so the argument keeps going back and forth with the tone of the discussion gradually deteriorating.  You've probably seen this scenario play out before in various forms and I'm trying to prevent that from happening by sticking to semi-rigorous design goals.

**Comment by adius** [comment]
> uncommon scenario where (A) the user wants to comment out the first element and (B) the first element fits on one line

I feel like I do it all the time, but maybe I'm just over sensitive too it...
You are right, however, that I could leverage block comments in a smarter way.
It's just much easier/faster to click in the line and press `cmd + /` to comment out the line 
(or use some `cmd` + `L` to select several lines before)

> similar effect in Dhall using the # operator

Except it is ~25 characters longer ;-)

> different things to different people and (as far as I can tell) pleasing everybody is not possible

Comma first is definitely off-putting for developers coming from classic languages.
And it sickens me that we alienate developers from other languages with solutions which are not better, but just different. And I'm all in for changing things if they make things for the better, but shoehorning separation style to look like a enumeration with broken first element editing / commenting / sorting isn't.

Oh yeah I forgot to mention that too: What I often do is select all elements from a list and let my editor sort them alphabetically. Doesn't work with Haskell style formatting either.

Btw: I actually started to develop a potential successor for YAML / JSON / TOML a few month ago before I heard about Dhall with a focus on ease of editing / readability and safety (through a set of predefined types). I was very interesting to read your ideas for this problem space. I really like the idea of being able to reference external files and of being able to specify a hash for them.
I hope this will be able to complement the focus of Dhall 🙃.

**Comment by adius** [comment]
And a little anecdote:

Apparently the computer science community had the same discussion already in the 60s to 80s,
but not about commas, but semicolons as separator or terminator in statements in normal code.

Luckily they made the sane choice and therefore most programming languages use the semicolon as a statement terminator, not separator.
I don't know why we have to make the same mistakes all over again 😭.

**Comment by adius** [comment]
> One generally accepted experimental result in programmer psychology is that semicolon as separator is about ten times more prone to error than semicolon as terminator
http://www.cs.virginia.edu/~cs655/readings/bwk-on-pascal.html

**Comment by Gabriel439** [comment]
Suppose that I were to add support for trailing commas and also update `dhall-format` to format them after the elements instead of before.  Would you also recommend that the bars in a multi-line union literal be treated the same way?

In other words, instead of the current behavior, which is this:

```haskell
< Red : {}
| Green : {}
| Blue : {}
>
```

... would you instead prefer this:

```haskell
<
  Red : {} |
  Green : {} |
  Blue : {} |
>
```

... because that strikes me as visually jarring.  (To be honest, trailing commas/semicolons also strike me as visually jarring once I got used to comma/semicolon-first style, but trailing bars even more so)

The other issue is that in "comma-first" style it is easy to visually navigate between elements of the list when list elements or record fields are quite large.  For example, suppose we had:

```haskell
[ very large
    dhall expression
  that spans
    multiple lines
, yet another large dhall expression
    that
  spans multiple
    lines
, here is the third
    expression
]
```

Your eye can easily jump to the 1st, 2nd, 3rd elements quickly by just scanning vertically down from the first bracket.  Contrast with:

```haskell
[
  very large
    dhall expression
  that spans
    multiple lines,
  yet another large dhall expression
    that
  spans multiple
    lines,
  here is the third
    expression,
]
```

**Comment by adius** [comment]
I'm also more a fan of the enumerator style. I think YAML has a pretty great syntax.

But at the end of the day I think the difference between enumerator and terminator is pretty much personal preference. (You might argue that missing enumerators are easier to see than missing terminators, but that's the only technical difference I can think of and the compiler / auto formatter
warns you about them as well)

**But enumerator and terminator are both substantially better than separator (like I explained before)**

You could convert all listings to be enumerator style.
Should be possible to implement backwards compatible.

```haskell
colors = | Red : {} | Green : {} | Blue : {}
colors =
  | Red : {}
  | Green : {}
  | Blue : {}

lines = [ 
  , very large
      dhall expression
  that spans
    multiple lines
  , yet another large dhall expression
    that
  spans multiple
    lines
  , here is the third
    expression
]

record = {
  , bar = False
  , foo = +3
  }
```

Although, to be honest, if you want folks beyond the (small) Haskell universe to adopt the language you should probably just use terminator style with commas. That's what people know, what they are comfortable with. I was confused by the syntax when I started to learn Haskell, too. It also took me some time to realize it's just normal arrays formatted weirdly (and not some special syntax construct), and to relearn typing code that way (I still often add accidentally two commas because I subconsciously add one at the end of a line) (And currently I'm writing a lot of PureScript, which has no good autoformatter yet) .

```
record = {
  bar = False,
  foo = +3,
}
```

**Comment by adius** [comment]
You could also make arrays & records terminator style, and unions enumerator style.
I don't think this inconsistency would be a huge problem. It's not like you want to convert them form one to each other (while array <-> record should be the same).

**Comment by adius** [comment]
Enumerator style should also make your parser easier for unions, right?
As soon as you hit the bar, you know it's going to be a union.

**Comment by Gabriel439** [comment]
Yes, enumerator style is easier to parse than terminator style, but only if there is a final character to indicate when the sequence is done.  Going back to the union example, it would have to be something like:

```haskell
colors = <
  | Red : {}
  | Green : {}
  | Blue : {}
  >
```

... similar to the list/record examples.  The reason YAML gets away with not requiring a final character to terminate the sequence is because YAML is indentation-sensitive.

However, this still doesn't solve the issue, though.  Consider the case of how to format multi-line anonymous functions or `let` expressions, which are currently formatted as:

```haskell
    λ(x0 : t0)
→ λ(x1 : t1)
→ λ(x2 : t2)
→ ...
```

... or:

```haskell
    let x0 = e0
in  let x1 = e1
in  let x2 = e2
in  ...
```

How would that work under enumerator style?

I'm not too concerned about preserving visual similarity to other languages or configuration file formats, though.  I think the arguments for precise diffs/blames, quicker editor manipulations, and visually indexing into the list are slightly more compelling than familiarity but still not strong.  My experience is that programming language adoption is driven by strong necessity rather than visual attractiveness.  If they choose Dhall it will be because they need functions or imports without sacrificing types or safety.

For example, Haskell initially tried the "let's make the language pretty" approach to drive adoption and it didn't work.  What ended up driving industry adoption in the end was the type system and people ended up putting up with a lot of ugly nonsense (lots of language extensions, type-level programming, long compile times, sometimes Template Haskell) just to get the safety they needed.

You're right that people hate change, but if they can't get over the way `dhall-format` formats multi-line lists then they are not going to get past anonymous functions or unions.  If somebody turns the language down because of the syntax then that just tells me that the language is not delivering enough value to them to overcome their aversion to change.  The solution to that is to deliver more value, not minimize change.

**Comment by adius** [comment]
>  Going back to the union example, it would have to be something like: …

Looks good to me


> how to format multi-line anonymous functions

```dhall
→ λ(x0 : t0)
→ λ(x1 : t1)
→ λ(x2 : t2)
→ ...
```

This would work I guess, altough I have to admit even I think this is weird 😅.
But unlike lists & records they don't normally span several lines or could be rewritten with `let` statements, right?


> how to format let expressions

```dhall
let x0 = e0 in
let x1 = e1 in
let x2 = e2 in
<expression>
```

This would be OK as it is unlikely that I want to move the final expression to another line, and all let expressions can be rearranged / deleted / … as they are terminator style.


> My experience is that programming language adoption is driven by strong necessity rather than visual attractiveness

My experience is that Haskell is easily one of the best programming languages around, yet developers get deterred by all the weird idiosyncrasies.
"If they can't even get commas right, how are they supposed to build an even halfway decent language". That was also my first thought to be honest.


>  If somebody turns the language down because of the syntax ...

Or he might be a more of a visual person than you are. 


> delivering enough value to them to overcome their aversion to change

Yeah true. But I can't see how this is an argument for anything. Let's make the syntax reaaally shitty, so that people must love the language to use it? 🤔

**Comment by adius** [comment]
Point in case: JavaScript is easily one of the worst languages around, but at least they got the commas right (trailing comma even in function calls) and the naming of functions is (mostly) pretty good. Haskell on the other hand calls functions `nub`. Nobody knows what that means. They should have just called it `removesDuplicates`. And this definitely deters developers. You can wave it of as irrelevant or minor, but for other (including me) it isn't.

**Comment by asivitz** [comment]
`Let's make the syntax reaaally shitty, so that people must love the language to use it?`
Come on... That's not what he's saying. He's trying to make the best language he can, and he won't get there by trying to fit everyone's preferences. You have to argue in good faith.

**Comment by adius** [comment]
Well, the problem is, I don't really see separator vs (terminator/enumerator) as a matter of preference. A matter of preference would for me be if I call the variable keyword `var` or `let`. I can't come up with any plausible reason why one would be better than the other (except maybe that `var` is an abbreviation and `let` is a real word). On the other hand there a several valid reasons why terminator / enumerator is the better choice. Let me restate them:

1. Items can be rearranged without modification
  1.1 You can select all lines and let your editor sort them
2. Git diffs are more meaningful / easier to read
  2.2. You can commit lines separately without having to change anything
3. Git blame displays the correct author
4. Every line can be easily commented out for testing
5. All the research on how separator style increases the chance of error

Considering this amount of evidence that terminator / enumerator is objectively better,
I have no understanding why anyone could still choose separator style over terminator / enumerator style. It feels like someone claims the earth is flat.

**Comment by adius** [comment]
... and that `var` stand for variable but  `let` is immutable. Ok, that was a bad example.
Can't think of a good example right now, but I guess there is one.

**Comment by pthariensflame** [comment]
@adius It seems to me that you're hung up on your editor being line-oriented.

**Comment by adius** [comment]
Haha, yeah, maybe there is a smarter way to edit code. I'd be happy to hear get some tips.
(And then you have the write code in GitHub comments and it's line based again :wink:)

**Comment by Gabriel439** [comment]
@asivitz: In order to keep this discussion from going off the rails let me address the tone of anything directed at me or the language.  I have experience navigating this sort of criticism.  I appreciate the defense, though :)

@adius: I'm still not convinced that the benefit is large enough to justify changing the language, but I'm not going to shut down this discussion altogether.

Out of all the proposals that you have suggested, the one that seemed the most promising to me was:

* Leave the separator punctuation the same
* Adding grammar support for an initial leading comma/bar for records/unions
* Have `dhall-format` format multi-line literals with leading commas/bars

The reasons why are:

* It's not too visually different from the current style that `dhall-format` uses
* Doesn't add an additional lines
* Still preserves visual alignment
* Is friendly to line-based tools

However, I'm still opposed because I would like to keep the grammar as minimal as possible and I would also like to discourage multiple ways of doing things.  This the same reason why Dhall does not support more than one definition per `let`.

The reason I weigh the benefit of line-based formatting pretty low is that Dhall is targeting a design space where the editor and `git` are not the bottlenecks.  For example, speed of editing would be a bottleneck in a language that didn't support functions to reduce repetition.  Similarly, minimizing `git diff`s for ease of review would be a greater concern for a language where you don't have types to enforce correctness.

Although I'm a no on this, I'll leave the issue open and see if other people feel the same way.  Specifically, what I'm looking for are accounts of issues caused from using Dhall in production that originated from either the grammar or standard formatting style for multi-line literals  If so then I'll reconsider my view on this.  Dhall's focus is on safety and correctness, so an argument framed in those terms is much stronger in my eyes.

**Comment by adius** [comment]
> the one that seemed the most promising to me was ...

Sounds good!


> I would also like to discourage multiple ways of doing things

Definitely not a fan either. Make leading comma mandatory!
(After a deprecation period of course)

> targeting a design space

I think config files are a prime example. You have lots of lists and you might want to change something quickly / comment something out for testing.
I could show you 2 commits just from last week where a developer in my company added a new entry to a `package.json` file "real quick" and forgot to add the trailing newline in the line above 😩.
This would also be my account of issues caused by separator style.

**Comment by adius** [comment]
BTW: Thanks for the discussion, you could have just closed it and call it a day. Appreciate the thoughtfulness!

**Comment by adius** [comment]
Oh, and what about the proposal to auto format

```dhall
    let x0 = e0
in  let x1 = e1
in  let x2 = e2
in  ...
```

like this

```dhall
let x0 = e0 in
let x1 = e1 in
let x2 = e2 in
<expression>
```

That's something that could be implemented without changing the syntax!

**Comment by Gabriel439** [comment]
The main reason I do the former formatting style is because (A) it also keeps the `in` tokens aligned (and similar reasoning for `λ` and `→`) and (B) .  However, I'm not as strongly opinionated about that choice since either way you can still visually index into the multi-line construct

**Comment by adius** [comment]
The `let` tokens are still aligned and act as the enumerator.
Your formatting also means the first `let` must be indented, which means extra work (I know, that's not relevant for the auto formatting, but it's still good to know one can achieve the same layout easier without auto formatter)
I'd definitely go for this change. Want me to give a shot at the implementation?

**Comment by Gabriel439** [comment]
@adius: Alright!  You can find the pretty-printing code here:

https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Core.hs#L483-L1056

The specific parts to change for anonymous functions and `let` expressions would be:

https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Core.hs#L617

https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Core.hs#L684

... and if you browse that you will see there are other things that support multi-line formatting like nested `if`-`then`-`else` expressions and function types (i.e. `Pi`), too

**Comment by Gabriel439** [comment]
Oh, there's another thing I forgot about: operators!  The `dhall-format` tool will also format a chain of the same operator using the following multi-line syntax:

```haskell
    "Red"
++  "Green"
++  "Blue"
```

In fact, a good expression to test formatting ideas on is this one:

```haskell
λ(xs : List { cores : Natural, host : Text, key : Text, mandatoryFeatures : 
List Text, platforms : List < AArch64_Linux : {} | ARMv5tel_Linux : {} | 
ARMv7l_Linux : {} | I686_Cygwin : {} | I686_Linux : {} | MIPS64el_Linux : {} | 
PowerPC_Linux : {} | X86_64_Cygwin : {} | X86_64_Darwin : {} | X86_64_FreeBSD : 
{} | X86_64_Linux : {} | X86_64_Solaris : {} >, speedFactor : Natural, 
supportedFeatures : List Text, user : Optional Text }) → List/fold { cores : 
Natural, host : Text, key : Text, mandatoryFeatures : List Text, platforms : 
List < AArch64_Linux : {} | ARMv5tel_Linux : {} | ARMv7l_Linux : {} | 
I686_Cygwin : {} | I686_Linux : {} | MIPS64el_Linux : {} | PowerPC_Linux : {} | 
X86_64_Cygwin : {} | X86_64_Darwin : {} | X86_64_FreeBSD : {} | X86_64_Linux : 
{} | X86_64_Solaris : {} >, speedFactor : Natural, supportedFeatures : List 
Text, user : Optional Text } xs Text (λ(x : { cores : Natural, host : Text, 
key : Text, mandatoryFeatures : List Text, platforms : List < AArch64_Linux : 
{} | ARMv5tel_Linux : {} | ARMv7l_Linux : {} | I686_Cygwin : {} | I686_Linux : 
{} | MIPS64el_Linux : {} | PowerPC_Linux : {} | X86_64_Cygwin : {} | 
X86_64_Darwin : {} | X86_64_FreeBSD : {} | X86_64_Linux : {} | X86_64_Solaris : 
{} >, speedFactor : Natural, supportedFeatures : List Text, user : Optional 
Text }) → λ(y : Text) → (Optional/fold Text x.user Text (λ(user : Text) 
→ user ++ "@" ++ x.host ++ "") x.host ++ " " ++ (merge { Empty = λ(_ : {}) 
→ "", NonEmpty = λ(result : Text) → result } (List/fold < AArch64_Linux : 
{} | ARMv5tel_Linux : {} | ARMv7l_Linux : {} | I686_Cygwin : {} | I686_Linux : 
{} | MIPS64el_Linux : {} | PowerPC_Linux : {} | X86_64_Cygwin : {} | 
X86_64_Darwin : {} | X86_64_FreeBSD : {} | X86_64_Linux : {} | X86_64_Solaris : 
{} > x.platforms < Empty : {} | NonEmpty : Text > (λ(element : < AArch64_Linux 
: {} | ARMv5tel_Linux : {} | ARMv7l_Linux : {} | I686_Cygwin : {} | I686_Linux 
: {} | MIPS64el_Linux : {} | PowerPC_Linux : {} | X86_64_Cygwin : {} | 
X86_64_Darwin : {} | X86_64_FreeBSD : {} | X86_64_Linux : {} | X86_64_Solaris : 
{} >) → λ(status : < Empty : {} | NonEmpty : Text >) → merge { Empty = 
λ(_ : {}) → < NonEmpty = merge { AArch64_Linux = λ(_ : {}) → 
"aarch64-linux", ARMv5tel_Linux = λ(_ : {}) → "armv5tel-linux", ARMv7l_Linux 
= λ(_ : {}) → "armv7l-linux", I686_Cygwin = λ(_ : {}) → "i686-cygwin", 
I686_Linux = λ(_ : {}) → "i686-linux", MIPS64el_Linux = λ(_ : {}) → 
"mips64el-linux", PowerPC_Linux = λ(_ : {}) → "powerpc-linux", X86_64_Cygwin 
= λ(_ : {}) → "x86_64-cygwin", X86_64_Darwin = λ(_ : {}) → 
"x86_64-darwin", X86_64_FreeBSD = λ(_ : {}) → "x86_64-freebsd", X86_64_Linux 
= λ(_ : {}) → "x86_64-linux", X86_64_Solaris = λ(_ : {}) → 
"x86_64-solaris" } element | Empty : {} >, NonEmpty = λ(result : Text) → < 
NonEmpty = (merge { AArch64_Linux = λ(_ : {}) → "aarch64-linux", 
ARMv5tel_Linux = λ(_ : {}) → "armv5tel-linux", ARMv7l_Linux = λ(_ : {}) → 
"armv7l-linux", I686_Cygwin = λ(_ : {}) → "i686-cygwin", I686_Linux = λ(_ : 
{}) → "i686-linux", MIPS64el_Linux = λ(_ : {}) → "mips64el-linux", 
PowerPC_Linux = λ(_ : {}) → "powerpc-linux", X86_64_Cygwin = λ(_ : {}) → 
"x86_64-cygwin", X86_64_Darwin = λ(_ : {}) → "x86_64-darwin", X86_64_FreeBSD 
= λ(_ : {}) → "x86_64-freebsd", X86_64_Linux = λ(_ : {}) → 
"x86_64-linux", X86_64_Solaris = λ(_ : {}) → "x86_64-solaris" } element) ++ 
"," ++ result | Empty : {} > } status : < Empty : {} | NonEmpty : Text >) < 
Empty = {=} | NonEmpty : Text >) : Text) ++ " " ++ x.key ++ " " ++ Integer/show 
(Natural/toInteger x.cores) ++ " " ++ Integer/show (Natural/toInteger 
x.speedFactor) ++ " " ++ (merge { Empty = λ(_ : {}) → "", NonEmpty = 
λ(result : Text) → result } (List/fold Text x.supportedFeatures < Empty : {} 
| NonEmpty : Text > (λ(element : Text) → λ(status : < Empty : {} | NonEmpty 
: Text >) → merge { Empty = λ(_ : {}) → < NonEmpty = element | Empty : {} 
>, NonEmpty = λ(result : Text) → < NonEmpty = element ++ "," ++ result | 
Empty : {} > } status : < Empty : {} | NonEmpty : Text >) < Empty = {=} | 
NonEmpty : Text >) : Text) ++ " " ++ (merge { Empty = λ(_ : {}) → "", 
NonEmpty = λ(result : Text) → result } (List/fold Text x.mandatoryFeatures < 
Empty : {} | NonEmpty : Text > (λ(element : Text) → λ(status : < Empty : {} 
| NonEmpty : Text >) → merge { Empty = λ(_ : {}) → < NonEmpty = element | 
Empty : {} >, NonEmpty = λ(result : Text) → < NonEmpty = element ++ "," ++ 
result | Empty : {} > } status : < Empty : {} | NonEmpty : Text >) < Empty = 
{=} | NonEmpty : Text >) : Text) ++ "\n") ++ y) ""
```

**Comment by ocharles** [comment]
> Although I'm a no on this, I'll leave the issue open and see if other people feel the same way. 

A year has passed and there are no comments. I think this ship has sailed and it's probably time to close this issue.

**Comment by Gabriel439** [comment]
Yeah, I'll close this out.  Also, I want to note here that we do plan to add support for trailing delimiters soon (i.e. trailing commas and bars), now that we've removed support for the old union syntax which was the biggest complication

**Comment by sporto** [comment]
Please reconsider this format. Having the first item in a multi line list different than the others is really annoying. Makes re-ordeing items quite cumbersome.

**Comment by Gabriel439** [comment]
@sporto: The language now supports leading and trailing commas, so you should be able to format all elements of a list uniformly
