### ISSUE TITLE
Imports relative to the file that's importing

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-lang#68]
Take the following files:

* `a/b` containing the Dhall expression `./c`
* `a/c` containing the Dhall expression `True`.

I then run

```bash
$ dhall < a/b
```

and would expect to see `True`. Instead, I actually get:

```
↳ ./c 

Error: Missing file c
```

I find this very surprising, and find Nix's import semantics much more sensible. Is there still time to rethink this?

**Comment by ocharles** [comment]
There is a natural question about what this means for HTTP imports - that is, what does it mean to be "relative" to a HTTP import. One solution is to simply prohibit it, the other option is to build a path relative to the HTTP URL. It could be argued that a relative import from a HTTP import is unsafe though anyway, as it has the ability to import things from the local fs, which could be used to accidentally expose potential secrets.

**Comment by Gabriel439** [comment]
@ocharles: Note that the example works if you instead do:

```bash
$ dhall <<< './a/b`
```

The only reason it failed was because you fed `./a/b` through standard input so Dhall doesn't know what where standard input is coming from, so Dhall assumed it was relative to the current directory by default.

Also, Dhall does handle paths relative to HTTP imports.  For example, if you import `http://example.com/foo/bar` and then that imports `./baz` then the relative import will resolve to `http://example.com/foo/baz`

HTTP imports cannot import things from the local filesystem (of either the server or client).  For example, if the `http://example.com/foo/baz` import tried to import an absolute path like `/baz` then the import would fail with a `ReferentiallyOpaque` exception.  Same thing for environment variables: remote imports cannot reference environment variables.  More generally, there is a check that anything remote cannot import anything local.  See:

https://github.com/dhall-lang/dhall-haskell/blob/0257e860466249f027bf1266c458239184e613d0/src/Dhall/Import.hs#L203-L228

https://github.com/dhall-lang/dhall-haskell/blob/0257e860466249f027bf1266c458239184e613d0/src/Dhall/Import.hs#L786-L795

https://github.com/dhall-lang/dhall-haskell/issues/162#issuecomment-352228811

**Comment by Gabriel439** [comment]
This is also why I want to finish standardizing the semantics because the last thing to standardize is the import semantics, which includes details like this

**Comment by ocharles** [comment]
Ohhhh, that makes sense. I was surprised when I saw an imported file import
another file, then it did what I wanted. This all sounds sane to me, think
this can be closed.

On 14 Jan 2018 3:41 pm, "Gabriel Gonzalez" <notifications@github.com> wrote:

@ocharles <https://github.com/ocharles>: Note that the example works if you
instead do:

$ dhall <<< './a/b`

The only reason it failed was because you fed ./a/b through standard input
so Dhall doesn't know what where standard input is coming from, so Dhall
assumed it was relative to the current directory by default.

Also, Dhall does handle paths relative to HTTP imports. For example, if you
import http://example.com/foo/bar and then that imports ./baz then the
relative import will resolve to http://example.com/foo/baz

HTTP imports cannot import things from the local filesystem (of either the
server or client). For example, if the http://example.com/foo/baz import
tried to import an absolute path like /baz then the import would fail with
a ReferentiallyOpaque exception. Same thing for environment variables:
remote imports cannot reference environment variables. More generally,
there is a check that anything remote cannot import anything local. See:

https://github.com/dhall-lang/dhall-haskell/blob/
0257e860466249f027bf1266c458239184e613d0/src/Dhall/Import.hs#L203-L228

https://github.com/dhall-lang/dhall-haskell/blob/
0257e860466249f027bf1266c458239184e613d0/src/Dhall/Import.hs#L786-L795

dhall-lang/dhall-haskell#162 (comment)
<https://github.com/dhall-lang/dhall-haskell/issues/162#issuecomment-352228811>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dhall-lang/dhall-lang/issues/68#issuecomment-357520227>,
or mute the thread

**Comment by Gabriel439** [comment]
You're welcome! :)

**Comment by Profpatsch** [comment]
That was the reason I added https://github.com/dhall-lang/dhall-haskell/pull/190.
It’s a bit confusing that stdin doesn’t have a file context (all the while dhall doesn’t allow for a filename as import). Right now I don’t have a strong opinion yet on whether a `--file` flag or similar should exist, but playing further with evaluating dhall expressions in nix builds might change that.
