### ISSUE TITLE
Capability to override default values with provided via ENV

### ISSUE THREAD

**Issue by SkyWriter** [dhall-lang/dhall-lang#70]
I was wondering if there's a way to provide default values for undefined (or possibly blank) environment variable values. E.g. say I have a default service URL value of "http://some.svc/", but I want to be able to override it with a SERVICE_URL env variable.

Looking at the Haskell implementation I figure there's an exception thrown as soon as lookupEnv fails, which seemingly eliminates possibilities of handling it within Dhall domain.

If this is a part of the language standard, I propose changing it in some way at some point to accommodate for the use case.

**Comment by Gabriel439** [comment]
Another approach might be to provide a way to convert an import to return an `Optional` value then the user can use `Optional/fold` to supply a default value if the import is absent.

The other reason that I suggest this is that at some point Dhall might have an operator similar to Haskell's `(<|>)` operator specialized to `Maybe` that allows chaining optional values as fallbacks.  In other words, something like the following pseudo-code:

```haskell
    let importedValue : Optional Text =
          http://www.example.com/foo as Optional <|> /etc/foo as Optional <|> env:FOO as Optional
in  let finalValue = Optional/fold Text importedValue Text (λ(x : Text) → x) "{foo not found}"
in  finalValue
```

**Comment by f-f** [comment]
I was also wondering about this, but I'm conflicted about the matter:
- having the program fail if the envvar is not there makes it safer, because you have to consciously provide it, and it will not just silently run without the possibly critical value.
- however:
  - it's really nice to be able to not make the program fail for some non-critical value for which we can give defaults
  - it's really nice to be able to branch at runtime based on the presence of an envvar or not

So I'm not sure we should actually go for this, but in case we want to:
I propose that we add the `envOpt` prefix for returning an optional envvar.
Could look something like this:

```haskell
-- suppose our ENV looks like this:
-- - var A set to "λ(a : Bool) → if a then 1 else 2"
-- - var B not set
-- - var C set to "Some text"

   let a = envOpt:A as Optional (∀(a : Bool) → Integer)
in let b = envOpt:B as Optional (∀(a : Bool) → Integer)
in let c = envOpt:C as Optional Text

-- then:
-- a = ([ λ(a : Bool) → if a then 1 else 2 ] : Optional (∀(a : Bool) → Integer))
-- b = ([] : Optional (∀(a : Bool) → Integer))
-- c = ([] : Optional Text)
```

In this way we would have both possibilities of throwing in case the var is compulsory (with `env`), but also make it possible to make a variable optional (with `envOpt`).

**Comment by Gabriel439** [comment]
@f-f: I have a proposal for how to do this here: https://github.com/dhall-lang/dhall-lang/issues/163
