### ISSUE TITLE
Questions regarding type-inference for `merge`

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-lang#749]
I have a few questions regarding this rule:

```
Γ ⊢ t : { y : ∀(x : A₀) → T₀, ts… }
Γ ⊢ u : < y : A₁ | us… >
Γ ⊢ (merge { ts… } < us… > : T₁) : T₂
A₀ ≡ A₁
↑(-1, x, 0, T₀) = T₁
────────────────────────────────────  ; `x` not free in `T₀`
Γ ⊢ merge t u : T₀
```

Firstly, I suspect that there are typos in the rule, and we actually want this:

```diff
     ↑(-1, x, 0, T₀) = T₁
-    ────────────────────────────────────  ; `x` not free in `T₀`
-    Γ ⊢ merge t u : T₀
+    ────────────────────────────────────  ; `x` not free in `T₁`
+    Γ ⊢ merge t u : T₁
 
```

Then, I don't really understand the "x not free"-constraint. We do have a failure test that is rejected due to this constraint:

https://github.com/dhall-lang/dhall-lang/blob/76494a43c48e6a5c3db6510918d138c27d055835/tests/type-inference/failure/unit/MergeHandlerFreeVar.dhall#L1

But why shouldn't we actually infer `Optional Bool` here?

**Comment by sjakobi** [comment]
So `x not free in T₀` ensures that the result type cannot depend on the union value. That makes sense, but it seems limiting now that we have dependent types:

```
⊢ merge { y = (\(x : Natural) -> assert : x === x) } (< y : Natural>.y 1)

it : Natural

Error: Unbound variable: x
```

This example is a bit useless, but it would be nice if it could be accepted.

**Comment by sjakobi** [comment]
Ah, no. The result type would  again be unclear. My example is fine to be rejected.

**Comment by Nadrieril** [comment]
Huh, it actually seems that there is a type for my example above:
```
let foo
   : forall(u: <x: Type>) -> merge { x = \(T: Type) -> Optional T } u
   = \(u: <x: Type>) -> merge { x = None } u
```
Your example would be:
```
let foo
   : forall(u: <x: Natural>) -> merge { x = \(y: Natural) -> y === y } u
   = \(u: <x: Natural>) -> merge { x = (\(y : Natural) -> assert : y === y) } u
```

More generally, I think we have
```
let foo
   : forall(u: union_type) -> merge match_types u
   = \(u: union_type) -> merge match u
```
where `match_types` can be derived from the type of `match` somehow. I'm not quite clear how, since above we transformed `None : forall(T: Type) -> Optional T` into `\(T: Type) -> Optional T` for example, and I'm not sure this operation can be generalized.
Am I missing something here or do my examples actually make sense ?

**Comment by Gabriel439** [comment]
The way I reason through these things is to desugar to lower-level primitives.

First, let's start off with the reason why `x` is supposed to not be free in `T₀`.  If we take the following type:

```dhall
< y₀ : A₀ | y₁ : A₁ | … >
```

... and desugar that to use records but not unions, we get what is essentially a pre-formed `merge` that has been applied to a union literal, but not yet applied to a record of handlers:

```dhall
  ∀(T : Type)
→ ∀(handlers : { y₀ : A₀ → T, y₁ : A₁ → T, … })
→ T
```

... where `T` corresponds to the type annotation for the `merge` (either explicit or inferred) and `handlers` represents our record of handlers.

If you make the variable bound by each handler type explicit:

```dhall
  ∀(T : Type)
→ ∀(handlers : { y₀ : ∀(x₀ : A₀) → T, y₁ : ∀(x₁ : A₁) → T, … })
→ T
```

... then this illustrates why the variable bound by each handler (i.e. `xₙ`) cannot appear in the result type for each handler (i.e. `T`): because `xₙ` is not in scope when `T` is bound.  This is where the "`x₀` is not free in `T`" restriction comes from.

However, there is another way we could have encoded this, which is to make `T` a dependent function from something to a type, like this pseudo-code:

```dhall
  ∀(T : ??? → Type)
→ ∀(handlers : { y₀ : ∀(x₀ : A₀) → T x₀, y₁ : ∀(x₁ : A₁) → T x₁, … })
→ T ???
```

... but there is already one problem with this: this doesn't work if each handler has a different type since we apply `T` to each `xₙ`, each of which has a different type `Aₙ`.

Okay, but what if we restrict this to the case where every handler has the same input type?

```dhall
  ∀(T : A → Type)
→ ∀(handlers : { y₀ : ∀(x₀ : A) → T x₀, y₁ : ∀(x₁ : A) → T x₁, … })
→ T ???
```

This gets us a bit further, but we still have one hole: what do we replace `???` with?

Well, we really want `???` to be the selected union alternative, but how do we get that in scope?

Remember that the above is analogous to a pre-formed `merge` (i.e. `merge someUnionLiteral`):

```dhall
merge (someUnionLiteral : < y₀ : A | y₁ : A | … >)
  : ∀(T : A → Type)
  → ∀(handlers : { y₀ : ∀(x₀ : A) → T x₀, y₁ : ∀(x₁ : A) → T x₁, … })
  → T ???
```

So if we abstract out the union literal itself, we can pretend that `merge` has this dependent pseudo-type:

```dhall
merge
  : ∀(someUnionLiteral : < y₀ : A | y₁ : A | … >)
  → ∀(T : A → Type)
  → ∀(handlers : { y₀ : ∀(x₀ : A) → T x₀, y₁ : ∀(x₁ : A) → T x₁, … })
  → T (merge someUnionLiteral { y₀ = λ(x₀ : A) → x₀, y₁ = λ(x₁ : A) → x₁, … } : A)
```

... which I believe is equivalent to what @Nadrieril is proposing, which seems like it might work if all alternatives are restricted to the same type.

That said, this is still a bit of an informal treatment it seems like the risk of introducing potential unsoundness might outweigh the utility of this, especially since I haven't seen a use case for this.

**Comment by philandstuff** [comment]
I think this is perfectly possible. `merge` is the recursion principle for coproduct types, and what we’re looking for is an induction principle for coproduct types. 

I think a reasonably good reference for this is section 1.7 of the Homotopy Type Theory book - despite the name, chapter 1 only deals with plain Martin-Löf type theory so is suited to our needs. 

In particular, we don’t need to restrict all the handlers to have the same type if we parameterise the output type family on the whole union:

```
  ∀(T : U → Type)
→ ∀(handlers : { y₀ : ∀(x₀ : A₀) → T (U.x₀ x₀), y₁ : ∀(x₁ : A₁) → T (U.x₁ x₁), … })
→ T u
```

Having said all this, while I think a dependent `merge` is achievable, I also think:

- we still need a non-dependent merge for a dependent merge to use to construct the output type family 
- there is a distinct lack of use cases for this feature

So I’d prefer to hold off on implementing this for now.

**Comment by sjakobi** [comment]
Many thanks for the explanations @Gabriel439! :+1: 

I'm not so interested in allowing more `merge`-expressions, but I'd be interested to hear what you think about my concerns about the correctness of the judgment in the issue description and in https://github.com/dhall-lang/dhall-lang/issues/749#issuecomment-534533035.

**Comment by philandstuff** [comment]
Oops. Yes I agree that there is a typo and it should be `T₁`.

Also I agree that `<us… >` is problematic. 

I think the fix is a little cumbersome but looks like this:

```
Γ ⊢ u : < y : A₁ | us… >
Γ ⊢ u₁ : < us… >
Γ ⊢ (merge { ts… } u₁ : T₁) : T₂
```

**Comment by sjakobi** [comment]
@philandstuff That's looks like a neat approach! It's a bit funny to make up the `u₁` term based on its type, but since the type is really all we care about, it should be fine! :+1:

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, we need to update the syntax of that rule to suggest a union literal.  It was added back when we had old-style union literals but even then it was ambiguous about whether it represented a literal or a type

**Comment by sjakobi** [comment]
Ah, somehow I missed that it's the same issue with the record of handlers where we're also currently abusing a record type as a record value…
