### ISSUE TITLE
Optional record fields again

### ISSUE THREAD

**Issue by torgeirsh** [dhall-lang/dhall-lang#778]
I read the discussion in issue #113 where one solution for optional fields is to define all fields as Optional with a default value of None, and use // to override certain fields with Some. There was a request to be able to write "defaults // { cpus = 1 }" instead of "defaults // { cpus = Some 1 }" (i.e. drop the Some constructor), but it was pointed out that it would break the associativity of //, and make it impossible to write an update { cpus = None Natural } which clears a previously set field.

While the reasons to not modify // are sound, I feel that prefixing each field with Some has considerable impact on the signal-to-noise ratio of large record updates. Would a separate operator for this be viable?

**Comment by Gabriel439** [comment]
@torgeirsh: You might first want to read this issue if you haven't already:

https://github.com/dhall-lang/dhall-lang/issues/382

The reason I mention that issue is that the fix to that introduces a new `::` operator, where:

```dhall
T::r
```

... is the same thing as:

```dhall
(T.default // r) : T.Type
```

So if were to introduce a new operator then the `T::r` operator would not benefit from the behavior (since it is defined in terms of `//`).

That said, I don't think the overhead of `Some` is too bad.  I think most of the issues with `Some` can be fixed by tweaking the formatter in conjunction with using the above operator (see the linked issue for some examples of this).

**Comment by Gabriel439** [comment]
@torgeirsh: You will still have to repeat `Some` 20 times.  It's just that the operator removes a lot of syntactic noise, so you end up with something like this:

```dhall
{ foo = Some Foo::{
    , bar = Some Bar::{
        , …
        }
    , baz = Some Baz::{
        , …
        }
    }
}
```

**Comment by Gabriel439** [comment]
@torgeirsh: Here's a more fully-worked example of what I mean:

https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/4ccc139f437d9aeecf595ee935099d8a54c71682/examples/aws-iam-authenticator-chart.dhall

I don't think the `Some` detract much from the above example

**Comment by torgeirsh** [comment]
In the example it seems most fields aren't optional, so there's naturally less noise from Some than in cases where all fields are optional (e.g. when you want to be able to leave out fields from the YAML/JSON). I haven't worked much with Dhall yet, so I'm not sure how often cases like that come up though.

**Comment by philandstuff** [comment]
This issue is quite old. I’m going to close it, but please reopen if this is still a problem that needs further discussion.
