### ISSUE TITLE
Idle idea: Record Constructors

### ISSUE THREAD

**Issue by SiriusStarr** [dhall-lang/dhall-lang#866]
Not something I feel horribly strongly about, but just a topic of conversation.  I find myself doing things like:
```haskell
let Point = { xCoord : Natural, yCoord : Natural }

let makePoint
    : Natural → Natural → Point
    =   λ(xCoord : Natural)
      → λ(yCoord : Natural)
      → { xCoord = xCoord, yCoord = yCoord }

in makePoint 117 3
```
quite frequently in Dhall.  Not the end of the world, of course, but mildly annoying boilerplate.

Elm has a feature called record constructors where, if you declare an alias for a record type, it overloads that alias to also be a constructor for said record.  For example:
```elm
> type alias Point = { xCoord : Int, yCoord : Int }
> Point 117 3
{ xCoord = 117, yCoord = 3 } : Point
```

Thoughts on being able to do this in Dhall?  E.g.
```haskell
let Point = { xCoord : Natural, yCoord : Natural }

in Point 117 3
```

This shouldn't be a breaking change at all, as any expression that this would allow for would be invalid in current Dhall, since it'd throw `Error: Not a function`.

The issue I foresee is that Dhall normalizes the order of record fields, which record constructors depend on, so this may be insurmountable.

**Comment by Gabriel439** [comment]
@SiriusStarr: I generally try to avoid the use of anonymous fields because they require the reader of the code to know what order the fields were defined in.  If the named fields are instantiated explicitly it lessens the burden on the reader.

However, if were to go this route I want to mention an idea I floated [in another discussion](https://github.com/dhall-lang/dhall-lang/issues/224) about unions being generalized to support more than one anonymous field.

In other words, you could declare:

```dhall
let Point = < MakePoint Natural Natural >

in  Point.MakePoint 117 3
```

One of the reason I suggest this is that then there would be an almost one-to-one correspondence between Dhall unions and Haskell data types.  For example, this Haskell type:

```haskell
data Foo = Bar Natural Natural | Baz

examples :: [ Foo ]
examples = [ Bar 1 2, Baz ]
```

... would correspond to this Dhall type:

```dhall
let Foo = < Bar Natural Natural | Baz >

let example : List Foo
    examples = [ Foo.Bar 1 2, Foo.Baz ]

…
```

That said, I still would personally prefer for the language to encourage users to idiomatically use named fields instead of anonymous fields.

**Comment by sjakobi** [comment]
> However, if were to go this route I want to mention an idea I floated [in another discussion](https://github.com/dhall-lang/dhall-lang/issues/224) about unions being generalized to support more than one anonymous field.
> 
> In other words, you could declare:
> 
> ```haskell
> let Point = < MakePoint Natural Natural >
> 
> in  Point.MakePoint 117 3
> ```

Side note:

While looking at https://github.com/dhall-lang/dhall-haskell/pull/1608/files#diff-e793430bac333df8f3e5883e5a070b20R1204-R1207 again, I noticed that union alternatives with multiple fields would make it harder to reliably detect "union literals" in implementations.

**Comment by SiriusStarr** [comment]
Honestly I don't hate being restricted to single field unions (though it might be nice from an integration perspective to have multiple).  It's not immediately obvious/transparent how multiple field unions would translate to JSON; presumably they'd get converted to an object with special named fields, e.g.
```
let Point = < MakePoint Natural Natural >

in Point.MakePoint 117 3
```
becoming
```
{ "_1" : 117, "_2" : 3}
```
(Stealing from tuple representation.)  The other option would be converting to an array, but that seems like a bad idea, given non-fixed length and the problems with decoding mixed-type arrays in some endpoints.

Regardless, I'm fine with record constructors not ever becoming a thing (since there is certainly a safety/maintainability potential issue there), it's just boilerplate I find myself writing quite a lot of.
