### ISSUE TITLE
More Questions than Issues

### ISSUE THREAD

**Issue by deknos** [dhall-lang/dhall-lang#874]
Hi,
i have more questions than issues which i could not answer by reading your Readme.

1. is dhall statically or dynamically typed? (as far one can say that for a non-turing-language)
2. will you submit your language to the IETF? That usually shows the long term commitment and brings broader acceptance in the industry and community
3. Is the basic/canonic representation of your language bijective? like, there's no representation which does the same but has other control characters or encodings (think  like Trigraphs from C, or the various ASN.1 Encodings.

I am really interested in your language.

yours, dennis

**Comment by Gabriel439** [comment]
1. Dhall is statically typed in the sense that expressions are always type-checked before they are evaluated, so you can never evaluate an ill-typed expression

2. I would like to propose submitting Dhall as an IETF standard at some point, but (A) that decision is not mine alone to make (See: [How do changes get approved?](https://github.com/dhall-lang/dhall-lang/blob/master/.github/CONTRIBUTING.md#how-do-changes-get-approved)) and (B) I personally think it is premature to do so at this moment

   The main thing I'm personally looking for before proposing IETF standardization is Dhall language bindings for most mainstream languages (e.g. Java/JavaScript/Python/C# for starters).  That would be a good empirical indicator that the language is sufficiently stable to be standardized

3. The language has a canonical representation which is the [CBOR encoding](https://github.com/dhall-lang/dhall-lang/blob/master/standard/binary.md)

   We use this representation in the standard test suite when we need something completely unambiguous.  This is also the same representation we use when hashing expressions.  I'm not sure if it is bijective according to your definition since it depends on what equivalence relationship you had in mind.

**Comment by sjakobi** [comment]
What does it mean to submit Dhall as an IETF standard?

**Comment by Gabriel439** [comment]
@sjakobi: To create an RFC, like the one for [CBOR](https://tools.ietf.org/html/rfc7049)

**Comment by deknos** [comment]
i meant unambiguous, bijective is the wrong expression, i am sorry. and thanks for your answers!

and it does not have to be one RFC, it could be a small number of them, too. DNSSEC and MIME have each several ones...

**Comment by Gabriel439** [comment]
@deknos: Yeah, I understand that it is possible to amend the standard by publication of follow-up RFCs.

Some of the reasons I'm waiting for a few new language bindings are:

* So far each new language binding ends up improving the quality and precision of the standard as a fresh pair of eyes attempts to implement the language

  So waiting for a few more bindings will ensure that the first RFC is less likely to be ambiguous

* Each new language binding gets to vote on proposed changes to the standard

  As the number of language bindings increases and the number of votes increases I expect that the threshold for proposing changes will get higher and the language will naturally stabilize

* Language bindings for mainstream languages will help provide "social proof" that the language is ready for the standardization track

**Comment by sjakobi** [comment]
@deknos If your questions have been answered, could you close this issue? Or is there more to do here?
