### ISSUE TITLE
Pretty version of JSON.render?

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-lang#932]
I've been having some issues with renderYAML (#931 and #927 ), so I've been toying with the idea of just rendering JSON instead of YAML. Since YAML is a superset of JSON (https://yaml.org/spec/1.2/spec.html#id2759572), I'm wondering if there's all that much benefit to supporting both renderings. It seems like machine-generated YAML is about as readable as machine-generated JSON, the only real benefit is that it "looks more YAML-y".

The main downside of the current JSON.render implementation is that it's compact (no linebreaks or indentation). I'd be happy to have a go at it, would you be open to implementing the same kinds of linebreaks / structural indentation in `render` as is currently done in `renderYAML`? The comments say it's handy for testing, so would we still want to support a compact rendering for that use case?

If it _did_ share indentation-related code between the two implementations, is there a place to put that? (i.e. shared but not an exposed part of the Prelude API)? I guess it could become a `renderTo` function which takes `<yaml|json>` as an argument, possibly with an additional `{ pretty: bool }` argument for JSON rendering.

**Comment by ari-becker** [comment]
>  I'm wondering if there's all that much benefit to supporting both renderings.

What I did today at work: writing type-safe Elasticsearch configuration, one possible rendering of which will be for including it directly into a Kubernetes ConfigMap, so that the YAML configuration will be reproduced exactly on-disk. If I didn't have access to the `renderYAML`, then my life would probably be harder (maybe straight JSON would work, maybe not, certainly it would be more difficult to make one-off changes straight to the ConfigMap if necessary).

In general I see most of the value of both of these `render` functions where the tool requires JSON or YAML to be represented, for some reason, as straight text, within a larger configuration file which is itself JSON or YAML. For example, [Kops](https://github.com/kubernetes/kops) [requires](https://github.com/kubernetes/kops/blob/b6c849cfb7263c04129dded841888bb645a03b39/docs/iam_roles.md#adding-additional-policies) additional IAM policies to be added to an EC2 role [to be included as Text](https://github.com/coralogix/dhall-kops/blob/master/api/v1alpha2/ClusterSpec.dhall#L80), so we have a [little helper library](https://github.com/coralogix/dhall-aws/blob/master/iam/Policy.dhall) that generates type-safe IAM policies through the `Prelude.JSON.render` paradigm and injects it into the `ClusterSpec` record as needed.

**Comment by Gabriel439** [comment]
@timbertson: Yeah, I think there is value in a prettier JSON renderer that is customizable.  One other thing worth customizing would be how much to indent each nesting level.

I also agree that we can factor out shared rendering code possibly in a directory nested inside the `./Prelude/JSON` directory.  Some of those utilities could also be factored out into a new `NonEmpty` type, too, since `NonEmpty` operations are used a bit within the implementation of `renderYAML`

**Comment by ari-becker** [comment]
> > maybe straight JSON would work, maybe not
> 
> My point was that it will, since all valid JSON is also valid YAML.

It's not only technical consideration at play. Hand-editing configuration post-deployment can be a valuable way of prototyping a proposed fix and getting fixes deployed sooner than a process that requires checking code out from source control, changing it, committing it, and waiting for a pipeline to run. You throw out all semblance of safety when you do so, of course, but it's a trade-off.

So for what it's worth, I also think that a pretty version of `JSON.render` would be valuable, because trying to hand-edit collapsed/minimal JSON is a pain. I just want to help illustrate some of the valuable use-cases behind having two different render methods.

**Comment by Profpatsch** [comment]
So far I’m just piping through `jq` or a similar tool if I need pretty JSON

**Comment by timbertson** [comment]
I've made an initial attempt at pretty JSON rendering in #936

**Comment by timbertson** [comment]
Done in #936 🎉
