### ISSUE TITLE
Possible to have Nix-like rec syntax for records?

### ISSUE THREAD

**Issue by gamb** [dhall-lang/dhall-lang#945]
E.g. `rec { a = 1, b = a }`? Unable to find relevant discussion, sorry if this has come up already.

**Comment by Nadrieril** [comment]
I don't think this has come up already.
The closer you can do right now would be
```dhall
let a = 1
in { a, b = a }
```
Would that be convenient enough ?

**Comment by Gabriel439** [comment]
@gamb: One technical issue is that record fields are not ordered, so you could end up with issues for code like this:

```haskell
let a = 1

let b = 2

in  rec { b = a, a = b }
```

That record could potentially be interpreted as `{ b = 1, a = 1 } ` or `{ a = 2, b = 2 }` depending on how you define things, and the correct answer wouldn't be obvious to the user.

My recommendation is also to use `let` definitions + record puns so that there's no ambiguity.

**Comment by gamb** [comment]
@Gabriel439: Thanks, that makes sense.

**Comment by Gabriel439** [comment]
@gamb: You're welcome!

**Comment by Profpatsch** [comment]
In nix `rec` introduces the ability to do arbitrary recursions iirc (it has the same semantics as nix’s `let`, which is recursive).
